// -----------------------------------------------------------------------------
// sRGB IEC61966-2.1 ICC profile (v4, 588 bytes, generated by Little-CMS).
//
// Why this exists: html2canvas / <canvas> rasters are *untagged* DeviceRGB.
// Untagged device colour is what fails PDF/X-4 preflight — PDF/X-4 itself
// permits device-independent (ICC-tagged) colour, so tagging each raster as
// ICCBased/sRGB can produce a conforming file with the RIP doing the CMYK
// separation. That is a far smaller job than building a CMYK emission path.
//
// IMPORTANT: whether RGB-in / RIP-separates is acceptable is a question for
// the printer, not for this file. Confirm with them before assuming this
// removes the need for an approved CMYK palette.
//
// Small enough to inline as base64, so there is no fetch to fail mid-export.
// -----------------------------------------------------------------------------

const SRGB_ICC_BASE64 =
  "AAACTGxjbXMEQAAAbW50clJHQiBYWVogB+oACAAUABEADgACYWNzcEFQUEwAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1sY21zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAALZGVzYwAAAQgAAAA2Y3BydAAAAUAAAABMd3RwdAAAAYwAAAAUY2hh" +
  "ZAAAAaAAAAAsclhZWgAAAcwAAAAUYlhZWgAAAeAAAAAUZ1hZWgAAAfQAAAAUclRSQwAAAggAAAAg" +
  "Z1RSQwAAAggAAAAgYlRSQwAAAggAAAAgY2hybQAAAigAAAAkbWx1YwAAAAAAAAABAAAADGVuVVMA" +
  "AAAaAAAAHABzAFIARwBCACAAYgB1AGkAbAB0AC0AaQBuAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAA" +
  "ADAAAAAcAE4AbwAgAGMAbwBwAHkAcgBpAGcAaAB0ACwAIAB1AHMAZQAgAGYAcgBlAGUAbAB5WFla" +
  "IAAAAAAAAPbWAAEAAAAA0y1zZjMyAAAAAAABDEIAAAXe///zJQAAB5MAAP2Q///7of///aIAAAPc" +
  "AADAblhZWiAAAAAAAABvoAAAOPUAAAOQWFlaIAAAAAAAACSfAAAPhAAAtsNYWVogAAAAAAAAYpcA" +
  "ALeHAAAY2XBhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbY2hybQAAAAAAAwAAAACj1wAA" +
  "VHsAAEzNAACZmgAAJmYAAA9c";

let cached: Uint8Array | null = null;

/** Raw bytes of the sRGB ICC profile. Cached after first decode. */
export function sRgbIccBytes(): Uint8Array {
  if (cached) return cached;
  const bin = atob(SRGB_ICC_BASE64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  cached = out;
  return out;
}

export const SRGB_ICC_PROFILE_NAME = "sRGB IEC61966-2.1";
