// Curated icon library exposed to the deck editor so users can pick an icon
// per item/slide, overriding the label-based auto-match in VariantRenderer.

import {
  Sparkles,
  Workflow,
  Layers3,
  Users,
  ShieldCheck,
  Target,
  Rocket,
  LineChart,
  Search,
  Cog,
  MessageSquareQuote,
  Building2,
  Landmark,
  Cpu,
  Factory,
  Store,
  HeartPulse,
  Car,
  Plane,
  Coins,
  Calendar,
  ArrowRight,
  CheckCircle2,
  AlertTriangle,
  TrendingUp,
  GitBranch,
  Globe2,
  Lightbulb,
  ClipboardList,
  FileCheck2,
  Send,
  MessagesSquare,
  Mail,
  Phone,
  Timer,
  Trophy,
  Puzzle,
  Handshake,
  Play,
  BarChart3,
  Zap,
  ArrowUpRight,
  Award,
  Book,
  Briefcase,
  Cloud,
  Code2,
  Database,
  FileText,
  Flag,
  Gauge,
  Gift,
  Hammer,
  Heart,
  Home,
  Key,
  Layers,
  Link as LinkIcon,
  Lock,
  Map,
  MessageCircle,
  Package,
  PenTool,
  PieChart,
  Presentation,
  Scale,
  Server,
  Settings,
  Shield,
  Star,
  Table,
  ThumbsUp,
  Truck,
  Video,
  Wallet,
  Wrench,
  Activity,
  Anchor,
  Aperture,
  Archive,
  AtSign,
  Atom,
  Axe,
  BadgeCheck,
  Ban,
  Banknote,
  Barcode,
  Battery,
  Beaker,
  Bell,
  Bike,
  Binary,
  Blocks,
  Bluetooth,
  Bold,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Braces,
  Brain,
  BriefcaseBusiness,
  Brush,
  Bug,
  Building,
  Bus,
  Cable,
  Calculator,
  CalendarCheck,
  CalendarClock,
  Camera,
  CircleDollarSign,
  CircuitBoard,
  Clipboard,
  ClipboardCheck,
  Clock,
  CloudCog,
  CloudUpload,
  Compass,
  Component,
  Contact,
  Container,
  Cookie,
  Copy,
  CreditCard,
  Crop,
  Crosshair,
  Crown,
  Cylinder,
  Diamond,
  Dna,
  Download,
  Drama,
  Droplet,
  Ear,
  Earth,
  Eye,
  Feather,
  FileBadge,
  FileCode,
  FileSearch,
  FileSpreadsheet,
  FileStack,
  Files,
  Film,
  Focus,
  FolderOpen,
  Folders,
  Footprints,
  Forklift,
  Frame,
  Fuel,
  Funnel,
  Gamepad2,
  Gavel,
  Gem,
  Globe,
  GraduationCap,
  Grid3x3,
  Group,
  Hand,
  HandCoins,
  HardDrive,
  HardHat,
  Hash,
  Headphones,
  Hexagon,
  Highlighter,
  History,
  Hospital,
  Hourglass,
  IdCard,
  Image,
  Images,
  Inbox,
  Infinity,
  Info,
  Keyboard,
  Lamp,
  Languages,
  Laptop,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Library,
  LifeBuoy,
  Ligature,
  ListChecks,
  ListOrdered,
  Loader,
  Locate,
  MapPin,
  Maximize,
  Medal,
  Megaphone,
  Menu,
  Merge,
  Mic,
  Microscope,
  Milestone,
  Minimize,
  Monitor,
  Moon,
  MousePointer,
  Move,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Orbit,
  Palette,
  Paperclip,
  PartyPopper,
  Pause,
  PenLine,
  Percent,
  PersonStanding,
  Pill,
  Pin,
  Pipette,
  Plug,
  Podcast,
  Pointer,
  Power,
  Printer,
  QrCode,
  Quote,
  Radar,
  Radio,
  Receipt,
  Recycle,
  Redo2,
  RefreshCw,
  Regex,
  Repeat,
  Replace,
  Reply,
  Rewind,
  Route,
  Rss,
  Ruler,
  Satellite,
  Save,
  Scan,
  ScanLine,
  School,
  Scissors,
  ScreenShare,
  Scroll,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sigma,
  Signal,
  Siren,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Snowflake,
  Sparkle,
  Speaker,
  Spline,
  Split,
  Square,
  SquareStack,
  Stamp,
  Stethoscope,
  Sticker,
  StickyNote,
  Sun,
  Sunrise,
  Syringe,
  Tag,
  Tags,
  Telescope,
  Tent,
  Terminal,
  TestTube,
  TextCursor,
  Thermometer,
  Ticket,
  Trash2,
  TreePine,
  TrendingDown,
  Triangle,
  Type,
  Umbrella,
  Undo2,
  Unlink,
  Upload,
  UserCheck,
  UserCog,
  UserPlus,
  Utensils,
  Variable,
  Vault,
  Vibrate,
  View,
  Voicemail,
  Volume2,
  Warehouse,
  Watch,
  Waves,
  Webhook,
  Wifi,
  Wind,
  ZoomIn,
  Ampersand,
  Asterisk,
  Badge,
  BadgeAlert,
  BellRing,
  BookmarkCheck,
  Circle,
  CircleCheck,
  CircleDot,
  CircleHelp,
  Clover,
  Dot,
  Egg,
  Flame,
  Flower,
  Flower2,
  Goal,
  Octagon,
  Pentagon,
  Rainbow,
  Ribbon,
  Shapes,
  ShieldAlert,
  ShieldPlus,
  Signature,
  Snail,
  Squircle,
  Sunset,
  ThumbsDown,
  Torus,
  Verified,
  Waypoints,
  Wand,
  Wand2,
  Wheat,
  ZapOff,
  AlarmClock,
  ArrowDownUp,
  ArrowLeftRight,
  ArrowUpDown,
  Blend,
  CalendarRange,
  CalendarSync,
  ChartGantt,
  CheckCheck,
  ChevronsRight,
  CircleArrowRight,
  ClipboardPen,
  Combine,
  ConciergeBell,
  Construction,
  Drill,
  FastForward,
  Filter,
  Fingerprint,
  FlaskConical,
  FolderSync,
  Forward,
  Grid2x2,
  IterationCcw,
  Kanban,
  ListTodo,
  Loader2,
  LockOpen,
  Logs,
  Magnet,
  MoveRight,
  PackageCheck,
  PackageOpen,
  Paintbrush,
  PanelsTopLeft,
  Pencil,
  PencilRuler,
  PlayCircle,
  Plus,
  Repeat2,
  ReplaceAll,
  RotateCcw,
  RotateCw,
  ScrollText,
  SendHorizontal,
  SkipForward,
  SquareCheck,
  SquarePen,
  StepForward,
  TicketCheck,
  TimerReset,
  ToggleRight,
  Accessibility,
  Baby,
  Backpack,
  BookUser,
  Cake,
  Church,
  ContactRound,
  Frown,
  Glasses,
  HandHeart,
  HandHelping,
  HandMetal,
  HeartHandshake,
  Laugh,
  MailOpen,
  Meh,
  MessageCircleHeart,
  MessageSquareHeart,
  MessageSquareText,
  Mic2,
  PhoneCall,
  Speech,
  UserCircle,
  UserMinus,
  UserPen,
  UserRound,
  UserRoundCheck,
  UserSearch,
  UserStar,
  UserX,
  Users2,
  UsersRound,
  Vote,
  Antenna,
  AreaChart,
  Bolt,
  BookOpenCheck,
  Brackets,
  ChartArea,
  ChartBar,
  ChartBarBig,
  ChartColumn,
  ChartLine,
  ChartNetwork,
  ChartNoAxesColumn,
  ChartPie,
  ChartScatter,
  ChartSpline,
  CloudDownload,
  Columns3,
  DatabaseBackup,
  DatabaseZap,
  DollarSign,
  FileBarChart,
  FileDigit,
  FileJson,
  FolderTree,
  GitCommitHorizontal,
  GitCompare,
  GitFork,
  GitMerge,
  GitPullRequest,
  Layers2,
  MemoryStick,
  MonitorDot,
  Radius,
  Rows3,
  SatelliteDish,
  ServerCog,
  Sheet,
  SignalHigh,
  SquareFunction,
  Table2,
  TabletSmartphone,
  TerminalSquare,
  TicketPercent,
  Weight,
  Anvil,
  Apple,
  Armchair,
  Beef,
  Bitcoin,
  Bone,
  BookMarked,
  BriefcaseMedical,
  Cannabis,
  CarFront,
  Caravan,
  Clapperboard,
  Cross,
  Dam,
  Drum,
  Dumbbell,
  Fence,
  Fish,
  Flashlight,
  FlaskRound,
  Grape,
  Handbag,
  Haze,
  Hotel,
  House,
  LandPlot,
  MapPinned,
  Milk,
  Mountain,
  MountainSnow,
  Nut,
  Palmtree,
  Pickaxe,
  PillBottle,
  PlaneTakeoff,
  Popcorn,
  Projector,
  Radiation,
  Sailboat,
  Shirt,
  ShoppingBasket,
  Shovel,
  Signpost,
  Ship,
  Sprout,
  Theater,
  Tractor,
  TrainFront,
  TreePalm,
  Tv,
  Wine,
  AudioLines,
  BrainCircuit,
  Cast,
  ClosedCaption,
  Cloudy,
  FileAudio,
  FileVideo,
  Instagram,
  Italic,
  Link2,
  Linkedin,
  Mails,
  MessageCircleMore,
  MessageSquare,
  MessageSquareDashed,
  MicVocal,
  MonitorPlay,
  Music2,
  PhoneOutgoing,
  ReplyAll,
  Share2,
  Subtitles,
  Text,
  TextQuote,
  Twitter,
  Underline,
  Videotape,
  Youtube,
  Album,
  ArchiveRestore,
  Bed,
  Binoculars,
  BookCopy,
  Coffee,
  Diameter,
  Disc,
  Disc3,
  Eraser,
  ExternalLink,
  File,
  FileCheck,
  FileHeart,
  FileLock,
  FilePen,
  FilePlus,
  FileType,
  FlagTriangleRight,
  Grid2x2Check,
  KeyRound,
  LampDesk,
  Luggage,
  Mailbox,
  Mouse,
  Ratio,
  ScanFace,
  SquareDashed,
  Tablet,
  TestTubes,
  Trash,
  Usb,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";

export type IconLibraryEntry = {
  name: string;
  label: string;
  group: "Core" | "Process" | "People" | "Data" | "Industry" | "Comms" | "Object";
  Icon: LucideIcon;
};

export const ICON_LIBRARY: IconLibraryEntry[] = [
  // Core
  { name: "Sparkles", label: "Sparkle", group: "Core", Icon: Sparkles },
  { name: "Target", label: "Target", group: "Core", Icon: Target },
  { name: "Rocket", label: "Rocket", group: "Core", Icon: Rocket },
  { name: "Lightbulb", label: "Idea", group: "Core", Icon: Lightbulb },
  { name: "Star", label: "Star", group: "Core", Icon: Star },
  { name: "Trophy", label: "Trophy", group: "Core", Icon: Trophy },
  { name: "Award", label: "Award", group: "Core", Icon: Award },
  { name: "Flag", label: "Flag", group: "Core", Icon: Flag },
  { name: "Zap", label: "Momentum", group: "Core", Icon: Zap },
  { name: "Heart", label: "Heart", group: "Core", Icon: Heart },
  { name: "CheckCircle2", label: "Approved", group: "Core", Icon: CheckCircle2 },
  { name: "ThumbsUp", label: "Thumbs up", group: "Core", Icon: ThumbsUp },
  { name: "AlertTriangle", label: "Risk", group: "Core", Icon: AlertTriangle },
  { name: "ShieldCheck", label: "Governance", group: "Core", Icon: ShieldCheck },
  { name: "Shield", label: "Shield", group: "Core", Icon: Shield },
  { name: "Lock", label: "Lock", group: "Core", Icon: Lock },
  { name: "Key", label: "Key", group: "Core", Icon: Key },
  { name: "Puzzle", label: "Puzzle piece", group: "Core", Icon: Puzzle },
  { name: "ArrowRight", label: "Arrow", group: "Core", Icon: ArrowRight },
  { name: "ArrowUpRight", label: "Growth arrow", group: "Core", Icon: ArrowUpRight },

  // Process
  { name: "Workflow", label: "Workflow", group: "Process", Icon: Workflow },
  { name: "Layers3", label: "Layered stack", group: "Process", Icon: Layers3 },
  { name: "Layers", label: "Layers", group: "Process", Icon: Layers },
  { name: "GitBranch", label: "Branch / integrate", group: "Process", Icon: GitBranch },
  { name: "ClipboardList", label: "Intake", group: "Process", Icon: ClipboardList },
  { name: "FileCheck2", label: "Review", group: "Process", Icon: FileCheck2 },
  { name: "Send", label: "Deliver", group: "Process", Icon: Send },
  { name: "Play", label: "Start", group: "Process", Icon: Play },
  { name: "Timer", label: "Time / speed", group: "Process", Icon: Timer },
  { name: "Calendar", label: "Calendar", group: "Process", Icon: Calendar },
  { name: "Cog", label: "Configure", group: "Process", Icon: Cog },
  { name: "Settings", label: "Settings", group: "Process", Icon: Settings },
  { name: "Wrench", label: "Wrench", group: "Process", Icon: Wrench },
  { name: "Hammer", label: "Build", group: "Process", Icon: Hammer },
  { name: "PenTool", label: "Design", group: "Process", Icon: PenTool },
  { name: "Search", label: "Discover", group: "Process", Icon: Search },
  { name: "TrendingUp", label: "Grow", group: "Process", Icon: TrendingUp },

  // People
  { name: "Users", label: "Team", group: "People", Icon: Users },
  { name: "Handshake", label: "Partnership", group: "People", Icon: Handshake },
  { name: "MessageSquareQuote", label: "Testimonial", group: "People", Icon: MessageSquareQuote },
  { name: "MessagesSquare", label: "Support", group: "People", Icon: MessagesSquare },
  { name: "MessageCircle", label: "Conversation", group: "People", Icon: MessageCircle },
  { name: "Mail", label: "Email", group: "People", Icon: Mail },
  { name: "Phone", label: "Phone", group: "People", Icon: Phone },
  { name: "Presentation", label: "Presentation", group: "People", Icon: Presentation },
  { name: "Book", label: "Learn", group: "People", Icon: Book },

  // Data
  { name: "LineChart", label: "Trend line", group: "Data", Icon: LineChart },
  { name: "BarChart3", label: "Bar chart", group: "Data", Icon: BarChart3 },
  { name: "PieChart", label: "Pie chart", group: "Data", Icon: PieChart },
  { name: "Gauge", label: "Gauge / KPI", group: "Data", Icon: Gauge },
  { name: "Database", label: "Database", group: "Data", Icon: Database },
  { name: "Table", label: "Table", group: "Data", Icon: Table },
  { name: "FileText", label: "Document", group: "Data", Icon: FileText },
  { name: "Server", label: "Server", group: "Data", Icon: Server },
  { name: "Cloud", label: "Cloud", group: "Data", Icon: Cloud },
  { name: "Code2", label: "Code", group: "Data", Icon: Code2 },
  { name: "Cpu", label: "Compute / AI", group: "Data", Icon: Cpu },
  { name: "LinkIcon", label: "Link", group: "Data", Icon: LinkIcon },

  // Industry
  { name: "Building2", label: "Enterprise", group: "Industry", Icon: Building2 },
  { name: "Landmark", label: "Finance", group: "Industry", Icon: Landmark },
  { name: "HeartPulse", label: "Life sciences", group: "Industry", Icon: HeartPulse },
  { name: "Store", label: "Retail", group: "Industry", Icon: Store },
  { name: "Factory", label: "Industrial", group: "Industry", Icon: Factory },
  { name: "Car", label: "Automotive", group: "Industry", Icon: Car },
  { name: "Plane", label: "Travel", group: "Industry", Icon: Plane },
  { name: "Truck", label: "Logistics", group: "Industry", Icon: Truck },
  { name: "Globe2", label: "Global", group: "Industry", Icon: Globe2 },
  { name: "Map", label: "Map", group: "Industry", Icon: Map },
  { name: "Scale", label: "Legal", group: "Industry", Icon: Scale },
  { name: "Briefcase", label: "Business", group: "Industry", Icon: Briefcase },
  { name: "Home", label: "Home", group: "Industry", Icon: Home },
  { name: "Video", label: "Video / media", group: "Industry", Icon: Video },

  // Object
  { name: "Coins", label: "Cost", group: "Object", Icon: Coins },
  { name: "Wallet", label: "Wallet", group: "Object", Icon: Wallet },
  { name: "Gift", label: "Gift", group: "Object", Icon: Gift },
  { name: "Package", label: "Package", group: "Object", Icon: Package },

  // Extended vocabulary — added so every division's approved set can reach 100
  // glyphs without leaving the curated, single-weight outline family.
  { name: "Activity", label: "Activity", group: "Data", Icon: Activity },
  { name: "Anchor", label: "Anchor", group: "Process", Icon: Anchor },
  { name: "Aperture", label: "Aperture", group: "Data", Icon: Aperture },
  { name: "Archive", label: "Archive", group: "Process", Icon: Archive },
  { name: "AtSign", label: "At Sign", group: "Comms", Icon: AtSign },
  { name: "Atom", label: "Atom", group: "Data", Icon: Atom },
  { name: "Axe", label: "Axe", group: "Industry", Icon: Axe },
  { name: "BadgeCheck", label: "Badge Check", group: "Industry", Icon: BadgeCheck },
  { name: "Ban", label: "Ban", group: "Industry", Icon: Ban },
  { name: "Banknote", label: "Banknote", group: "Industry", Icon: Banknote },
  { name: "Barcode", label: "Barcode", group: "Data", Icon: Barcode },
  { name: "Battery", label: "Battery", group: "Data", Icon: Battery },
  { name: "Beaker", label: "Beaker", group: "Industry", Icon: Beaker },
  { name: "Bell", label: "Bell", group: "Comms", Icon: Bell },
  { name: "Bike", label: "Bike", group: "Industry", Icon: Bike },
  { name: "Binary", label: "Binary", group: "Data", Icon: Binary },
  { name: "Blocks", label: "Blocks", group: "Process", Icon: Blocks },
  { name: "Bluetooth", label: "Bluetooth", group: "Data", Icon: Bluetooth },
  { name: "Bold", label: "Bold", group: "Process", Icon: Bold },
  { name: "Bookmark", label: "Bookmark", group: "Process", Icon: Bookmark },
  { name: "BookOpen", label: "Book Open", group: "Industry", Icon: BookOpen },
  { name: "Bot", label: "Bot", group: "Data", Icon: Bot },
  { name: "Box", label: "Box", group: "Industry", Icon: Box },
  { name: "Boxes", label: "Boxes", group: "Industry", Icon: Boxes },
  { name: "Braces", label: "Braces", group: "Data", Icon: Braces },
  { name: "Brain", label: "Brain", group: "Data", Icon: Brain },
  { name: "BriefcaseBusiness", label: "Briefcase Business", group: "Industry", Icon: BriefcaseBusiness },
  { name: "Brush", label: "Brush", group: "Process", Icon: Brush },
  { name: "Bug", label: "Bug", group: "Process", Icon: Bug },
  { name: "Building", label: "Building", group: "Industry", Icon: Building },
  { name: "Bus", label: "Bus", group: "Industry", Icon: Bus },
  { name: "Cable", label: "Cable", group: "Data", Icon: Cable },
  { name: "Calculator", label: "Calculator", group: "Data", Icon: Calculator },
  { name: "CalendarCheck", label: "Calendar Check", group: "Process", Icon: CalendarCheck },
  { name: "CalendarClock", label: "Calendar Clock", group: "Process", Icon: CalendarClock },
  { name: "Camera", label: "Camera", group: "Comms", Icon: Camera },
  { name: "CircleDollarSign", label: "Circle Dollar Sign", group: "Industry", Icon: CircleDollarSign },
  { name: "CircuitBoard", label: "Circuit Board", group: "Data", Icon: CircuitBoard },
  { name: "Clipboard", label: "Clipboard", group: "Process", Icon: Clipboard },
  { name: "ClipboardCheck", label: "Clipboard Check", group: "Process", Icon: ClipboardCheck },
  { name: "Clock", label: "Clock", group: "Process", Icon: Clock },
  { name: "CloudCog", label: "Cloud Cog", group: "Data", Icon: CloudCog },
  { name: "CloudUpload", label: "Cloud Upload", group: "Data", Icon: CloudUpload },
  { name: "Compass", label: "Compass", group: "Process", Icon: Compass },
  { name: "Component", label: "Component", group: "Data", Icon: Component },
  { name: "Container", label: "Container", group: "Industry", Icon: Container },
  { name: "Contact", label: "Contact", group: "People", Icon: Contact },
  { name: "Cookie", label: "Cookie", group: "Process", Icon: Cookie },
  { name: "Copy", label: "Copy", group: "Process", Icon: Copy },
  { name: "CreditCard", label: "Credit Card", group: "Industry", Icon: CreditCard },
  { name: "Crop", label: "Crop", group: "Process", Icon: Crop },
  { name: "Crosshair", label: "Crosshair", group: "Process", Icon: Crosshair },
  { name: "Crown", label: "Crown", group: "People", Icon: Crown },
  { name: "Cylinder", label: "Cylinder", group: "Process", Icon: Cylinder },
  { name: "Diamond", label: "Diamond", group: "Process", Icon: Diamond },
  { name: "Dna", label: "Dna", group: "Industry", Icon: Dna },
  { name: "Download", label: "Download", group: "Process", Icon: Download },
  { name: "Drama", label: "Drama", group: "People", Icon: Drama },
  { name: "Droplet", label: "Droplet", group: "Process", Icon: Droplet },
  { name: "Ear", label: "Ear", group: "Comms", Icon: Ear },
  { name: "Earth", label: "Earth", group: "Comms", Icon: Earth },
  { name: "Eye", label: "Eye", group: "Data", Icon: Eye },
  { name: "Feather", label: "Feather", group: "Industry", Icon: Feather },
  { name: "FileBadge", label: "File Badge", group: "Data", Icon: FileBadge },
  { name: "FileCode", label: "File Code", group: "Data", Icon: FileCode },
  { name: "FileSearch", label: "File Search", group: "Data", Icon: FileSearch },
  { name: "FileSpreadsheet", label: "File Spreadsheet", group: "Data", Icon: FileSpreadsheet },
  { name: "FileStack", label: "File Stack", group: "Data", Icon: FileStack },
  { name: "Files", label: "Files", group: "Data", Icon: Files },
  { name: "Film", label: "Film", group: "Comms", Icon: Film },
  { name: "Focus", label: "Focus", group: "Data", Icon: Focus },
  { name: "FolderOpen", label: "Folder Open", group: "Data", Icon: FolderOpen },
  { name: "Folders", label: "Folders", group: "Data", Icon: Folders },
  { name: "Footprints", label: "Footprints", group: "People", Icon: Footprints },
  { name: "Forklift", label: "Forklift", group: "Industry", Icon: Forklift },
  { name: "Frame", label: "Frame", group: "Process", Icon: Frame },
  { name: "Fuel", label: "Fuel", group: "Industry", Icon: Fuel },
  { name: "Funnel", label: "Funnel", group: "Process", Icon: Funnel },
  { name: "Gamepad2", label: "Gamepad", group: "Industry", Icon: Gamepad2 },
  { name: "Gavel", label: "Gavel", group: "Industry", Icon: Gavel },
  { name: "Gem", label: "Gem", group: "Process", Icon: Gem },
  { name: "Globe", label: "Globe", group: "Industry", Icon: Globe },
  { name: "GraduationCap", label: "Graduation Cap", group: "People", Icon: GraduationCap },
  { name: "Grid3x3", label: "Grid 3x 3", group: "Data", Icon: Grid3x3 },
  { name: "Group", label: "Group", group: "People", Icon: Group },
  { name: "Hand", label: "Hand", group: "People", Icon: Hand },
  { name: "HandCoins", label: "Hand Coins", group: "People", Icon: HandCoins },
  { name: "HardDrive", label: "Hard Drive", group: "Data", Icon: HardDrive },
  { name: "HardHat", label: "Hard Hat", group: "Industry", Icon: HardHat },
  { name: "Hash", label: "Hash", group: "Data", Icon: Hash },
  { name: "Headphones", label: "Headphones", group: "Comms", Icon: Headphones },
  { name: "Hexagon", label: "Hexagon", group: "Process", Icon: Hexagon },
  { name: "Highlighter", label: "Highlighter", group: "Process", Icon: Highlighter },
  { name: "History", label: "History", group: "Process", Icon: History },
  { name: "Hospital", label: "Hospital", group: "Industry", Icon: Hospital },
  { name: "Hourglass", label: "Hourglass", group: "Process", Icon: Hourglass },
  { name: "IdCard", label: "Id Card", group: "People", Icon: IdCard },
  { name: "Image", label: "Image", group: "Comms", Icon: Image },
  { name: "Images", label: "Images", group: "Comms", Icon: Images },
  { name: "Inbox", label: "Inbox", group: "Comms", Icon: Inbox },
  { name: "Infinity", label: "Infinity", group: "Data", Icon: Infinity },
  { name: "Info", label: "Info", group: "Industry", Icon: Info },
  { name: "Keyboard", label: "Keyboard", group: "Data", Icon: Keyboard },
  { name: "Lamp", label: "Lamp", group: "Industry", Icon: Lamp },
  { name: "Languages", label: "Languages", group: "Comms", Icon: Languages },
  { name: "Laptop", label: "Laptop", group: "Data", Icon: Laptop },
  { name: "LayoutDashboard", label: "Layout Dashboard", group: "Data", Icon: LayoutDashboard },
  { name: "LayoutGrid", label: "Layout Grid", group: "Data", Icon: LayoutGrid },
  { name: "Leaf", label: "Leaf", group: "Process", Icon: Leaf },
  { name: "Library", label: "Library", group: "Industry", Icon: Library },
  { name: "LifeBuoy", label: "Life Buoy", group: "Industry", Icon: LifeBuoy },
  { name: "Ligature", label: "Ligature", group: "Process", Icon: Ligature },
  { name: "ListChecks", label: "List Checks", group: "Process", Icon: ListChecks },
  { name: "ListOrdered", label: "List Ordered", group: "Process", Icon: ListOrdered },
  { name: "Loader", label: "Loader", group: "Data", Icon: Loader },
  { name: "Locate", label: "Locate", group: "Process", Icon: Locate },
  { name: "MapPin", label: "Map Pin", group: "Process", Icon: MapPin },
  { name: "Maximize", label: "Maximize", group: "Process", Icon: Maximize },
  { name: "Medal", label: "Medal", group: "People", Icon: Medal },
  { name: "Megaphone", label: "Megaphone", group: "Comms", Icon: Megaphone },
  { name: "Menu", label: "Menu", group: "Process", Icon: Menu },
  { name: "Merge", label: "Merge", group: "Process", Icon: Merge },
  { name: "Mic", label: "Mic", group: "Comms", Icon: Mic },
  { name: "Microscope", label: "Microscope", group: "Comms", Icon: Microscope },
  { name: "Milestone", label: "Milestone", group: "Process", Icon: Milestone },
  { name: "Minimize", label: "Minimize", group: "Process", Icon: Minimize },
  { name: "Monitor", label: "Monitor", group: "Data", Icon: Monitor },
  { name: "Moon", label: "Moon", group: "Process", Icon: Moon },
  { name: "MousePointer", label: "Mouse Pointer", group: "Process", Icon: MousePointer },
  { name: "Move", label: "Move", group: "Process", Icon: Move },
  { name: "Music", label: "Music", group: "Comms", Icon: Music },
  { name: "Navigation", label: "Navigation", group: "Process", Icon: Navigation },
  { name: "Network", label: "Network", group: "Data", Icon: Network },
  { name: "Newspaper", label: "Newspaper", group: "Comms", Icon: Newspaper },
  { name: "Notebook", label: "Notebook", group: "Industry", Icon: Notebook },
  { name: "NotebookPen", label: "Notebook Pen", group: "Process", Icon: NotebookPen },
  { name: "Orbit", label: "Orbit", group: "Data", Icon: Orbit },
  { name: "Palette", label: "Palette", group: "Process", Icon: Palette },
  { name: "Paperclip", label: "Paperclip", group: "Process", Icon: Paperclip },
  { name: "PartyPopper", label: "Party Popper", group: "Process", Icon: PartyPopper },
  { name: "Pause", label: "Pause", group: "Process", Icon: Pause },
  { name: "PenLine", label: "Pen Line", group: "Process", Icon: PenLine },
  { name: "Percent", label: "Percent", group: "Data", Icon: Percent },
  { name: "PersonStanding", label: "Person Standing", group: "People", Icon: PersonStanding },
  { name: "Pill", label: "Pill", group: "Industry", Icon: Pill },
  { name: "Pin", label: "Pin", group: "Process", Icon: Pin },
  { name: "Pipette", label: "Pipette", group: "Process", Icon: Pipette },
  { name: "Plug", label: "Plug", group: "Data", Icon: Plug },
  { name: "Podcast", label: "Podcast", group: "Comms", Icon: Podcast },
  { name: "Pointer", label: "Pointer", group: "Process", Icon: Pointer },
  { name: "Power", label: "Power", group: "Data", Icon: Power },
  { name: "Printer", label: "Printer", group: "Data", Icon: Printer },
  { name: "QrCode", label: "Qr Code", group: "Data", Icon: QrCode },
  { name: "Quote", label: "Quote", group: "Comms", Icon: Quote },
  { name: "Radar", label: "Radar", group: "Data", Icon: Radar },
  { name: "Radio", label: "Radio", group: "Comms", Icon: Radio },
  { name: "Receipt", label: "Receipt", group: "Industry", Icon: Receipt },
  { name: "Recycle", label: "Recycle", group: "Process", Icon: Recycle },
  { name: "Redo2", label: "Redo", group: "Process", Icon: Redo2 },
  { name: "RefreshCw", label: "Refresh Cw", group: "Process", Icon: RefreshCw },
  { name: "Regex", label: "Regex", group: "Data", Icon: Regex },
  { name: "Repeat", label: "Repeat", group: "Process", Icon: Repeat },
  { name: "Replace", label: "Replace", group: "Process", Icon: Replace },
  { name: "Reply", label: "Reply", group: "Comms", Icon: Reply },
  { name: "Rewind", label: "Rewind", group: "Process", Icon: Rewind },
  { name: "Route", label: "Route", group: "Process", Icon: Route },
  { name: "Rss", label: "Rss", group: "Comms", Icon: Rss },
  { name: "Ruler", label: "Ruler", group: "Process", Icon: Ruler },
  { name: "Satellite", label: "Satellite", group: "Data", Icon: Satellite },
  { name: "Save", label: "Save", group: "Process", Icon: Save },
  { name: "Scan", label: "Scan", group: "Data", Icon: Scan },
  { name: "ScanLine", label: "Scan Line", group: "Data", Icon: ScanLine },
  { name: "School", label: "School", group: "People", Icon: School },
  { name: "Scissors", label: "Scissors", group: "Process", Icon: Scissors },
  { name: "ScreenShare", label: "Screen Share", group: "Comms", Icon: ScreenShare },
  { name: "Scroll", label: "Scroll", group: "Industry", Icon: Scroll },
  { name: "ShoppingBag", label: "Shopping Bag", group: "Industry", Icon: ShoppingBag },
  { name: "ShoppingCart", label: "Shopping Cart", group: "Industry", Icon: ShoppingCart },
  { name: "Shuffle", label: "Shuffle", group: "Process", Icon: Shuffle },
  { name: "Sigma", label: "Sigma", group: "Data", Icon: Sigma },
  { name: "Signal", label: "Signal", group: "Data", Icon: Signal },
  { name: "Siren", label: "Siren", group: "Industry", Icon: Siren },
  { name: "SlidersHorizontal", label: "Sliders Horizontal", group: "Process", Icon: SlidersHorizontal },
  { name: "Smartphone", label: "Smartphone", group: "Data", Icon: Smartphone },
  { name: "Smile", label: "Smile", group: "People", Icon: Smile },
  { name: "Snowflake", label: "Snowflake", group: "Process", Icon: Snowflake },
  { name: "Sparkle", label: "Sparkle", group: "Process", Icon: Sparkle },
  { name: "Speaker", label: "Speaker", group: "Comms", Icon: Speaker },
  { name: "Spline", label: "Spline", group: "Data", Icon: Spline },
  { name: "Split", label: "Split", group: "Process", Icon: Split },
  { name: "Square", label: "Square", group: "Process", Icon: Square },
  { name: "SquareStack", label: "Square Stack", group: "Process", Icon: SquareStack },
  { name: "Stamp", label: "Stamp", group: "Process", Icon: Stamp },
  { name: "Stethoscope", label: "Stethoscope", group: "Industry", Icon: Stethoscope },
  { name: "Sticker", label: "Sticker", group: "Process", Icon: Sticker },
  { name: "StickyNote", label: "Sticky Note", group: "Process", Icon: StickyNote },
  { name: "Sun", label: "Sun", group: "Process", Icon: Sun },
  { name: "Sunrise", label: "Sunrise", group: "Process", Icon: Sunrise },
  { name: "Syringe", label: "Syringe", group: "Industry", Icon: Syringe },
  { name: "Tag", label: "Tag", group: "Process", Icon: Tag },
  { name: "Tags", label: "Tags", group: "Process", Icon: Tags },
  { name: "Telescope", label: "Telescope", group: "Data", Icon: Telescope },
  { name: "Tent", label: "Tent", group: "Industry", Icon: Tent },
  { name: "Terminal", label: "Terminal", group: "Data", Icon: Terminal },
  { name: "TestTube", label: "Test Tube", group: "Industry", Icon: TestTube },
  { name: "TextCursor", label: "Text Cursor", group: "Process", Icon: TextCursor },
  { name: "Thermometer", label: "Thermometer", group: "Process", Icon: Thermometer },
  { name: "Ticket", label: "Ticket", group: "Comms", Icon: Ticket },
  { name: "Trash2", label: "Trash", group: "Industry", Icon: Trash2 },
  { name: "TreePine", label: "Tree Pine", group: "Process", Icon: TreePine },
  { name: "TrendingDown", label: "Trending Down", group: "Data", Icon: TrendingDown },
  { name: "Triangle", label: "Triangle", group: "Process", Icon: Triangle },
  { name: "Type", label: "Type", group: "Process", Icon: Type },
  { name: "Umbrella", label: "Umbrella", group: "Process", Icon: Umbrella },
  { name: "Undo2", label: "Undo", group: "Process", Icon: Undo2 },
  { name: "Unlink", label: "Unlink", group: "Process", Icon: Unlink },
  { name: "Upload", label: "Upload", group: "Process", Icon: Upload },
  { name: "UserCheck", label: "User Check", group: "People", Icon: UserCheck },
  { name: "UserCog", label: "User Cog", group: "People", Icon: UserCog },
  { name: "UserPlus", label: "User Plus", group: "People", Icon: UserPlus },
  { name: "Utensils", label: "Utensils", group: "Industry", Icon: Utensils },
  { name: "Variable", label: "Variable", group: "Data", Icon: Variable },
  { name: "Vault", label: "Vault", group: "Industry", Icon: Vault },
  { name: "Vibrate", label: "Vibrate", group: "Comms", Icon: Vibrate },
  { name: "View", label: "View", group: "Data", Icon: View },
  { name: "Voicemail", label: "Voicemail", group: "Comms", Icon: Voicemail },
  { name: "Volume2", label: "Volume", group: "Comms", Icon: Volume2 },
  { name: "Warehouse", label: "Warehouse", group: "Industry", Icon: Warehouse },
  { name: "Watch", label: "Watch", group: "Industry", Icon: Watch },
  { name: "Waves", label: "Waves", group: "Process", Icon: Waves },
  { name: "Webhook", label: "Webhook", group: "Data", Icon: Webhook },
  { name: "Wifi", label: "Wifi", group: "Data", Icon: Wifi },
  { name: "Wind", label: "Wind", group: "Process", Icon: Wind },
  { name: "ZoomIn", label: "Zoom In", group: "Data", Icon: ZoomIn },

  // Extended — Core
  { name: "Ampersand", label: "Ampersand", group: "Core", Icon: Ampersand },
  { name: "Asterisk", label: "Asterisk", group: "Core", Icon: Asterisk },
  { name: "Badge", label: "Badge", group: "Core", Icon: Badge },
  { name: "BadgeAlert", label: "Badge Alert", group: "Core", Icon: BadgeAlert },
  { name: "BellRing", label: "Bell Ring", group: "Core", Icon: BellRing },
  { name: "BookmarkCheck", label: "Bookmark Check", group: "Core", Icon: BookmarkCheck },
  { name: "Circle", label: "Circle", group: "Core", Icon: Circle },
  { name: "CircleCheck", label: "Circle Check", group: "Core", Icon: CircleCheck },
  { name: "CircleDot", label: "Circle Dot", group: "Core", Icon: CircleDot },
  { name: "CircleHelp", label: "Circle Help", group: "Core", Icon: CircleHelp },
  { name: "Clover", label: "Clover", group: "Core", Icon: Clover },
  { name: "Dot", label: "Dot", group: "Core", Icon: Dot },
  { name: "Egg", label: "Egg", group: "Core", Icon: Egg },
  { name: "Flame", label: "Flame", group: "Core", Icon: Flame },
  { name: "Flower", label: "Flower", group: "Core", Icon: Flower },
  { name: "Flower2", label: "Flower", group: "Core", Icon: Flower2 },
  { name: "Goal", label: "Goal", group: "Core", Icon: Goal },
  { name: "Octagon", label: "Octagon", group: "Core", Icon: Octagon },
  { name: "Pentagon", label: "Pentagon", group: "Core", Icon: Pentagon },
  { name: "Rainbow", label: "Rainbow", group: "Core", Icon: Rainbow },
  { name: "Ribbon", label: "Ribbon", group: "Core", Icon: Ribbon },
  { name: "Shapes", label: "Shapes", group: "Core", Icon: Shapes },
  { name: "ShieldAlert", label: "Shield Alert", group: "Core", Icon: ShieldAlert },
  { name: "ShieldPlus", label: "Shield Plus", group: "Core", Icon: ShieldPlus },
  { name: "Signature", label: "Signature", group: "Core", Icon: Signature },
  { name: "Snail", label: "Snail", group: "Core", Icon: Snail },
  { name: "Squircle", label: "Squircle", group: "Core", Icon: Squircle },
  { name: "Sunset", label: "Sunset", group: "Core", Icon: Sunset },
  { name: "ThumbsDown", label: "Thumbs Down", group: "Core", Icon: ThumbsDown },
  { name: "Torus", label: "Torus", group: "Core", Icon: Torus },
  { name: "Verified", label: "Verified", group: "Core", Icon: Verified },
  { name: "Waypoints", label: "Waypoints", group: "Core", Icon: Waypoints },
  { name: "Wand", label: "Wand", group: "Core", Icon: Wand },
  { name: "Wand2", label: "Wand", group: "Core", Icon: Wand2 },
  { name: "Wheat", label: "Wheat", group: "Core", Icon: Wheat },
  { name: "ZapOff", label: "Zap Off", group: "Core", Icon: ZapOff },

  // Extended — Process
  { name: "AlarmClock", label: "Alarm Clock", group: "Process", Icon: AlarmClock },
  { name: "ArrowDownUp", label: "Arrow Down Up", group: "Process", Icon: ArrowDownUp },
  { name: "ArrowLeftRight", label: "Arrow Left Right", group: "Process", Icon: ArrowLeftRight },
  { name: "ArrowUpDown", label: "Arrow Up Down", group: "Process", Icon: ArrowUpDown },
  { name: "Blend", label: "Blend", group: "Process", Icon: Blend },
  { name: "CalendarRange", label: "Calendar Range", group: "Process", Icon: CalendarRange },
  { name: "CalendarSync", label: "Calendar Sync", group: "Process", Icon: CalendarSync },
  { name: "ChartGantt", label: "Chart Gantt", group: "Process", Icon: ChartGantt },
  { name: "CheckCheck", label: "Check Check", group: "Process", Icon: CheckCheck },
  { name: "ChevronsRight", label: "Chevrons Right", group: "Process", Icon: ChevronsRight },
  { name: "CircleArrowRight", label: "Circle Arrow Right", group: "Process", Icon: CircleArrowRight },
  { name: "ClipboardPen", label: "Clipboard Pen", group: "Process", Icon: ClipboardPen },
  { name: "Combine", label: "Combine", group: "Process", Icon: Combine },
  { name: "ConciergeBell", label: "Concierge Bell", group: "Process", Icon: ConciergeBell },
  { name: "Construction", label: "Construction", group: "Process", Icon: Construction },
  { name: "Drill", label: "Drill", group: "Process", Icon: Drill },
  { name: "FastForward", label: "Fast Forward", group: "Process", Icon: FastForward },
  { name: "Filter", label: "Filter", group: "Process", Icon: Filter },
  { name: "Fingerprint", label: "Fingerprint", group: "Process", Icon: Fingerprint },
  { name: "FlaskConical", label: "Flask Conical", group: "Process", Icon: FlaskConical },
  { name: "FolderSync", label: "Folder Sync", group: "Process", Icon: FolderSync },
  { name: "Forward", label: "Forward", group: "Process", Icon: Forward },
  { name: "Grid2x2", label: "Grid2x", group: "Process", Icon: Grid2x2 },
  { name: "IterationCcw", label: "Iteration Ccw", group: "Process", Icon: IterationCcw },
  { name: "Kanban", label: "Kanban", group: "Process", Icon: Kanban },
  { name: "ListTodo", label: "List Todo", group: "Process", Icon: ListTodo },
  { name: "Loader2", label: "Loader", group: "Process", Icon: Loader2 },
  { name: "LockOpen", label: "Lock Open", group: "Process", Icon: LockOpen },
  { name: "Logs", label: "Logs", group: "Process", Icon: Logs },
  { name: "Magnet", label: "Magnet", group: "Process", Icon: Magnet },
  { name: "MoveRight", label: "Move Right", group: "Process", Icon: MoveRight },
  { name: "PackageCheck", label: "Package Check", group: "Process", Icon: PackageCheck },
  { name: "PackageOpen", label: "Package Open", group: "Process", Icon: PackageOpen },
  { name: "Paintbrush", label: "Paintbrush", group: "Process", Icon: Paintbrush },
  { name: "PanelsTopLeft", label: "Panels Top Left", group: "Process", Icon: PanelsTopLeft },
  { name: "Pencil", label: "Pencil", group: "Process", Icon: Pencil },
  { name: "PencilRuler", label: "Pencil Ruler", group: "Process", Icon: PencilRuler },
  { name: "PlayCircle", label: "Play Circle", group: "Process", Icon: PlayCircle },
  { name: "Plus", label: "Plus", group: "Process", Icon: Plus },
  { name: "Repeat2", label: "Repeat", group: "Process", Icon: Repeat2 },
  { name: "ReplaceAll", label: "Replace All", group: "Process", Icon: ReplaceAll },
  { name: "RotateCcw", label: "Rotate Ccw", group: "Process", Icon: RotateCcw },
  { name: "RotateCw", label: "Rotate Cw", group: "Process", Icon: RotateCw },
  { name: "ScrollText", label: "Scroll Text", group: "Process", Icon: ScrollText },
  { name: "SendHorizontal", label: "Send Horizontal", group: "Process", Icon: SendHorizontal },
  { name: "SkipForward", label: "Skip Forward", group: "Process", Icon: SkipForward },
  { name: "SquareCheck", label: "Square Check", group: "Process", Icon: SquareCheck },
  { name: "SquarePen", label: "Square Pen", group: "Process", Icon: SquarePen },
  { name: "StepForward", label: "Step Forward", group: "Process", Icon: StepForward },
  { name: "TicketCheck", label: "Ticket Check", group: "Process", Icon: TicketCheck },
  { name: "TimerReset", label: "Timer Reset", group: "Process", Icon: TimerReset },
  { name: "ToggleRight", label: "Toggle Right", group: "Process", Icon: ToggleRight },

  // Extended — People
  { name: "Accessibility", label: "Accessibility", group: "People", Icon: Accessibility },
  { name: "Baby", label: "Baby", group: "People", Icon: Baby },
  { name: "Backpack", label: "Backpack", group: "People", Icon: Backpack },
  { name: "BookUser", label: "Book User", group: "People", Icon: BookUser },
  { name: "Cake", label: "Cake", group: "People", Icon: Cake },
  { name: "Church", label: "Church", group: "People", Icon: Church },
  { name: "ContactRound", label: "Contact Round", group: "People", Icon: ContactRound },
  { name: "Frown", label: "Frown", group: "People", Icon: Frown },
  { name: "Glasses", label: "Glasses", group: "People", Icon: Glasses },
  { name: "HandHeart", label: "Hand Heart", group: "People", Icon: HandHeart },
  { name: "HandHelping", label: "Hand Helping", group: "People", Icon: HandHelping },
  { name: "HandMetal", label: "Hand Metal", group: "People", Icon: HandMetal },
  { name: "HeartHandshake", label: "Heart Handshake", group: "People", Icon: HeartHandshake },
  { name: "Laugh", label: "Laugh", group: "People", Icon: Laugh },
  { name: "MailOpen", label: "Mail Open", group: "People", Icon: MailOpen },
  { name: "Meh", label: "Meh", group: "People", Icon: Meh },
  { name: "MessageCircleHeart", label: "Message Circle Heart", group: "People", Icon: MessageCircleHeart },
  { name: "MessageSquareHeart", label: "Message Square Heart", group: "People", Icon: MessageSquareHeart },
  { name: "MessageSquareText", label: "Message Square Text", group: "People", Icon: MessageSquareText },
  { name: "Mic2", label: "Mic", group: "People", Icon: Mic2 },
  { name: "PhoneCall", label: "Phone Call", group: "People", Icon: PhoneCall },
  { name: "Speech", label: "Speech", group: "People", Icon: Speech },
  { name: "UserCircle", label: "User Circle", group: "People", Icon: UserCircle },
  { name: "UserMinus", label: "User Minus", group: "People", Icon: UserMinus },
  { name: "UserPen", label: "User Pen", group: "People", Icon: UserPen },
  { name: "UserRound", label: "User Round", group: "People", Icon: UserRound },
  { name: "UserRoundCheck", label: "User Round Check", group: "People", Icon: UserRoundCheck },
  { name: "UserSearch", label: "User Search", group: "People", Icon: UserSearch },
  { name: "UserStar", label: "User Star", group: "People", Icon: UserStar },
  { name: "UserX", label: "User X", group: "People", Icon: UserX },
  { name: "Users2", label: "Users", group: "People", Icon: Users2 },
  { name: "UsersRound", label: "Users Round", group: "People", Icon: UsersRound },
  { name: "Vote", label: "Vote", group: "People", Icon: Vote },

  // Extended — Data
  { name: "Antenna", label: "Antenna", group: "Data", Icon: Antenna },
  { name: "AreaChart", label: "Area Chart", group: "Data", Icon: AreaChart },
  { name: "Bolt", label: "Bolt", group: "Data", Icon: Bolt },
  { name: "BookOpenCheck", label: "Book Open Check", group: "Data", Icon: BookOpenCheck },
  { name: "Brackets", label: "Brackets", group: "Data", Icon: Brackets },
  { name: "ChartArea", label: "Chart Area", group: "Data", Icon: ChartArea },
  { name: "ChartBar", label: "Chart Bar", group: "Data", Icon: ChartBar },
  { name: "ChartBarBig", label: "Chart Bar Big", group: "Data", Icon: ChartBarBig },
  { name: "ChartColumn", label: "Chart Column", group: "Data", Icon: ChartColumn },
  { name: "ChartLine", label: "Chart Line", group: "Data", Icon: ChartLine },
  { name: "ChartNetwork", label: "Chart Network", group: "Data", Icon: ChartNetwork },
  { name: "ChartNoAxesColumn", label: "Chart No Axes Column", group: "Data", Icon: ChartNoAxesColumn },
  { name: "ChartPie", label: "Chart Pie", group: "Data", Icon: ChartPie },
  { name: "ChartScatter", label: "Chart Scatter", group: "Data", Icon: ChartScatter },
  { name: "ChartSpline", label: "Chart Spline", group: "Data", Icon: ChartSpline },
  { name: "CloudDownload", label: "Cloud Download", group: "Data", Icon: CloudDownload },
  { name: "Columns3", label: "Columns", group: "Data", Icon: Columns3 },
  { name: "DatabaseBackup", label: "Database Backup", group: "Data", Icon: DatabaseBackup },
  { name: "DatabaseZap", label: "Database Zap", group: "Data", Icon: DatabaseZap },
  { name: "DollarSign", label: "Dollar Sign", group: "Data", Icon: DollarSign },
  { name: "FileBarChart", label: "File Bar Chart", group: "Data", Icon: FileBarChart },
  { name: "FileDigit", label: "File Digit", group: "Data", Icon: FileDigit },
  { name: "FileJson", label: "File Json", group: "Data", Icon: FileJson },
  { name: "FolderTree", label: "Folder Tree", group: "Data", Icon: FolderTree },
  { name: "GitCommitHorizontal", label: "Git Commit Horizontal", group: "Data", Icon: GitCommitHorizontal },
  { name: "GitCompare", label: "Git Compare", group: "Data", Icon: GitCompare },
  { name: "GitFork", label: "Git Fork", group: "Data", Icon: GitFork },
  { name: "GitMerge", label: "Git Merge", group: "Data", Icon: GitMerge },
  { name: "GitPullRequest", label: "Git Pull Request", group: "Data", Icon: GitPullRequest },
  { name: "Layers2", label: "Layers", group: "Data", Icon: Layers2 },
  { name: "MemoryStick", label: "Memory Stick", group: "Data", Icon: MemoryStick },
  { name: "MonitorDot", label: "Monitor Dot", group: "Data", Icon: MonitorDot },
  { name: "Radius", label: "Radius", group: "Data", Icon: Radius },
  { name: "Rows3", label: "Rows", group: "Data", Icon: Rows3 },
  { name: "SatelliteDish", label: "Satellite Dish", group: "Data", Icon: SatelliteDish },
  { name: "ServerCog", label: "Server Cog", group: "Data", Icon: ServerCog },
  { name: "Sheet", label: "Sheet", group: "Data", Icon: Sheet },
  { name: "SignalHigh", label: "Signal High", group: "Data", Icon: SignalHigh },
  { name: "SquareFunction", label: "Square Function", group: "Data", Icon: SquareFunction },
  { name: "Table2", label: "Table", group: "Data", Icon: Table2 },
  { name: "TabletSmartphone", label: "Tablet Smartphone", group: "Data", Icon: TabletSmartphone },
  { name: "TerminalSquare", label: "Terminal Square", group: "Data", Icon: TerminalSquare },
  { name: "TicketPercent", label: "Ticket Percent", group: "Data", Icon: TicketPercent },
  { name: "Weight", label: "Weight", group: "Data", Icon: Weight },

  // Extended — Industry
  { name: "Anvil", label: "Anvil", group: "Industry", Icon: Anvil },
  { name: "Apple", label: "Apple", group: "Industry", Icon: Apple },
  { name: "Armchair", label: "Armchair", group: "Industry", Icon: Armchair },
  { name: "Beef", label: "Beef", group: "Industry", Icon: Beef },
  { name: "Bitcoin", label: "Bitcoin", group: "Industry", Icon: Bitcoin },
  { name: "Bone", label: "Bone", group: "Industry", Icon: Bone },
  { name: "BookMarked", label: "Book Marked", group: "Industry", Icon: BookMarked },
  { name: "BriefcaseMedical", label: "Briefcase Medical", group: "Industry", Icon: BriefcaseMedical },
  { name: "Cannabis", label: "Cannabis", group: "Industry", Icon: Cannabis },
  { name: "CarFront", label: "Car Front", group: "Industry", Icon: CarFront },
  { name: "Caravan", label: "Caravan", group: "Industry", Icon: Caravan },
  { name: "Clapperboard", label: "Clapperboard", group: "Industry", Icon: Clapperboard },
  { name: "Cross", label: "Cross", group: "Industry", Icon: Cross },
  { name: "Dam", label: "Dam", group: "Industry", Icon: Dam },
  { name: "Drum", label: "Drum", group: "Industry", Icon: Drum },
  { name: "Dumbbell", label: "Dumbbell", group: "Industry", Icon: Dumbbell },
  { name: "Fence", label: "Fence", group: "Industry", Icon: Fence },
  { name: "Fish", label: "Fish", group: "Industry", Icon: Fish },
  { name: "Flashlight", label: "Flashlight", group: "Industry", Icon: Flashlight },
  { name: "FlaskRound", label: "Flask Round", group: "Industry", Icon: FlaskRound },
  { name: "Grape", label: "Grape", group: "Industry", Icon: Grape },
  { name: "Handbag", label: "Handbag", group: "Industry", Icon: Handbag },
  { name: "Haze", label: "Haze", group: "Industry", Icon: Haze },
  { name: "Hotel", label: "Hotel", group: "Industry", Icon: Hotel },
  { name: "House", label: "House", group: "Industry", Icon: House },
  { name: "LandPlot", label: "Land Plot", group: "Industry", Icon: LandPlot },
  { name: "MapPinned", label: "Map Pinned", group: "Industry", Icon: MapPinned },
  { name: "Milk", label: "Milk", group: "Industry", Icon: Milk },
  { name: "Mountain", label: "Mountain", group: "Industry", Icon: Mountain },
  { name: "MountainSnow", label: "Mountain Snow", group: "Industry", Icon: MountainSnow },
  { name: "Nut", label: "Nut", group: "Industry", Icon: Nut },
  { name: "Palmtree", label: "Palmtree", group: "Industry", Icon: Palmtree },
  { name: "Pickaxe", label: "Pickaxe", group: "Industry", Icon: Pickaxe },
  { name: "PillBottle", label: "Pill Bottle", group: "Industry", Icon: PillBottle },
  { name: "PlaneTakeoff", label: "Plane Takeoff", group: "Industry", Icon: PlaneTakeoff },
  { name: "Popcorn", label: "Popcorn", group: "Industry", Icon: Popcorn },
  { name: "Projector", label: "Projector", group: "Industry", Icon: Projector },
  { name: "Radiation", label: "Radiation", group: "Industry", Icon: Radiation },
  { name: "Sailboat", label: "Sailboat", group: "Industry", Icon: Sailboat },
  { name: "Shirt", label: "Shirt", group: "Industry", Icon: Shirt },
  { name: "ShoppingBasket", label: "Shopping Basket", group: "Industry", Icon: ShoppingBasket },
  { name: "Shovel", label: "Shovel", group: "Industry", Icon: Shovel },
  { name: "Signpost", label: "Signpost", group: "Industry", Icon: Signpost },
  { name: "Ship", label: "Ship", group: "Industry", Icon: Ship },
  { name: "Sprout", label: "Sprout", group: "Industry", Icon: Sprout },
  { name: "Theater", label: "Theater", group: "Industry", Icon: Theater },
  { name: "Tractor", label: "Tractor", group: "Industry", Icon: Tractor },
  { name: "TrainFront", label: "Train Front", group: "Industry", Icon: TrainFront },
  { name: "TreePalm", label: "Tree Palm", group: "Industry", Icon: TreePalm },
  { name: "Tv", label: "Tv", group: "Industry", Icon: Tv },
  { name: "Wine", label: "Wine", group: "Industry", Icon: Wine },

  // Extended — Comms
  { name: "AudioLines", label: "Audio Lines", group: "Comms", Icon: AudioLines },
  { name: "BrainCircuit", label: "Brain Circuit", group: "Comms", Icon: BrainCircuit },
  { name: "Cast", label: "Cast", group: "Comms", Icon: Cast },
  { name: "ClosedCaption", label: "Closed Caption", group: "Comms", Icon: ClosedCaption },
  { name: "Cloudy", label: "Cloudy", group: "Comms", Icon: Cloudy },
  { name: "FileAudio", label: "File Audio", group: "Comms", Icon: FileAudio },
  { name: "FileVideo", label: "File Video", group: "Comms", Icon: FileVideo },
  { name: "Instagram", label: "Instagram", group: "Comms", Icon: Instagram },
  { name: "Italic", label: "Italic", group: "Comms", Icon: Italic },
  { name: "Link2", label: "Link", group: "Comms", Icon: Link2 },
  { name: "Linkedin", label: "Linkedin", group: "Comms", Icon: Linkedin },
  { name: "Mails", label: "Mails", group: "Comms", Icon: Mails },
  { name: "MessageCircleMore", label: "Message Circle More", group: "Comms", Icon: MessageCircleMore },
  { name: "MessageSquare", label: "Message Square", group: "Comms", Icon: MessageSquare },
  { name: "MessageSquareDashed", label: "Message Square Dashed", group: "Comms", Icon: MessageSquareDashed },
  { name: "MicVocal", label: "Mic Vocal", group: "Comms", Icon: MicVocal },
  { name: "MonitorPlay", label: "Monitor Play", group: "Comms", Icon: MonitorPlay },
  { name: "Music2", label: "Music", group: "Comms", Icon: Music2 },
  { name: "PhoneOutgoing", label: "Phone Outgoing", group: "Comms", Icon: PhoneOutgoing },
  { name: "ReplyAll", label: "Reply All", group: "Comms", Icon: ReplyAll },
  { name: "Share2", label: "Share", group: "Comms", Icon: Share2 },
  { name: "Subtitles", label: "Subtitles", group: "Comms", Icon: Subtitles },
  { name: "Text", label: "Text", group: "Comms", Icon: Text },
  { name: "TextQuote", label: "Text Quote", group: "Comms", Icon: TextQuote },
  { name: "Twitter", label: "Twitter", group: "Comms", Icon: Twitter },
  { name: "Underline", label: "Underline", group: "Comms", Icon: Underline },
  { name: "Videotape", label: "Videotape", group: "Comms", Icon: Videotape },
  { name: "Youtube", label: "Youtube", group: "Comms", Icon: Youtube },

  // Extended — Object
  { name: "Album", label: "Album", group: "Object", Icon: Album },
  { name: "ArchiveRestore", label: "Archive Restore", group: "Object", Icon: ArchiveRestore },
  { name: "Bed", label: "Bed", group: "Object", Icon: Bed },
  { name: "Binoculars", label: "Binoculars", group: "Object", Icon: Binoculars },
  { name: "BookCopy", label: "Book Copy", group: "Object", Icon: BookCopy },
  { name: "Coffee", label: "Coffee", group: "Object", Icon: Coffee },
  { name: "Diameter", label: "Diameter", group: "Object", Icon: Diameter },
  { name: "Disc", label: "Disc", group: "Object", Icon: Disc },
  { name: "Disc3", label: "Disc", group: "Object", Icon: Disc3 },
  { name: "Eraser", label: "Eraser", group: "Object", Icon: Eraser },
  { name: "ExternalLink", label: "External Link", group: "Object", Icon: ExternalLink },
  { name: "File", label: "File", group: "Object", Icon: File },
  { name: "FileCheck", label: "File Check", group: "Object", Icon: FileCheck },
  { name: "FileHeart", label: "File Heart", group: "Object", Icon: FileHeart },
  { name: "FileLock", label: "File Lock", group: "Object", Icon: FileLock },
  { name: "FilePen", label: "File Pen", group: "Object", Icon: FilePen },
  { name: "FilePlus", label: "File Plus", group: "Object", Icon: FilePlus },
  { name: "FileType", label: "File Type", group: "Object", Icon: FileType },
  { name: "FlagTriangleRight", label: "Flag Triangle Right", group: "Object", Icon: FlagTriangleRight },
  { name: "Grid2x2Check", label: "Grid2x2 Check", group: "Object", Icon: Grid2x2Check },
  { name: "KeyRound", label: "Key Round", group: "Object", Icon: KeyRound },
  { name: "LampDesk", label: "Lamp Desk", group: "Object", Icon: LampDesk },
  { name: "Luggage", label: "Luggage", group: "Object", Icon: Luggage },
  { name: "Mailbox", label: "Mailbox", group: "Object", Icon: Mailbox },
  { name: "Mouse", label: "Mouse", group: "Object", Icon: Mouse },
  { name: "Ratio", label: "Ratio", group: "Object", Icon: Ratio },
  { name: "ScanFace", label: "Scan Face", group: "Object", Icon: ScanFace },
  { name: "SquareDashed", label: "Square Dashed", group: "Object", Icon: SquareDashed },
  { name: "Tablet", label: "Tablet", group: "Object", Icon: Tablet },
  { name: "TestTubes", label: "Test Tubes", group: "Object", Icon: TestTubes },
  { name: "Trash", label: "Trash", group: "Object", Icon: Trash },
  { name: "Usb", label: "Usb", group: "Object", Icon: Usb },
  { name: "ZoomOut", label: "Zoom Out", group: "Object", Icon: ZoomOut },
];

const BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  ICON_LIBRARY.map((e) => [e.name, e.Icon]),
);

export function iconByName(name: string | undefined | null): LucideIcon | null {
  if (!name) return null;
  return BY_NAME[name] ?? null;
}

/**
 * Parse a `pack:name` icon reference (e.g. "lucide:home", "ph:rocket").
 * Returns null for plain curated names — those go through `iconByName`.
 */
export function parseIconRef(
  ref: string | undefined | null,
): { packId: string; name: string } | null {
  if (!ref) return null;
  const idx = ref.indexOf(":");
  if (idx <= 0 || idx === ref.length - 1) return null;
  return { packId: ref.slice(0, idx), name: ref.slice(idx + 1) };
}

export const ICON_GROUPS: Array<IconLibraryEntry["group"]> = [
  "Core",
  "Process",
  "People",
  "Data",
  "Industry",
  "Comms",
  "Object",
];
