// Curated icon library exposed to the deck editor so users can pick an icon
// per item/slide, overriding the label-based auto-match in VariantRenderer.

import {
  Sparkles,
  Workflow,
  Layers3,
  Users,
  ShieldCheck,
  Target,
  Rocket,
  LineChart,
  Search,
  Cog,
  MessageSquareQuote,
  Building2,
  Landmark,
  Cpu,
  Factory,
  Store,
  HeartPulse,
  Car,
  Plane,
  Coins,
  Calendar,
  ArrowRight,
  CheckCircle2,
  AlertTriangle,
  TrendingUp,
  GitBranch,
  Globe2,
  Lightbulb,
  ClipboardList,
  FileCheck2,
  Send,
  MessagesSquare,
  Mail,
  Phone,
  Timer,
  Trophy,
  Puzzle,
  Handshake,
  Play,
  BarChart3,
  Zap,
  ArrowUpRight,
  Award,
  Book,
  Briefcase,
  Cloud,
  Code2,
  Database,
  FileText,
  Flag,
  Gauge,
  Gift,
  Hammer,
  Heart,
  Home,
  Key,
  Layers,
  Link as LinkIcon,
  Lock,
  Map,
  MessageCircle,
  Package,
  PenTool,
  PieChart,
  Presentation,
  Scale,
  Server,
  Settings,
  Shield,
  Star,
  Table,
  ThumbsUp,
  Truck,
  Video,
  Wallet,
  Wrench,
  Activity,
  Anchor,
  Aperture,
  Archive,
  AtSign,
  Atom,
  Axe,
  BadgeCheck,
  Ban,
  Banknote,
  Barcode,
  Battery,
  Beaker,
  Bell,
  Bike,
  Binary,
  Blocks,
  Bluetooth,
  Bold,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Braces,
  Brain,
  BriefcaseBusiness,
  Brush,
  Bug,
  Building,
  Bus,
  Cable,
  Calculator,
  CalendarCheck,
  CalendarClock,
  Camera,
  CircleDollarSign,
  CircuitBoard,
  Clipboard,
  ClipboardCheck,
  Clock,
  CloudCog,
  CloudUpload,
  Compass,
  Component,
  Contact,
  Container,
  Cookie,
  Copy,
  CreditCard,
  Crop,
  Crosshair,
  Crown,
  Cylinder,
  Diamond,
  Dna,
  Download,
  Drama,
  Droplet,
  Ear,
  Earth,
  Eye,
  Feather,
  FileBadge,
  FileCode,
  FileSearch,
  FileSpreadsheet,
  FileStack,
  Files,
  Film,
  Focus,
  FolderOpen,
  Folders,
  Footprints,
  Forklift,
  Frame,
  Fuel,
  Funnel,
  Gamepad2,
  Gavel,
  Gem,
  Globe,
  GraduationCap,
  Grid3x3,
  Group,
  Hand,
  HandCoins,
  HardDrive,
  HardHat,
  Hash,
  Headphones,
  Hexagon,
  Highlighter,
  History,
  Hospital,
  Hourglass,
  IdCard,
  Image,
  Images,
  Inbox,
  Infinity,
  Info,
  Keyboard,
  Lamp,
  Languages,
  Laptop,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Library,
  LifeBuoy,
  Ligature,
  ListChecks,
  ListOrdered,
  Loader,
  Locate,
  MapPin,
  Maximize,
  Medal,
  Megaphone,
  Menu,
  Merge,
  Mic,
  Microscope,
  Milestone,
  Minimize,
  Monitor,
  Moon,
  MousePointer,
  Move,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Orbit,
  Palette,
  Paperclip,
  PartyPopper,
  Pause,
  PenLine,
  Percent,
  PersonStanding,
  Pill,
  Pin,
  Pipette,
  Plug,
  Podcast,
  Pointer,
  Power,
  Printer,
  QrCode,
  Quote,
  Radar,
  Radio,
  Receipt,
  Recycle,
  Redo2,
  RefreshCw,
  Regex,
  Repeat,
  Replace,
  Reply,
  Rewind,
  Route,
  Rss,
  Ruler,
  Satellite,
  Save,
  Scan,
  ScanLine,
  School,
  Scissors,
  ScreenShare,
  Scroll,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sigma,
  Signal,
  Siren,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Snowflake,
  Sparkle,
  Speaker,
  Spline,
  Split,
  Square,
  SquareStack,
  Stamp,
  Stethoscope,
  Sticker,
  StickyNote,
  Sun,
  Sunrise,
  Syringe,
  Tag,
  Tags,
  Telescope,
  Tent,
  Terminal,
  TestTube,
  TextCursor,
  Thermometer,
  Ticket,
  Trash2,
  TreePine,
  TrendingDown,
  Triangle,
  Type,
  Umbrella,
  Undo2,
  Unlink,
  Upload,
  UserCheck,
  UserCog,
  UserPlus,
  Utensils,
  Variable,
  Vault,
  Vibrate,
  View,
  Voicemail,
  Volume2,
  Warehouse,
  Watch,
  Waves,
  Webhook,
  Wifi,
  Wind,
  ZoomIn,
  type LucideIcon,
} from "lucide-react";

export type IconLibraryEntry = {
  name: string;
  label: string;
  group: "Core" | "Process" | "People" | "Data" | "Industry" | "Comms" | "Object";
  Icon: LucideIcon;
};

export const ICON_LIBRARY: IconLibraryEntry[] = [
  // Core
  { name: "Sparkles", label: "Sparkle", group: "Core", Icon: Sparkles },
  { name: "Target", label: "Target", group: "Core", Icon: Target },
  { name: "Rocket", label: "Rocket", group: "Core", Icon: Rocket },
  { name: "Lightbulb", label: "Idea", group: "Core", Icon: Lightbulb },
  { name: "Star", label: "Star", group: "Core", Icon: Star },
  { name: "Trophy", label: "Trophy", group: "Core", Icon: Trophy },
  { name: "Award", label: "Award", group: "Core", Icon: Award },
  { name: "Flag", label: "Flag", group: "Core", Icon: Flag },
  { name: "Zap", label: "Momentum", group: "Core", Icon: Zap },
  { name: "Heart", label: "Heart", group: "Core", Icon: Heart },
  { name: "CheckCircle2", label: "Approved", group: "Core", Icon: CheckCircle2 },
  { name: "ThumbsUp", label: "Thumbs up", group: "Core", Icon: ThumbsUp },
  { name: "AlertTriangle", label: "Risk", group: "Core", Icon: AlertTriangle },
  { name: "ShieldCheck", label: "Governance", group: "Core", Icon: ShieldCheck },
  { name: "Shield", label: "Shield", group: "Core", Icon: Shield },
  { name: "Lock", label: "Lock", group: "Core", Icon: Lock },
  { name: "Key", label: "Key", group: "Core", Icon: Key },
  { name: "Puzzle", label: "Puzzle piece", group: "Core", Icon: Puzzle },
  { name: "ArrowRight", label: "Arrow", group: "Core", Icon: ArrowRight },
  { name: "ArrowUpRight", label: "Growth arrow", group: "Core", Icon: ArrowUpRight },

  // Process
  { name: "Workflow", label: "Workflow", group: "Process", Icon: Workflow },
  { name: "Layers3", label: "Layered stack", group: "Process", Icon: Layers3 },
  { name: "Layers", label: "Layers", group: "Process", Icon: Layers },
  { name: "GitBranch", label: "Branch / integrate", group: "Process", Icon: GitBranch },
  { name: "ClipboardList", label: "Intake", group: "Process", Icon: ClipboardList },
  { name: "FileCheck2", label: "Review", group: "Process", Icon: FileCheck2 },
  { name: "Send", label: "Deliver", group: "Process", Icon: Send },
  { name: "Play", label: "Start", group: "Process", Icon: Play },
  { name: "Timer", label: "Time / speed", group: "Process", Icon: Timer },
  { name: "Calendar", label: "Calendar", group: "Process", Icon: Calendar },
  { name: "Cog", label: "Configure", group: "Process", Icon: Cog },
  { name: "Settings", label: "Settings", group: "Process", Icon: Settings },
  { name: "Wrench", label: "Wrench", group: "Process", Icon: Wrench },
  { name: "Hammer", label: "Build", group: "Process", Icon: Hammer },
  { name: "PenTool", label: "Design", group: "Process", Icon: PenTool },
  { name: "Search", label: "Discover", group: "Process", Icon: Search },
  { name: "TrendingUp", label: "Grow", group: "Process", Icon: TrendingUp },

  // People
  { name: "Users", label: "Team", group: "People", Icon: Users },
  { name: "Handshake", label: "Partnership", group: "People", Icon: Handshake },
  { name: "MessageSquareQuote", label: "Testimonial", group: "People", Icon: MessageSquareQuote },
  { name: "MessagesSquare", label: "Support", group: "People", Icon: MessagesSquare },
  { name: "MessageCircle", label: "Conversation", group: "People", Icon: MessageCircle },
  { name: "Mail", label: "Email", group: "People", Icon: Mail },
  { name: "Phone", label: "Phone", group: "People", Icon: Phone },
  { name: "Presentation", label: "Presentation", group: "People", Icon: Presentation },
  { name: "Book", label: "Learn", group: "People", Icon: Book },

  // Data
  { name: "LineChart", label: "Trend line", group: "Data", Icon: LineChart },
  { name: "BarChart3", label: "Bar chart", group: "Data", Icon: BarChart3 },
  { name: "PieChart", label: "Pie chart", group: "Data", Icon: PieChart },
  { name: "Gauge", label: "Gauge / KPI", group: "Data", Icon: Gauge },
  { name: "Database", label: "Database", group: "Data", Icon: Database },
  { name: "Table", label: "Table", group: "Data", Icon: Table },
  { name: "FileText", label: "Document", group: "Data", Icon: FileText },
  { name: "Server", label: "Server", group: "Data", Icon: Server },
  { name: "Cloud", label: "Cloud", group: "Data", Icon: Cloud },
  { name: "Code2", label: "Code", group: "Data", Icon: Code2 },
  { name: "Cpu", label: "Compute / AI", group: "Data", Icon: Cpu },
  { name: "LinkIcon", label: "Link", group: "Data", Icon: LinkIcon },

  // Industry
  { name: "Building2", label: "Enterprise", group: "Industry", Icon: Building2 },
  { name: "Landmark", label: "Finance", group: "Industry", Icon: Landmark },
  { name: "HeartPulse", label: "Life sciences", group: "Industry", Icon: HeartPulse },
  { name: "Store", label: "Retail", group: "Industry", Icon: Store },
  { name: "Factory", label: "Industrial", group: "Industry", Icon: Factory },
  { name: "Car", label: "Automotive", group: "Industry", Icon: Car },
  { name: "Plane", label: "Travel", group: "Industry", Icon: Plane },
  { name: "Truck", label: "Logistics", group: "Industry", Icon: Truck },
  { name: "Globe2", label: "Global", group: "Industry", Icon: Globe2 },
  { name: "Map", label: "Map", group: "Industry", Icon: Map },
  { name: "Scale", label: "Legal", group: "Industry", Icon: Scale },
  { name: "Briefcase", label: "Business", group: "Industry", Icon: Briefcase },
  { name: "Home", label: "Home", group: "Industry", Icon: Home },
  { name: "Video", label: "Video / media", group: "Industry", Icon: Video },

  // Object
  { name: "Coins", label: "Cost", group: "Object", Icon: Coins },
  { name: "Wallet", label: "Wallet", group: "Object", Icon: Wallet },
  { name: "Gift", label: "Gift", group: "Object", Icon: Gift },
  { name: "Package", label: "Package", group: "Object", Icon: Package },

  // Extended vocabulary — added so every division's approved set can reach 100
  // glyphs without leaving the curated, single-weight outline family.
  { name: "Activity", label: "Activity", group: "Data", Icon: Activity },
  { name: "Anchor", label: "Anchor", group: "Process", Icon: Anchor },
  { name: "Aperture", label: "Aperture", group: "Data", Icon: Aperture },
  { name: "Archive", label: "Archive", group: "Process", Icon: Archive },
  { name: "AtSign", label: "At Sign", group: "Comms", Icon: AtSign },
  { name: "Atom", label: "Atom", group: "Data", Icon: Atom },
  { name: "Axe", label: "Axe", group: "Industry", Icon: Axe },
  { name: "BadgeCheck", label: "Badge Check", group: "Industry", Icon: BadgeCheck },
  { name: "Ban", label: "Ban", group: "Industry", Icon: Ban },
  { name: "Banknote", label: "Banknote", group: "Industry", Icon: Banknote },
  { name: "Barcode", label: "Barcode", group: "Data", Icon: Barcode },
  { name: "Battery", label: "Battery", group: "Data", Icon: Battery },
  { name: "Beaker", label: "Beaker", group: "Industry", Icon: Beaker },
  { name: "Bell", label: "Bell", group: "Comms", Icon: Bell },
  { name: "Bike", label: "Bike", group: "Industry", Icon: Bike },
  { name: "Binary", label: "Binary", group: "Data", Icon: Binary },
  { name: "Blocks", label: "Blocks", group: "Process", Icon: Blocks },
  { name: "Bluetooth", label: "Bluetooth", group: "Data", Icon: Bluetooth },
  { name: "Bold", label: "Bold", group: "Process", Icon: Bold },
  { name: "Bookmark", label: "Bookmark", group: "Process", Icon: Bookmark },
  { name: "BookOpen", label: "Book Open", group: "Industry", Icon: BookOpen },
  { name: "Bot", label: "Bot", group: "Data", Icon: Bot },
  { name: "Box", label: "Box", group: "Industry", Icon: Box },
  { name: "Boxes", label: "Boxes", group: "Industry", Icon: Boxes },
  { name: "Braces", label: "Braces", group: "Data", Icon: Braces },
  { name: "Brain", label: "Brain", group: "Data", Icon: Brain },
  { name: "BriefcaseBusiness", label: "Briefcase Business", group: "Industry", Icon: BriefcaseBusiness },
  { name: "Brush", label: "Brush", group: "Process", Icon: Brush },
  { name: "Bug", label: "Bug", group: "Process", Icon: Bug },
  { name: "Building", label: "Building", group: "Industry", Icon: Building },
  { name: "Bus", label: "Bus", group: "Industry", Icon: Bus },
  { name: "Cable", label: "Cable", group: "Data", Icon: Cable },
  { name: "Calculator", label: "Calculator", group: "Data", Icon: Calculator },
  { name: "CalendarCheck", label: "Calendar Check", group: "Process", Icon: CalendarCheck },
  { name: "CalendarClock", label: "Calendar Clock", group: "Process", Icon: CalendarClock },
  { name: "Camera", label: "Camera", group: "Comms", Icon: Camera },
  { name: "CircleDollarSign", label: "Circle Dollar Sign", group: "Industry", Icon: CircleDollarSign },
  { name: "CircuitBoard", label: "Circuit Board", group: "Data", Icon: CircuitBoard },
  { name: "Clipboard", label: "Clipboard", group: "Process", Icon: Clipboard },
  { name: "ClipboardCheck", label: "Clipboard Check", group: "Process", Icon: ClipboardCheck },
  { name: "Clock", label: "Clock", group: "Process", Icon: Clock },
  { name: "CloudCog", label: "Cloud Cog", group: "Data", Icon: CloudCog },
  { name: "CloudUpload", label: "Cloud Upload", group: "Data", Icon: CloudUpload },
  { name: "Compass", label: "Compass", group: "Process", Icon: Compass },
  { name: "Component", label: "Component", group: "Data", Icon: Component },
  { name: "Container", label: "Container", group: "Industry", Icon: Container },
  { name: "Contact", label: "Contact", group: "People", Icon: Contact },
  { name: "Cookie", label: "Cookie", group: "Process", Icon: Cookie },
  { name: "Copy", label: "Copy", group: "Process", Icon: Copy },
  { name: "CreditCard", label: "Credit Card", group: "Industry", Icon: CreditCard },
  { name: "Crop", label: "Crop", group: "Process", Icon: Crop },
  { name: "Crosshair", label: "Crosshair", group: "Process", Icon: Crosshair },
  { name: "Crown", label: "Crown", group: "People", Icon: Crown },
  { name: "Cylinder", label: "Cylinder", group: "Process", Icon: Cylinder },
  { name: "Diamond", label: "Diamond", group: "Process", Icon: Diamond },
  { name: "Dna", label: "Dna", group: "Industry", Icon: Dna },
  { name: "Download", label: "Download", group: "Process", Icon: Download },
  { name: "Drama", label: "Drama", group: "People", Icon: Drama },
  { name: "Droplet", label: "Droplet", group: "Process", Icon: Droplet },
  { name: "Ear", label: "Ear", group: "Comms", Icon: Ear },
  { name: "Earth", label: "Earth", group: "Comms", Icon: Earth },
  { name: "Eye", label: "Eye", group: "Data", Icon: Eye },
  { name: "Feather", label: "Feather", group: "Industry", Icon: Feather },
  { name: "FileBadge", label: "File Badge", group: "Data", Icon: FileBadge },
  { name: "FileCode", label: "File Code", group: "Data", Icon: FileCode },
  { name: "FileSearch", label: "File Search", group: "Data", Icon: FileSearch },
  { name: "FileSpreadsheet", label: "File Spreadsheet", group: "Data", Icon: FileSpreadsheet },
  { name: "FileStack", label: "File Stack", group: "Data", Icon: FileStack },
  { name: "Files", label: "Files", group: "Data", Icon: Files },
  { name: "Film", label: "Film", group: "Comms", Icon: Film },
  { name: "Focus", label: "Focus", group: "Data", Icon: Focus },
  { name: "FolderOpen", label: "Folder Open", group: "Data", Icon: FolderOpen },
  { name: "Folders", label: "Folders", group: "Data", Icon: Folders },
  { name: "Footprints", label: "Footprints", group: "People", Icon: Footprints },
  { name: "Forklift", label: "Forklift", group: "Industry", Icon: Forklift },
  { name: "Frame", label: "Frame", group: "Process", Icon: Frame },
  { name: "Fuel", label: "Fuel", group: "Industry", Icon: Fuel },
  { name: "Funnel", label: "Funnel", group: "Process", Icon: Funnel },
  { name: "Gamepad2", label: "Gamepad", group: "Industry", Icon: Gamepad2 },
  { name: "Gavel", label: "Gavel", group: "Industry", Icon: Gavel },
  { name: "Gem", label: "Gem", group: "Process", Icon: Gem },
  { name: "Globe", label: "Globe", group: "Industry", Icon: Globe },
  { name: "GraduationCap", label: "Graduation Cap", group: "People", Icon: GraduationCap },
  { name: "Grid3x3", label: "Grid 3x 3", group: "Data", Icon: Grid3x3 },
  { name: "Group", label: "Group", group: "People", Icon: Group },
  { name: "Hand", label: "Hand", group: "People", Icon: Hand },
  { name: "HandCoins", label: "Hand Coins", group: "People", Icon: HandCoins },
  { name: "HardDrive", label: "Hard Drive", group: "Data", Icon: HardDrive },
  { name: "HardHat", label: "Hard Hat", group: "Industry", Icon: HardHat },
  { name: "Hash", label: "Hash", group: "Data", Icon: Hash },
  { name: "Headphones", label: "Headphones", group: "Comms", Icon: Headphones },
  { name: "Hexagon", label: "Hexagon", group: "Process", Icon: Hexagon },
  { name: "Highlighter", label: "Highlighter", group: "Process", Icon: Highlighter },
  { name: "History", label: "History", group: "Process", Icon: History },
  { name: "Hospital", label: "Hospital", group: "Industry", Icon: Hospital },
  { name: "Hourglass", label: "Hourglass", group: "Process", Icon: Hourglass },
  { name: "IdCard", label: "Id Card", group: "People", Icon: IdCard },
  { name: "Image", label: "Image", group: "Comms", Icon: Image },
  { name: "Images", label: "Images", group: "Comms", Icon: Images },
  { name: "Inbox", label: "Inbox", group: "Comms", Icon: Inbox },
  { name: "Infinity", label: "Infinity", group: "Data", Icon: Infinity },
  { name: "Info", label: "Info", group: "Industry", Icon: Info },
  { name: "Keyboard", label: "Keyboard", group: "Data", Icon: Keyboard },
  { name: "Lamp", label: "Lamp", group: "Industry", Icon: Lamp },
  { name: "Languages", label: "Languages", group: "Comms", Icon: Languages },
  { name: "Laptop", label: "Laptop", group: "Data", Icon: Laptop },
  { name: "LayoutDashboard", label: "Layout Dashboard", group: "Data", Icon: LayoutDashboard },
  { name: "LayoutGrid", label: "Layout Grid", group: "Data", Icon: LayoutGrid },
  { name: "Leaf", label: "Leaf", group: "Process", Icon: Leaf },
  { name: "Library", label: "Library", group: "Industry", Icon: Library },
  { name: "LifeBuoy", label: "Life Buoy", group: "Industry", Icon: LifeBuoy },
  { name: "Ligature", label: "Ligature", group: "Process", Icon: Ligature },
  { name: "ListChecks", label: "List Checks", group: "Process", Icon: ListChecks },
  { name: "ListOrdered", label: "List Ordered", group: "Process", Icon: ListOrdered },
  { name: "Loader", label: "Loader", group: "Data", Icon: Loader },
  { name: "Locate", label: "Locate", group: "Process", Icon: Locate },
  { name: "MapPin", label: "Map Pin", group: "Process", Icon: MapPin },
  { name: "Maximize", label: "Maximize", group: "Process", Icon: Maximize },
  { name: "Medal", label: "Medal", group: "People", Icon: Medal },
  { name: "Megaphone", label: "Megaphone", group: "Comms", Icon: Megaphone },
  { name: "Menu", label: "Menu", group: "Process", Icon: Menu },
  { name: "Merge", label: "Merge", group: "Process", Icon: Merge },
  { name: "Mic", label: "Mic", group: "Comms", Icon: Mic },
  { name: "Microscope", label: "Microscope", group: "Comms", Icon: Microscope },
  { name: "Milestone", label: "Milestone", group: "Process", Icon: Milestone },
  { name: "Minimize", label: "Minimize", group: "Process", Icon: Minimize },
  { name: "Monitor", label: "Monitor", group: "Data", Icon: Monitor },
  { name: "Moon", label: "Moon", group: "Process", Icon: Moon },
  { name: "MousePointer", label: "Mouse Pointer", group: "Process", Icon: MousePointer },
  { name: "Move", label: "Move", group: "Process", Icon: Move },
  { name: "Music", label: "Music", group: "Comms", Icon: Music },
  { name: "Navigation", label: "Navigation", group: "Process", Icon: Navigation },
  { name: "Network", label: "Network", group: "Data", Icon: Network },
  { name: "Newspaper", label: "Newspaper", group: "Comms", Icon: Newspaper },
  { name: "Notebook", label: "Notebook", group: "Industry", Icon: Notebook },
  { name: "NotebookPen", label: "Notebook Pen", group: "Process", Icon: NotebookPen },
  { name: "Orbit", label: "Orbit", group: "Data", Icon: Orbit },
  { name: "Palette", label: "Palette", group: "Process", Icon: Palette },
  { name: "Paperclip", label: "Paperclip", group: "Process", Icon: Paperclip },
  { name: "PartyPopper", label: "Party Popper", group: "Process", Icon: PartyPopper },
  { name: "Pause", label: "Pause", group: "Process", Icon: Pause },
  { name: "PenLine", label: "Pen Line", group: "Process", Icon: PenLine },
  { name: "Percent", label: "Percent", group: "Data", Icon: Percent },
  { name: "PersonStanding", label: "Person Standing", group: "People", Icon: PersonStanding },
  { name: "Pill", label: "Pill", group: "Industry", Icon: Pill },
  { name: "Pin", label: "Pin", group: "Process", Icon: Pin },
  { name: "Pipette", label: "Pipette", group: "Process", Icon: Pipette },
  { name: "Plug", label: "Plug", group: "Data", Icon: Plug },
  { name: "Podcast", label: "Podcast", group: "Comms", Icon: Podcast },
  { name: "Pointer", label: "Pointer", group: "Process", Icon: Pointer },
  { name: "Power", label: "Power", group: "Data", Icon: Power },
  { name: "Printer", label: "Printer", group: "Data", Icon: Printer },
  { name: "QrCode", label: "Qr Code", group: "Data", Icon: QrCode },
  { name: "Quote", label: "Quote", group: "Comms", Icon: Quote },
  { name: "Radar", label: "Radar", group: "Data", Icon: Radar },
  { name: "Radio", label: "Radio", group: "Comms", Icon: Radio },
  { name: "Receipt", label: "Receipt", group: "Industry", Icon: Receipt },
  { name: "Recycle", label: "Recycle", group: "Process", Icon: Recycle },
  { name: "Redo2", label: "Redo", group: "Process", Icon: Redo2 },
  { name: "RefreshCw", label: "Refresh Cw", group: "Process", Icon: RefreshCw },
  { name: "Regex", label: "Regex", group: "Data", Icon: Regex },
  { name: "Repeat", label: "Repeat", group: "Process", Icon: Repeat },
  { name: "Replace", label: "Replace", group: "Process", Icon: Replace },
  { name: "Reply", label: "Reply", group: "Comms", Icon: Reply },
  { name: "Rewind", label: "Rewind", group: "Process", Icon: Rewind },
  { name: "Route", label: "Route", group: "Process", Icon: Route },
  { name: "Rss", label: "Rss", group: "Comms", Icon: Rss },
  { name: "Ruler", label: "Ruler", group: "Process", Icon: Ruler },
  { name: "Satellite", label: "Satellite", group: "Data", Icon: Satellite },
  { name: "Save", label: "Save", group: "Process", Icon: Save },
  { name: "Scan", label: "Scan", group: "Data", Icon: Scan },
  { name: "ScanLine", label: "Scan Line", group: "Data", Icon: ScanLine },
  { name: "School", label: "School", group: "People", Icon: School },
  { name: "Scissors", label: "Scissors", group: "Process", Icon: Scissors },
  { name: "ScreenShare", label: "Screen Share", group: "Comms", Icon: ScreenShare },
  { name: "Scroll", label: "Scroll", group: "Industry", Icon: Scroll },
  { name: "ShoppingBag", label: "Shopping Bag", group: "Industry", Icon: ShoppingBag },
  { name: "ShoppingCart", label: "Shopping Cart", group: "Industry", Icon: ShoppingCart },
  { name: "Shuffle", label: "Shuffle", group: "Process", Icon: Shuffle },
  { name: "Sigma", label: "Sigma", group: "Data", Icon: Sigma },
  { name: "Signal", label: "Signal", group: "Data", Icon: Signal },
  { name: "Siren", label: "Siren", group: "Industry", Icon: Siren },
  { name: "SlidersHorizontal", label: "Sliders Horizontal", group: "Process", Icon: SlidersHorizontal },
  { name: "Smartphone", label: "Smartphone", group: "Data", Icon: Smartphone },
  { name: "Smile", label: "Smile", group: "People", Icon: Smile },
  { name: "Snowflake", label: "Snowflake", group: "Process", Icon: Snowflake },
  { name: "Sparkle", label: "Sparkle", group: "Process", Icon: Sparkle },
  { name: "Speaker", label: "Speaker", group: "Comms", Icon: Speaker },
  { name: "Spline", label: "Spline", group: "Data", Icon: Spline },
  { name: "Split", label: "Split", group: "Process", Icon: Split },
  { name: "Square", label: "Square", group: "Process", Icon: Square },
  { name: "SquareStack", label: "Square Stack", group: "Process", Icon: SquareStack },
  { name: "Stamp", label: "Stamp", group: "Process", Icon: Stamp },
  { name: "Stethoscope", label: "Stethoscope", group: "Industry", Icon: Stethoscope },
  { name: "Sticker", label: "Sticker", group: "Process", Icon: Sticker },
  { name: "StickyNote", label: "Sticky Note", group: "Process", Icon: StickyNote },
  { name: "Sun", label: "Sun", group: "Process", Icon: Sun },
  { name: "Sunrise", label: "Sunrise", group: "Process", Icon: Sunrise },
  { name: "Syringe", label: "Syringe", group: "Industry", Icon: Syringe },
  { name: "Tag", label: "Tag", group: "Process", Icon: Tag },
  { name: "Tags", label: "Tags", group: "Process", Icon: Tags },
  { name: "Telescope", label: "Telescope", group: "Data", Icon: Telescope },
  { name: "Tent", label: "Tent", group: "Industry", Icon: Tent },
  { name: "Terminal", label: "Terminal", group: "Data", Icon: Terminal },
  { name: "TestTube", label: "Test Tube", group: "Industry", Icon: TestTube },
  { name: "TextCursor", label: "Text Cursor", group: "Process", Icon: TextCursor },
  { name: "Thermometer", label: "Thermometer", group: "Process", Icon: Thermometer },
  { name: "Ticket", label: "Ticket", group: "Comms", Icon: Ticket },
  { name: "Trash2", label: "Trash", group: "Industry", Icon: Trash2 },
  { name: "TreePine", label: "Tree Pine", group: "Process", Icon: TreePine },
  { name: "TrendingDown", label: "Trending Down", group: "Data", Icon: TrendingDown },
  { name: "Triangle", label: "Triangle", group: "Process", Icon: Triangle },
  { name: "Type", label: "Type", group: "Process", Icon: Type },
  { name: "Umbrella", label: "Umbrella", group: "Process", Icon: Umbrella },
  { name: "Undo2", label: "Undo", group: "Process", Icon: Undo2 },
  { name: "Unlink", label: "Unlink", group: "Process", Icon: Unlink },
  { name: "Upload", label: "Upload", group: "Process", Icon: Upload },
  { name: "UserCheck", label: "User Check", group: "People", Icon: UserCheck },
  { name: "UserCog", label: "User Cog", group: "People", Icon: UserCog },
  { name: "UserPlus", label: "User Plus", group: "People", Icon: UserPlus },
  { name: "Utensils", label: "Utensils", group: "Industry", Icon: Utensils },
  { name: "Variable", label: "Variable", group: "Data", Icon: Variable },
  { name: "Vault", label: "Vault", group: "Industry", Icon: Vault },
  { name: "Vibrate", label: "Vibrate", group: "Comms", Icon: Vibrate },
  { name: "View", label: "View", group: "Data", Icon: View },
  { name: "Voicemail", label: "Voicemail", group: "Comms", Icon: Voicemail },
  { name: "Volume2", label: "Volume", group: "Comms", Icon: Volume2 },
  { name: "Warehouse", label: "Warehouse", group: "Industry", Icon: Warehouse },
  { name: "Watch", label: "Watch", group: "Industry", Icon: Watch },
  { name: "Waves", label: "Waves", group: "Process", Icon: Waves },
  { name: "Webhook", label: "Webhook", group: "Data", Icon: Webhook },
  { name: "Wifi", label: "Wifi", group: "Data", Icon: Wifi },
  { name: "Wind", label: "Wind", group: "Process", Icon: Wind },
  { name: "ZoomIn", label: "Zoom In", group: "Data", Icon: ZoomIn },
];

const BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  ICON_LIBRARY.map((e) => [e.name, e.Icon]),
);

export function iconByName(name: string | undefined | null): LucideIcon | null {
  if (!name) return null;
  return BY_NAME[name] ?? null;
}

/**
 * Parse a `pack:name` icon reference (e.g. "lucide:home", "ph:rocket").
 * Returns null for plain curated names — those go through `iconByName`.
 */
export function parseIconRef(
  ref: string | undefined | null,
): { packId: string; name: string } | null {
  if (!ref) return null;
  const idx = ref.indexOf(":");
  if (idx <= 0 || idx === ref.length - 1) return null;
  return { packId: ref.slice(0, idx), name: ref.slice(idx + 1) };
}

export const ICON_GROUPS: Array<IconLibraryEntry["group"]> = [
  "Core",
  "Process",
  "People",
  "Data",
  "Industry",
  "Comms",
  "Object",
];
