// Automated QA for every London signage download.
//
// Every file that leaves the London kit — .svg, .ai and .png — is audited
// against the panel's own specification before it reaches the user: artboard
// geometry in mm, trim box placement, bleed per edge, raster pixel count,
// effective ppi and the resulting flat-tone banding run. The audit reads the
// generated bytes, never the intent, so a generator regression is caught at the
// download instead of at the printer.

import { LONDON_MAX_PX } from "@/lib/london-panel-raster";
import {
  panelSlug,
  rasterSizeFor,
  recommendedPpi,
  type LondonPanel,
} from "@/lib/next-london-signage";

const MM_TO_PT = 72 / 25.4;

/** Worst measured flat-tone run in the issued pack — the pass tolerance. */
export const LONDON_BAND_TOLERANCE_MM = 2.9;

export type QaStatus = "pass" | "warn" | "fail";

export type QaCheck = {
  id: string;
  label: string;
  status: QaStatus;
  expected: string;
  actual: string;
  note?: string;
};

export type LondonQaReport = {
  panelId: string;
  panelName: string;
  file: string;
  kind: "svg" | "ai" | "png";
  status: QaStatus;
  checks: QaCheck[];
};

function worst(checks: QaCheck[]): QaStatus {
  if (checks.some((c) => c.status === "fail")) return "fail";
  if (checks.some((c) => c.status === "warn")) return "warn";
  return "pass";
}

function check(
  id: string,
  label: string,
  ok: boolean,
  expected: string,
  actual: string,
  opts: { warnOnly?: boolean; note?: string } = {},
): QaCheck {
  return {
    id,
    label,
    status: ok ? "pass" : opts.warnOnly ? "warn" : "fail",
    expected,
    actual,
    ...(opts.note ? { note: opts.note } : {}),
  };
}

const near = (a: number, b: number, tol = 0.02) => Math.abs(a - b) <= tol;
const mm = (n: number) => `${Math.round(n * 100) / 100} mm`;

// ---------------------------------------------------------------------------
// Spec self-consistency (applies to any output for the panel)
// ---------------------------------------------------------------------------

export function auditPanelSpec(panel: LondonPanel): QaCheck[] {
  const derivedW = panel.trimW + panel.bleedEdge * 2;
  const derivedH = panel.trimH + panel.bleedEdge * 2;
  const tier = recommendedPpi(panel);
  return [
    check(
      "spec-bleed-math",
      "Bleed box = trim + bleed per edge",
      near(panel.bleedW, derivedW, 0.51) && near(panel.bleedH, derivedH, 0.51),
      `${mm(derivedW)} × ${mm(derivedH)}`,
      `${mm(panel.bleedW)} × ${mm(panel.bleedH)}`,
    ),
    check(
      "spec-trim-positive",
      "Trim inside bleed",
      panel.trimW > 0 &&
        panel.trimH > 0 &&
        panel.trimW <= panel.bleedW &&
        panel.trimH <= panel.bleedH,
      "trim ≤ bleed",
      `${mm(panel.trimW)} × ${mm(panel.trimH)}`,
    ),
    check(
      "spec-ppi-tier",
      "Packaged ppi matches the size tier",
      panel.rasterPpi === tier,
      `${tier} ppi`,
      `${panel.rasterPpi} ppi`,
      { warnOnly: true, note: "Overrides are allowed but should be deliberate." },
    ),
  ];
}

// ---------------------------------------------------------------------------
// Vector: SVG
// ---------------------------------------------------------------------------

function attr(svg: string, name: string): string | null {
  const m = new RegExp(`${name}="([^"]*)"`).exec(svg);
  return m ? m[1]! : null;
}

export function auditSvg(panel: LondonPanel, svg: string): LondonQaReport {
  const w = Number.parseFloat(attr(svg, "width") ?? "");
  const h = Number.parseFloat(attr(svg, "height") ?? "");
  const unitOk = /width="[\d.]+mm"/.test(svg) && /height="[\d.]+mm"/.test(svg);
  const viewBox = (attr(svg, "viewBox") ?? "").trim().split(/\s+/).map(Number);
  const trimAttr = attr(svg, "data-trim") ?? "";
  const bleedAttr = Number.parseFloat((attr(svg, "data-bleed") ?? "").replace("mm", ""));

  const checks: QaCheck[] = [
    ...auditPanelSpec(panel),
    check(
      "svg-units",
      "Artboard declared in millimetres",
      unitOk,
      "width/height in mm",
      unitOk ? "mm" : "missing or non-mm units",
    ),
    check(
      "svg-artboard",
      "Artboard sized to bleed",
      near(w, panel.bleedW, 0.05) && near(h, panel.bleedH, 0.05),
      `${mm(panel.bleedW)} × ${mm(panel.bleedH)}`,
      `${mm(w || 0)} × ${mm(h || 0)}`,
    ),
    check(
      "svg-viewbox",
      "User-unit grid matches the bleed aspect",
      viewBox.length === 4 &&
        viewBox.every((n) => Number.isFinite(n)) &&
        viewBox[2]! > 0 &&
        viewBox[3]! > 0 &&
        near(viewBox[2]! / viewBox[3]!, panel.bleedW / panel.bleedH, 0.005),
      `aspect ${(panel.bleedW / panel.bleedH).toFixed(3)} (crop origin is free)`,
      viewBox.length === 4
        ? `${viewBox.join(" ")} (aspect ${(viewBox[2]! / viewBox[3]!).toFixed(3)})`
        : "missing viewBox",
    ),
    check(
      "svg-trim-meta",
      "Trim geometry recorded",
      trimAttr ? trimAttr === `${panel.trimW}x${panel.trimH}mm` : false,
      `${panel.trimW}x${panel.trimH}mm`,
      trimAttr || "absent",
      trimAttr
        ? {}
        : { warnOnly: true, note: "Master carries no trim metadata — cut from the issued proofs." },
    ),
    check(
      "svg-bleed-meta",
      "Bleed per edge recorded",
      Number.isFinite(bleedAttr) ? near(bleedAttr, panel.bleedEdge, 0.05) : false,
      mm(panel.bleedEdge),
      Number.isFinite(bleedAttr) ? mm(bleedAttr) : "absent",
      Number.isFinite(bleedAttr)
        ? {}
        : { warnOnly: true, note: "Bleed is implied by the artboard size on this master." },
    ),
    check(
      "svg-live-gradient",
      "Ground is a live gradient, not a raster",
      /(linear|radial)Gradient/.test(svg) && !/<image/i.test(svg),
      "vector gradient only",
      /<image/i.test(svg) ? "embedded raster found" : "vector gradient",
    ),
  ];

  return {
    panelId: panel.id,
    panelName: panel.name,
    file: `${panelSlug(panel)}.svg`,
    kind: "svg",
    status: worst(checks),
    checks,
  };
}

// ---------------------------------------------------------------------------
// Vector: .ai (PDF-compatible)
// ---------------------------------------------------------------------------

function box(pdf: string, name: string): number[] | null {
  const m = new RegExp(`/${name}\\s*\\[([^\\]]+)\\]`).exec(pdf);
  if (!m) return null;
  const nums = m[1]!.trim().split(/\s+/).map(Number);
  return nums.length === 4 && nums.every((n) => Number.isFinite(n)) ? nums : null;
}

export function auditAi(panel: LondonPanel, ai: string | Uint8Array): LondonQaReport {
  const text = typeof ai === "string" ? ai : Array.from(ai, (b) => String.fromCharCode(b)).join("");

  const media = box(text, "MediaBox");
  const trim = box(text, "TrimBox");
  const expectW = panel.bleedW * MM_TO_PT;
  const expectH = panel.bleedH * MM_TO_PT;
  const trimW = trim ? trim[2]! - trim[0]! : 0;
  const trimH = trim ? trim[3]! - trim[1]! : 0;
  const insetX = trim ? trim[0]! : 0;
  const insetY = trim ? trim[1]! : 0;
  const expectInset = panel.bleedEdge * MM_TO_PT;

  const checks: QaCheck[] = [
    ...auditPanelSpec(panel),
    check(
      "ai-pdf",
      "PDF-compatible Illustrator file",
      text.startsWith("%PDF-") && text.trimEnd().endsWith("%%EOF"),
      "%PDF header + %%EOF trailer",
      text.slice(0, 8).trim() || "unknown",
    ),
    check(
      "ai-mediabox",
      "MediaBox sized to bleed",
      !!media &&
        near(media[2]! - media[0]!, expectW, 0.6) &&
        near(media[3]! - media[1]!, expectH, 0.6),
      `${expectW.toFixed(1)} × ${expectH.toFixed(1)} pt`,
      media
        ? `${(media[2]! - media[0]!).toFixed(1)} × ${(media[3]! - media[1]!).toFixed(1)} pt`
        : "absent",
    ),
    check(
      "ai-trimbox",
      "TrimBox sized to trim",
      trim
        ? near(trimW, panel.trimW * MM_TO_PT, 0.6) && near(trimH, panel.trimH * MM_TO_PT, 0.6)
        : false,
      `${(panel.trimW * MM_TO_PT).toFixed(1)} × ${(panel.trimH * MM_TO_PT).toFixed(1)} pt`,
      trim ? `${trimW.toFixed(1)} × ${trimH.toFixed(1)} pt` : "absent",
      trim
        ? {}
        : {
            warnOnly: true,
            note: "No TrimBox on this master — the RIP cuts to the issued proofs.",
          },
    ),
    check(
      "ai-trim-centred",
      "Trim centred inside bleed",
      trim ? near(insetX, expectInset, 0.6) && near(insetY, expectInset, 0.6) : false,
      `${expectInset.toFixed(1)} pt per edge`,
      trim ? `${insetX.toFixed(1)} / ${insetY.toFixed(1)} pt` : "absent",
      trim ? {} : { warnOnly: true },
    ),
    check(
      "ai-vector-ground",
      "Ground stays vector — no embedded raster",
      !/\/Subtype\s*\/Image/.test(text),
      "no image XObject",
      /\/Subtype\s*\/Image/.test(text) ? "embedded raster found" : "vector only",
    ),
    check(
      "ai-shading",
      "Gradient is a live axial/radial shading",
      /\/ShadingType\s*[23]/.test(text),
      "ShadingType 2 or 3",
      /\/ShadingType\s*[23]/.exec(text)?.[0] ?? "vector paths, no shading dict",
      {
        warnOnly: true,
        note: "Vector-path blends print correctly but are less editable than a live shading.",
      },
    ),
  ];

  return {
    panelId: panel.id,
    panelName: panel.name,
    file: `${panelSlug(panel)}.ai`,
    kind: "ai",
    status: worst(checks),
    checks,
  };
}

// ---------------------------------------------------------------------------
// Raster: PNG
// ---------------------------------------------------------------------------

const PNG_SIG = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

export type PngHeader = { w: number; h: number; bitDepth: number; colorType: number };

/** Read IHDR straight out of the encoded bytes — no canvas round-trip. */
export function readPngHeader(bytes: Uint8Array): PngHeader | null {
  if (bytes.length < 33) return null;
  for (let i = 0; i < 8; i += 1) if (bytes[i] !== PNG_SIG[i]) return null;
  const u32 = (o: number) =>
    ((bytes[o]! << 24) | (bytes[o + 1]! << 16) | (bytes[o + 2]! << 8) | bytes[o + 3]!) >>> 0;
  if (String.fromCharCode(bytes[12]!, bytes[13]!, bytes[14]!, bytes[15]!) !== "IHDR") return null;
  return { w: u32(16), h: u32(20), bitDepth: bytes[24]!, colorType: bytes[25]! };
}

export function auditPng(panel: LondonPanel, ppi: number, bytes: Uint8Array): LondonQaReport {
  const header = readPngHeader(bytes);
  const expect = rasterSizeFor(panel, ppi);
  const capped =
    Math.max((panel.bleedW / 25.4) * ppi, (panel.bleedH / 25.4) * ppi) > LONDON_MAX_PX + 1;
  const w = header?.w ?? 0;
  const h = header?.h ?? 0;
  const effPpi = w > 0 ? w / (panel.bleedW / 25.4) : 0;
  const bandMm = effPpi > 0 ? (25.4 / effPpi) * 3 : Infinity;
  const mb = bytes.byteLength / (1024 * 1024);

  const checks: QaCheck[] = [
    ...auditPanelSpec(panel),
    check(
      "png-signature",
      "Valid lossless PNG",
      !!header,
      "PNG signature + IHDR",
      header ? `${header.bitDepth}-bit, colour type ${header.colorType}` : "unreadable",
    ),
    check(
      "png-depth",
      "8-bit per channel truecolour",
      !!header && header.bitDepth === 8 && (header.colorType === 2 || header.colorType === 6),
      "8-bit RGB/RGBA",
      header ? `${header.bitDepth}-bit, type ${header.colorType}` : "unreadable",
    ),
    check(
      "png-pixels",
      "Pixel count matches the tier",
      w === expect.w && h === expect.h,
      `${expect.w} × ${expect.h} px`,
      header ? `${w} × ${h} px` : "unreadable",
    ),
    check(
      "png-bleed-coverage",
      "Raster covers the full bleed",
      w > 0 && near(w / h, panel.bleedW / panel.bleedH, 0.01),
      `aspect ${(panel.bleedW / panel.bleedH).toFixed(3)} (bleed)`,
      w > 0 ? (w / h).toFixed(3) : "unreadable",
    ),
    check(
      "png-effective-ppi",
      "Effective resolution at print size",
      !capped ? effPpi >= ppi - 1 : effPpi > 0,
      `${ppi} ppi across ${mm(panel.bleedW)}`,
      `${effPpi ? effPpi.toFixed(1) : "0"} ppi`,
      capped
        ? {
            warnOnly: true,
            note: `Capped at ${LONDON_MAX_PX} px, so the file prints below ${ppi} ppi — send the vector.`,
          }
        : {},
    ),
    check(
      "png-banding",
      "Flat-tone run within pack tolerance",
      bandMm <= LONDON_BAND_TOLERANCE_MM,
      `≤ ${LONDON_BAND_TOLERANCE_MM} mm`,
      Number.isFinite(bandMm) ? mm(bandMm) : "unmeasurable",
      { warnOnly: capped, note: "Triangular-PDF dither applied at 1.4 LSB." },
    ),
    check(
      "png-weight",
      "File weight is sane for the RIP",
      mb > 0.01 && mb < 400,
      "0.01–400 MB",
      `${mb.toFixed(2)} MB`,
      { warnOnly: true },
    ),
  ];

  return {
    panelId: panel.id,
    panelName: panel.name,
    file: `${panelSlug(panel)}-${ppi}ppi.png`,
    kind: "png",
    status: worst(checks),
    checks,
  };
}

// ---------------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------------

export function failedChecks(report: LondonQaReport): QaCheck[] {
  return report.checks.filter((c) => c.status !== "pass");
}

/** One-line human summary used in download toasts. */
export function qaSummary(report: LondonQaReport): string {
  const bad = failedChecks(report);
  if (!bad.length)
    return `QA passed — ${report.checks.length} checks on trim, bleed, ppi and banding.`;
  const first = bad[0]!;
  const rest = bad.length > 1 ? ` (+${bad.length - 1} more)` : "";
  return `${first.label}: expected ${first.expected}, got ${first.actual}${rest}`;
}

export type QaRollup = { total: number; pass: number; warn: number; fail: number };

export function rollup(reports: LondonQaReport[]): QaRollup {
  return {
    total: reports.length,
    pass: reports.filter((r) => r.status === "pass").length,
    warn: reports.filter((r) => r.status === "warn").length,
    fail: reports.filter((r) => r.status === "fail").length,
  };
}

const csvCell = (v: string) => (/[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v);

/** Machine-readable audit trail shipped alongside regenerated artwork. */
export function qaReportCsv(reports: LondonQaReport[]): string {
  const rows = ["file,panel,kind,file_status,check,status,expected,actual,note"];
  for (const r of reports) {
    for (const c of r.checks) {
      rows.push(
        [
          r.file,
          r.panelName,
          r.kind,
          r.status,
          c.label,
          c.status,
          c.expected,
          c.actual,
          c.note ?? "",
        ]
          .map(csvCell)
          .join(","),
      );
    }
  }
  return rows.join("\n");
}

/** Audit both vector formats plus the packaged raster tier for one panel. */
export function auditPanelBundle(opts: {
  panel: LondonPanel;
  svg: string;
  ai: string | Uint8Array;
  png?: { ppi: number; bytes: Uint8Array };
}): LondonQaReport[] {
  const out = [auditSvg(opts.panel, opts.svg), auditAi(opts.panel, opts.ai)];
  if (opts.png) out.push(auditPng(opts.panel, opts.png.ppi, opts.png.bytes));
  return out;
}
