// TransPerfect NEXT 2026 — London (QEII Centre) VENUE TEMPLATE SIGNAGE ITEMS.
//
// Second issue from the London location team: the venue's own template pack
// ("List Signage QEII.xlsx" + the per-floor Illustrator/PDF templates). Each row
// below is one signage item the venue expects artwork for, transcribed verbatim
// from that list, with the branding note the team wrote against it.
//
// Dimensions come from the list where the team stated them. Where the list left
// dims blank, the size is read off the supplied venue template artboard; those
// rows carry `dimsSource: "template"` (1:10 proofs are scaled up ×10 and say so)
// so nothing here reads as a measurement we invented.
//
// Pure data, no imports: `next-london-signage.ts` derives the full panel records
// (bleed box, raster size, ppi tier, dither band, weight) from these specs so
// every item gets its own generated gradient ground and the same vector-first
// downloads as the originally issued 54.

export type LondonVenueItemSpec = {
  floor: "EXT" | "GF" | "2F" | "3F" | "4F" | "5F" | "6F";
  room: string;
  name: string;
  /** Ground description shown next to the panel. */
  ground: string;
  /** Gradient treatment id from LONDON_STYLES. */
  style: string;
  trimW: number;
  trimH: number;
  bleedEdge: number;
  /** Venue template file this artwork is placed into. */
  template: string;
  /** Where the trim size came from. */
  dimsSource: "list" | "template" | "template-1:10";
  /** The location team's branding note, verbatim. */
  note: string;
  /** Quantity on site, when the list called one out. */
  qty?: number;
};

export const LONDON_VENUE_ITEMS: LondonVenueItemSpec[] = [
  // ── Exterior ────────────────────────────────────────────────────────────
  {
    floor: "EXT",
    room: "EXTERIOR",
    name: "EXTERIOR FLAG - 1500x4000mm",
    ground: "Tall beam flag",
    style: "01-beam-violet-aqua",
    trimW: 1500,
    trimH: 4000,
    bleedEdge: 25,
    template: "Exterior/Exterior Flags/QEII 1500 x 4000 FLAG 020316.pdf",
    dimsSource: "list",
    qty: 8,
    note: "8 flags outside the venue: TransPerfect & TransPerfect NEXT alternating.",
  },
  {
    floor: "EXT",
    room: "CANOPY",
    name: "CANOPY BANNER - 11775x1350mm",
    ground: "Wide diagonal wash",
    style: "03-wash-diagonal",
    trimW: 11775,
    trimH: 1350,
    bleedEdge: 100,
    template: "No venue template supplied",
    dimsSource: "list",
    note: "BEYOND INTELLIGENCE and TransPerfect.",
  },

  // ── Ground floor ────────────────────────────────────────────────────────
  {
    floor: "GF",
    room: "FOYER",
    name: "FOYER FLOOR VINYL - 4000x800mm",
    ground: "Horizon band",
    style: "04-horizon",
    trimW: 4000,
    trimH: 800,
    bleedEdge: 25,
    template: "No venue template supplied",
    dimsSource: "list",
    note: "Floor vinyl in front of the video wall, 1.6 m away from it. BEYOND INTELLIGENCE.",
  },
  {
    floor: "GF",
    room: "LIFTS",
    name: "LIFT DOOR - 1120x2090mm",
    ground: "Dawn column",
    style: "09-dawn",
    trimW: 1120,
    trimH: 2090,
    bleedEdge: 10,
    template: "GF/Lift Door Template/Lifts_Template.ai",
    dimsSource: "template",
    note: "Ground floor and third floor. Placeholder on each door for a fun quote.",
  },
  {
    floor: "GF",
    room: "LIFTS",
    name: "LIFT WALLS - 1125x2105mm",
    ground: "Veil wall",
    style: "10-veil",
    trimW: 1125,
    trimH: 2105,
    bleedEdge: 10,
    template: "GF/Lift Walls Template/Lifts_Template.ai",
    dimsSource: "template",
    note: "All floors but 1. Use the badge design (back of the badges), adapted as signage.",
  },
  {
    floor: "GF",
    room: "CLOAKROOM",
    name: "CLOAKROOM VINYL - 3390x1900mm",
    ground: "Halo panel",
    style: "08-chevron-sweep",
    trimW: 3390,
    trimH: 1900,
    bleedEdge: 25,
    template: "GF/Cloakroom.pdf",
    dimsSource: "template-1:10",
    note: "Cloakroom signage.",
  },
  {
    floor: "GF",
    room: "REGISTRATION",
    name: "REGISTRATION DESK VINYL - 3390x1900mm",
    ground: "Horizon desk front",
    style: "04-horizon",
    trimW: 3390,
    trimH: 1900,
    bleedEdge: 25,
    template: "GF/REG_DESK_SIZES.pdf",
    dimsSource: "template-1:10",
    note: "CHECK-IN | INFORMATION.",
  },
  {
    floor: "GF",
    room: "CHURCHILL",
    name: "CHURCHILL SI BOOTH WALLS - 3390x1900mm",
    ground: "Beam booth wall",
    style: "01-beam-violet-aqua",
    trimW: 3390,
    trimH: 1900,
    bleedEdge: 100,
    template: "GF/Churchill SI Booths.pdf",
    dimsSource: "template-1:10",
    note: "Covers the Innovation Lounge walls — TransPerfectNEXT widget logo, GlobalLink, TransPerfect.",
  },
  {
    floor: "GF",
    room: "NEXTBREW COFFEE",
    name: "TABLE TOP SQUARE - 750x750mm",
    ground: "Brew diagonal table top",
    style: "11-brew-diagonal",
    trimW: 750,
    trimH: 750,
    bleedEdge: 10,
    template: "No venue template supplied",
    dimsSource: "list",
    qty: 6,
    note: "NEXTbrew onsite coffee shop — brand the table tops.",
  },
  {
    floor: "GF",
    room: "NEXTBREW COFFEE",
    name: "TABLE TOP ROUND - 900mm DIA",
    ground: "Brew diagonal table top",
    style: "11-brew-diagonal",
    trimW: 900,
    trimH: 900,
    bleedEdge: 10,
    template: "No venue template supplied",
    dimsSource: "list",
    qty: 4,
    note: "NEXTbrew round tables — full-bleed circle, apply the cutting path on proof.",
  },
  {
    floor: "GF",
    room: "NEXTBREW COFFEE",
    name: "LOW CIRCLE TABLE TOP - 700mm DIA",
    ground: "Brew diagonal table top",
    style: "11-brew-diagonal",
    trimW: 700,
    trimH: 700,
    bleedEdge: 10,
    template: "No venue template supplied",
    dimsSource: "list",
    note: "NEXTbrew low circle table.",
  },
  {
    floor: "GF",
    room: "NEXTBREW COFFEE",
    name: "TABLE TOP SQUARE - 600x600mm",
    ground: "Brew diagonal table top",
    style: "11-brew-diagonal",
    trimW: 600,
    trimH: 600,
    bleedEdge: 10,
    template: "No venue template supplied",
    dimsSource: "list",
    note: "NEXTbrew small square table.",
  },

  // ── Second floor ────────────────────────────────────────────────────────
  {
    floor: "2F",
    room: "BEAM",
    name: "BEAM VINYL - 4750x850mm",
    ground: "Diagonal wash beam",
    style: "03-wash-diagonal",
    trimW: 4750,
    trimH: 850,
    bleedEdge: 25,
    template: "No venue template supplied",
    dimsSource: "list",
    note: "MediaNEXT branding.",
  },
  {
    floor: "2F",
    room: "REDGRAVE",
    name: "REDGRAVE WALL 2A - 7670x2570mm",
    ground: "Prism sweep wall",
    style: "07-prism-sweep",
    trimW: 7670,
    trimH: 2570,
    bleedEdge: 100,
    template: "No venue template supplied",
    dimsSource: "list",
    note: "TRANSPERFECT NEXT.",
  },
  {
    floor: "2F",
    room: "OLIVIER & BURTON",
    name: "DOOR BRANDING OLIVIER & BURTON - 840x2000mm",
    ground: "Bloom door",
    style: "05-bloom-corner",
    trimW: 840,
    trimH: 2000,
    bleedEdge: 10,
    template: "Venue template requested — sized from 2F/Albert_and_Victoria.ai",
    dimsSource: "template",
    note: "MediaNEXT branding. Template still being requested from the venue.",
  },
  {
    floor: "2F",
    room: "ALBERT",
    name: "DOOR BRANDING ALBERT - 840x2000mm",
    ground: "Bloom door",
    style: "05-bloom-corner",
    trimW: 840,
    trimH: 2000,
    bleedEdge: 10,
    template: "2F/Albert_and_Victoria.ai",
    dimsSource: "template",
    note: "ExperienceNEXT.",
  },
  {
    floor: "2F",
    room: "VICTORIA",
    name: "DOOR BRANDING VICTORIA - 840x2000mm",
    ground: "Bloom door",
    style: "05-bloom-corner",
    trimW: 840,
    trimH: 2000,
    bleedEdge: 10,
    template: "2F/Albert_and_Victoria.ai",
    dimsSource: "template",
    note: "FinanceNEXT.",
  },
  {
    floor: "2F",
    room: "GIELGUD",
    name: "DOOR BRANDING GIELGUD - 850x2020mm",
    ground: "Bloom door",
    style: "05-bloom-corner",
    trimW: 850,
    trimH: 2020,
    bleedEdge: 10,
    template: "2F/Gielgud_entrance.ai",
    dimsSource: "template",
    note: "DigitalNEXT.",
  },

  // ── Third floor ─────────────────────────────────────────────────────────
  {
    floor: "3F",
    room: "PAOLOZZI",
    name: "PAOLOZZI COVER - 4500x6500mm",
    ground: "Prism sweep cover",
    style: "07-prism-sweep",
    trimW: 4500,
    trimH: 6500,
    bleedEdge: 100,
    template: "3F/Palozzi Cover/PALOZZI COVER.png",
    dimsSource: "list",
    note: "1 m returns each side, 100 mm bleed. Checkerboard with all sub-event logos.",
  },
  {
    floor: "3F",
    room: "BALCONY",
    name: "BALCONY WRAP BULKHEAD - 13360x1550mm",
    ground: "Wide diagonal wash",
    style: "03-wash-diagonal",
    trimW: 13360,
    trimH: 1550,
    bleedEdge: 100,
    template: "3F/Balcony Wrap - 3F/Template_for_Balcony_Full.ai",
    dimsSource: "template-1:10",
    note: "Bulkhead only. TransPerfectNEXT & BEYOND INTELLIGENCE.",
  },
  {
    floor: "3F",
    room: "FLEMING",
    name: "FLEMING DOOR ARTWORK - 1500x1500mm",
    ground: "Bloom square",
    style: "05-bloom-corner",
    trimW: 1500,
    trimH: 1500,
    bleedEdge: 10,
    template: "3F/Fleming Whittle Doors/Fleming_Whittle_Doors.ai",
    dimsSource: "list",
    qty: 2,
    note: "2 artworks per room — poly board instead of vinyl.",
  },
  {
    floor: "3F",
    room: "WHITTLE",
    name: "WHITTLE DOOR ARTWORK - 1500x1500mm",
    ground: "Dawn square",
    style: "09-dawn",
    trimW: 1500,
    trimH: 1500,
    bleedEdge: 10,
    template: "3F/Fleming Whittle Doors/Fleming_Whittle_Doors.ai",
    dimsSource: "list",
    qty: 2,
    note: "2 artworks per room — poly board instead of vinyl.",
  },
  {
    floor: "3F",
    room: "EXHIBITION BOOTHS",
    name: "TRADE BOOTH A FRONT - 1830x2440mm",
    ground: "Beam booth front",
    style: "01-beam-violet-aqua",
    trimW: 1830,
    trimH: 2440,
    bleedEdge: 100,
    template: "3F/Exhibition Booths - 3F/TradeBoothA_Front_1830x2440mm_Plus100mmBleed.ai",
    dimsSource: "template",
    note: "Exhibition booths handled separately by the venue — artwork to template.",
  },
  {
    floor: "3F",
    room: "EXHIBITION BOOTHS",
    name: "TRADE BOOTH B FRONT - 1830x2440mm",
    ground: "Prism booth front",
    style: "07-prism-sweep",
    trimW: 1830,
    trimH: 2440,
    bleedEdge: 100,
    template: "3F/Exhibition Booths - 3F/TradeBoothB_Front_1830x2440mm_Plus100mmBleed.ai",
    dimsSource: "template",
    note: "Exhibition booths handled separately by the venue — artwork to template.",
  },

  // ── Fourth floor ────────────────────────────────────────────────────────
  {
    floor: "4F",
    room: "WESTMINSTER",
    name: "DOOR BRANDING WESTMINSTER - 900x2020mm",
    ground: "Bloom door",
    style: "05-bloom-corner",
    trimW: 900,
    trimH: 2020,
    bleedEdge: 10,
    template: "4F/Westminster_door_A_copy.ai",
    dimsSource: "template",
    note: "GamesNEXT.",
  },
  {
    floor: "4F",
    room: "WESTMINSTER",
    name: "WESTMINSTER CORRIDOR PANEL - 900x2020mm",
    ground: "Veil corridor",
    style: "10-veil",
    trimW: 900,
    trimH: 2020,
    bleedEdge: 10,
    template: "4F/Westminster__Corridoor_1.ai",
    dimsSource: "template",
    note: "Corridor run outside Westminster — GamesNEXT.",
  },
  {
    floor: "4F",
    room: "ST JAMES",
    name: "DOOR BRANDING ST JAMES - 900x2020mm",
    ground: "Bloom door",
    style: "05-bloom-corner",
    trimW: 900,
    trimH: 2020,
    bleedEdge: 10,
    template: "4F/St_James_door.ai",
    dimsSource: "template",
    note: "LearnNEXT.",
  },
  {
    floor: "4F",
    room: "ABBEY",
    name: "DOOR BRANDING ABBEY - 920x2020mm",
    ground: "Bloom door",
    style: "05-bloom-corner",
    trimW: 920,
    trimH: 2020,
    bleedEdge: 10,
    template: "4F/Abbey_doors.ai",
    dimsSource: "template",
    note: "GlobalLinkNEXT.",
  },
  {
    floor: "4F",
    room: "WORDSWORTH",
    name: "DOOR BRANDING WORDSWORTH - 900x2020mm",
    ground: "Bloom door",
    style: "05-bloom-corner",
    trimW: 900,
    trimH: 2020,
    bleedEdge: 10,
    template: "Venue template requested — sized from 4F door templates",
    dimsSource: "template",
    note: "DataForceNEXT.",
  },
  {
    floor: "4F",
    room: "ST JAMES",
    name: "PILLAR WRAP ST JAMES - 620x2500mm",
    ground: "Beam pillar",
    style: "01-beam-violet-aqua",
    trimW: 620,
    trimH: 2500,
    bleedEdge: 10,
    template: "5F/Pillar Wrap - 5F/QEII-SquarePillarWraps-2500H_floor_5.pdf",
    dimsSource: "list",
    qty: 2,
    note: "620 mm per side × 2500 mm H, 10 mm bleed. 2 in this room — LearnNEXT version.",
  },
  {
    floor: "4F",
    room: "WESTMINSTER",
    name: "PILLAR WRAP WESTMINSTER - 620x2500mm",
    ground: "Prism pillar",
    style: "07-prism-sweep",
    trimW: 620,
    trimH: 2500,
    bleedEdge: 10,
    template: "5F/Pillar Wrap - 5F/QEII-SquarePillarWraps-2500H_floor_5.pdf",
    dimsSource: "list",
    qty: 2,
    note: "620 mm per side × 2500 mm H, 10 mm bleed. 2 in this room — GamesNEXT version.",
  },
  {
    floor: "4F",
    room: "WESTMINSTER",
    name: "WALL 4E OUTSIDE WESTMINSTER - 2590x2110mm",
    ground: "Prism wall",
    style: "07-prism-sweep",
    trimW: 2590,
    trimH: 2110,
    bleedEdge: 100,
    template: "No venue template supplied",
    dimsSource: "list",
    note: "TransPerfectNEXT.",
  },

  // ── Fifth floor ─────────────────────────────────────────────────────────
  {
    floor: "5F",
    room: "CAMBRIDGE",
    name: "PILLAR WRAP CAMBRIDGE - 620x2500mm",
    ground: "Beam pillar",
    style: "01-beam-violet-aqua",
    trimW: 620,
    trimH: 2500,
    bleedEdge: 10,
    template: "5F/Pillar Wrap - 5F/QEII-SquarePillarWraps-2500H_floor_5.pdf",
    dimsSource: "template",
    note: "OpTImize & LifeSciNEXT co-branded.",
  },
  {
    floor: "5F",
    room: "STAIRS",
    name: "STAIR GLASS PANEL 1 - 1244x1600mm",
    ground: "Dawn glass",
    style: "09-dawn",
    trimW: 1244,
    trimH: 1600,
    bleedEdge: 10,
    template: "5F/Stair Vinyl - 5F/Glass_panel_1_(2).ai",
    dimsSource: "template",
    note: "Stair vinyl — applied to glass, keep copy clear of the handrail line.",
  },
  {
    floor: "5F",
    room: "STAIRS",
    name: "STAIR GLASS PANEL 2 - 1244x1600mm",
    ground: "Dawn glass",
    style: "09-dawn",
    trimW: 1244,
    trimH: 1600,
    bleedEdge: 10,
    template: "5F/Stair Vinyl - 5F/Glass_panel_2.ai",
    dimsSource: "template",
    note: "Stair vinyl — continues the run from panel 1.",
  },
  {
    floor: "5F",
    room: "STAIRS",
    name: "STAIR GLASS PANEL 3 - 1224x1315mm",
    ground: "Veil glass",
    style: "10-veil",
    trimW: 1224,
    trimH: 1315,
    bleedEdge: 10,
    template: "5F/Stair Vinyl - 5F/Glass_panel_3.ai",
    dimsSource: "template",
    note: "Stair vinyl — short return panel at the landing.",
  },
  {
    floor: "5F",
    room: "WINDSOR",
    name: "WINDSOR FASCIA - 870x320mm",
    ground: "Veil fascia",
    style: "10-veil",
    trimW: 870,
    trimH: 320,
    bleedEdge: 10,
    template: "5F/Windosr - 5F/St_James_Westminster_Windsor_Template.ai",
    dimsSource: "template",
    note: "Shared St James / Westminster / Windsor room fascia template.",
  },
  {
    floor: "5F",
    room: "EXHIBITION BOOTHS",
    name: "TRADE BOOTH FRONT - 1220x2440mm",
    ground: "Beam booth front",
    style: "01-beam-violet-aqua",
    trimW: 1220,
    trimH: 2440,
    bleedEdge: 100,
    template: "5F/Exhibition Booths - 5F/TradeBooth_Front_1220x2440mm_Plus100mmBleed.ai",
    dimsSource: "template",
    note: "Exhibition booths handled separately by the venue — artwork to template.",
  },
  {
    floor: "5F",
    room: "EXHIBITION BOOTHS",
    name: "TRADE BOOTH BACK - 1220x2440mm",
    ground: "Dawn booth back",
    style: "09-dawn",
    trimW: 1220,
    trimH: 2440,
    bleedEdge: 100,
    template: "5F/Exhibition Booths - 5F/TradeBooth_Back_1220x2440mm_Plus100mmBleed.ai",
    dimsSource: "template",
    note: "Exhibition booths handled separately by the venue — artwork to template.",
  },

  // ── Sixth floor ─────────────────────────────────────────────────────────
  {
    floor: "6F",
    room: "MOUNTBATTEN",
    name: "MOUNTBATTEN 6A SET WRAP - 4940x2030mm",
    ground: "Prism set wrap",
    style: "07-prism-sweep",
    trimW: 4940,
    trimH: 2030,
    bleedEdge: 100,
    template: "6F/Set Wrap Mountbatten - 6F/Mountbatten_Set_Wrap_Template.ai",
    dimsSource: "list",
    note: "LifeSciNEXT.",
  },
  {
    floor: "6F",
    room: "MOUNTBATTEN",
    name: "MOUNTBATTEN SET RETURN - 3500x4310mm",
    ground: "Bloom set return",
    style: "05-bloom-corner",
    trimW: 3500,
    trimH: 4310,
    bleedEdge: 100,
    template: "6F/Set Wrap Mountbatten - 6F/Mountbatten_Set_Wrap_Template.ai",
    dimsSource: "template-1:10",
    note: "Set return artboard from the venue wrap template — LifeSciNEXT.",
  },

  // ── Step & repeat + door set (third issue) ───────────────────────────────
  {
    floor: "GF",
    room: "STEP & REPEAT",
    name: "STEP & REPEAT WALL - 3000x2400mm",
    ground: "Repeat wash wall",
    style: "12-repeat-wash",
    trimW: 3000,
    trimH: 2400,
    bleedEdge: 50,
    template: "No venue template supplied",
    dimsSource: "list",
    note: "Press and photo wall in the foyer — TransPerfect NEXT repeat rows, BEYOND INTELLIGENCE.",
  },
  {
    floor: "GF",
    room: "STEP & REPEAT",
    name: "STEP & REPEAT WALL WIDE - 4000x2400mm",
    ground: "Repeat wash wall",
    style: "12-repeat-wash",
    trimW: 4000,
    trimH: 2400,
    bleedEdge: 50,
    template: "No venue template supplied",
    dimsSource: "list",
    note: "Wide press wall option for the sponsor photo call — TransPerfect NEXT.",
  },
  {
    floor: "3F",
    room: "STEP & REPEAT",
    name: "STEP & REPEAT WALL 3F - 2400x2400mm",
    ground: "Repeat wash wall",
    style: "12-repeat-wash",
    trimW: 2400,
    trimH: 2400,
    bleedEdge: 50,
    template: "No venue template supplied",
    dimsSource: "list",
    note: "Third floor photo wall beside the exhibition run — TransPerfect NEXT.",
  },
  {
    floor: "GF",
    room: "MAIN DOORS",
    name: "MAIN ENTRANCE DOOR VINYL - 900x2100mm",
    ground: "Bloom door",
    style: "05-bloom-corner",
    trimW: 900,
    trimH: 2100,
    bleedEdge: 10,
    template: "No venue template supplied",
    dimsSource: "list",
    qty: 4,
    note: "Glass entrance doors — WELCOME, applied both leaves.",
  },
  {
    floor: "GF",
    room: "CHURCHILL",
    name: "CHURCHILL DOOR VINYL - 900x2100mm",
    ground: "Beam door",
    style: "01-beam-violet-aqua",
    trimW: 900,
    trimH: 2100,
    bleedEdge: 10,
    template: "No venue template supplied",
    dimsSource: "list",
    qty: 2,
    note: "Innovation Lounge doors — TransPerfect NEXT, room name set as live copy.",
  },
  {
    floor: "6F",
    room: "MOUNTBATTEN",
    name: "MOUNTBATTEN DOOR VINYL - 900x2020mm",
    ground: "Bloom door",
    style: "05-bloom-corner",
    trimW: 900,
    trimH: 2020,
    bleedEdge: 10,
    template: "No venue template supplied",
    dimsSource: "list",
    qty: 2,
    note: "LifeSciNEXT room doors — live copy for the session name.",
  },

  // ── Master NEXT pillar family, in the London kit ─────────────────────────
  // Same geometry as the issued City Series pillar sheet (596.9 × 1981 mm,
  // 25 mm bleed) so the London pack carries the master pillar set with the
  // same per-panel lockup and copy editing as every other item here.
  {
    floor: "GF",
    room: "PILLARS",
    name: "WELCOME PILLAR - 596.9x1981mm",
    ground: "Beam pillar",
    style: "01-beam-violet-aqua",
    trimW: 596.9,
    trimH: 1981,
    bleedEdge: 25,
    template: "Master NEXT pillar sheet",
    dimsSource: "template",
    note: "Master NEXT welcome pillar — WELCOME.",
  },
  {
    floor: "GF",
    room: "PILLARS",
    name: "REGISTRATION PILLAR - 596.9x1981mm",
    ground: "Horizon pillar",
    style: "04-horizon",
    trimW: 596.9,
    trimH: 1981,
    bleedEdge: 25,
    template: "Master NEXT pillar sheet",
    dimsSource: "template",
    note: "Master NEXT registration pillar — REGISTRATION.",
  },
  {
    floor: "GF",
    room: "PILLARS",
    name: "GENERAL LOGO PILLAR - 596.9x1981mm",
    ground: "Dawn pillar",
    style: "09-dawn",
    trimW: 596.9,
    trimH: 1981,
    bleedEdge: 25,
    template: "Master NEXT pillar sheet",
    dimsSource: "template",
    note: "Master NEXT general logo pillar — lockup and QR only, no headline.",
  },
  {
    floor: "3F",
    room: "PILLARS",
    name: "DIRECTIONAL PILLAR - 596.9x1981mm",
    ground: "Prism pillar",
    style: "07-prism-sweep",
    trimW: 596.9,
    trimH: 1981,
    bleedEdge: 25,
    template: "Master NEXT pillar sheet",
    dimsSource: "template",
    note: "Master NEXT directional pillar — MAIN STAGE.",
  },
];
