// TransPerfect NEXT 2026 - London (QEII Centre) SUPPLIED PRINT PACK, 18 Sep 2026.
//
// The location team's delivery for job 2281: one finished Illustrator master
// (PDF-compatible) per print area, the print-ready PDF alongside it where one
// was supplied, and a flat render of every artboard page inside that file.
//
// This pack REPLACES every earlier supplied master for the areas it covers, so
// the hub cards, the live editor ground, the venue renders and the vendor
// downloads all serve what the venue will actually print. Areas the pack does
// not cover keep whatever was in force and say so - nothing is silently
// rebuilt, and nothing here is regenerated by us.
//
// Sizes are the MEASURED artboard, not a stated size: several masters are
// supplied scaled (Paolozzi at 50%, the canopy at 25%, Redgrave / the metal
// wall / the set-wrap and balcony templates at 1:10), so `londonPackScale`
// reports the ratio against the area trim rather than letting a scaled sheet
// read as a full-size one.

import aV01MasterAi from "@/assets/london-pack-2281/v01-master.ai.asset.json";
import aV01PrintPdf from "@/assets/london-pack-2281/v01-print.pdf.asset.json";
import aV01ProofP1Jpg from "@/assets/london-pack-2281/v01-proof-p1.jpg.asset.json";
import aV52MasterAi from "@/assets/london-pack-2281/v52-master.ai.asset.json";
import aV52PrintPdf from "@/assets/london-pack-2281/v52-print.pdf.asset.json";
import aV52ProofP1Jpg from "@/assets/london-pack-2281/v52-proof-p1.jpg.asset.json";
import aV61MasterAi from "@/assets/london-pack-2281/v61-master.ai.asset.json";
import aV61PrintPdf from "@/assets/london-pack-2281/v61-print.pdf.asset.json";
import aV61ProofP1Jpg from "@/assets/london-pack-2281/v61-proof-p1.jpg.asset.json";
import aV02MasterAi from "@/assets/london-pack-2281/v02-master.ai.asset.json";
import aV02PrintPdf from "@/assets/london-pack-2281/v02-print.pdf.asset.json";
import aV02ProofP1Jpg from "@/assets/london-pack-2281/v02-proof-p1.jpg.asset.json";
import aV03MasterAi from "@/assets/london-pack-2281/v03-master.ai.asset.json";
import aV03PrintPdf from "@/assets/london-pack-2281/v03-print.pdf.asset.json";
import aV03ProofP1Jpg from "@/assets/london-pack-2281/v03-proof-p1.jpg.asset.json";
import aV04MasterAi from "@/assets/london-pack-2281/v04-master.ai.asset.json";
import aV04ProofP1Jpg from "@/assets/london-pack-2281/v04-proof-p1.jpg.asset.json";
import aV04ProofP2Jpg from "@/assets/london-pack-2281/v04-proof-p2.jpg.asset.json";
import aV05MasterAi from "@/assets/london-pack-2281/v05-master.ai.asset.json";
import aV05PrintPdf from "@/assets/london-pack-2281/v05-print.pdf.asset.json";
import aV05ProofP1Jpg from "@/assets/london-pack-2281/v05-proof-p1.jpg.asset.json";
import aV06MasterPdf from "@/assets/london-pack-2281/v06-master.pdf.asset.json";
import aV06ProofP1Jpg from "@/assets/london-pack-2281/v06-proof-p1.jpg.asset.json";
import aV07MasterPdf from "@/assets/london-pack-2281/v07-master.pdf.asset.json";
import aV07ProofP1Jpg from "@/assets/london-pack-2281/v07-proof-p1.jpg.asset.json";
import aV07ProofP2Jpg from "@/assets/london-pack-2281/v07-proof-p2.jpg.asset.json";
import aV07ProofP3Jpg from "@/assets/london-pack-2281/v07-proof-p3.jpg.asset.json";
import aV07ProofP4Jpg from "@/assets/london-pack-2281/v07-proof-p4.jpg.asset.json";
import aV53MasterAi from "@/assets/london-pack-2281/v53-master.ai.asset.json";
import aV53PrintPdf from "@/assets/london-pack-2281/v53-print.pdf.asset.json";
import aV53ProofP1Jpg from "@/assets/london-pack-2281/v53-proof-p1.jpg.asset.json";
import aV08MasterPdf from "@/assets/london-pack-2281/v08-master.pdf.asset.json";
import aV08ProofP1Jpg from "@/assets/london-pack-2281/v08-proof-p1.jpg.asset.json";
import aV08ProofP2Jpg from "@/assets/london-pack-2281/v08-proof-p2.jpg.asset.json";
import aV08ProofP3Jpg from "@/assets/london-pack-2281/v08-proof-p3.jpg.asset.json";
import aV08ProofP4Jpg from "@/assets/london-pack-2281/v08-proof-p4.jpg.asset.json";
import aV08ProofP5Jpg from "@/assets/london-pack-2281/v08-proof-p5.jpg.asset.json";
import aV08ProofP6Jpg from "@/assets/london-pack-2281/v08-proof-p6.jpg.asset.json";
import aV08ProofP7Jpg from "@/assets/london-pack-2281/v08-proof-p7.jpg.asset.json";
import aV08ProofP8Jpg from "@/assets/london-pack-2281/v08-proof-p8.jpg.asset.json";
import aV08ProofP9Jpg from "@/assets/london-pack-2281/v08-proof-p9.jpg.asset.json";
import aV09MasterAi from "@/assets/london-pack-2281/v09-master.ai.asset.json";
import aV09ProofP1Jpg from "@/assets/london-pack-2281/v09-proof-p1.jpg.asset.json";
import aV10MasterAi from "@/assets/london-pack-2281/v10-master.ai.asset.json";
import aV10ProofP1Jpg from "@/assets/london-pack-2281/v10-proof-p1.jpg.asset.json";
import aV11MasterAi from "@/assets/london-pack-2281/v11-master.ai.asset.json";
import aV11ProofP1Jpg from "@/assets/london-pack-2281/v11-proof-p1.jpg.asset.json";
import aV12MasterAi from "@/assets/london-pack-2281/v12-master.ai.asset.json";
import aV12ProofP1Jpg from "@/assets/london-pack-2281/v12-proof-p1.jpg.asset.json";
import aV46MasterAi from "@/assets/london-pack-2281/v46-master.ai.asset.json";
import aV46PrintPdf from "@/assets/london-pack-2281/v46-print.pdf.asset.json";
import aV46ProofP1Jpg from "@/assets/london-pack-2281/v46-proof-p1.jpg.asset.json";
import aV46ProofP2Jpg from "@/assets/london-pack-2281/v46-proof-p2.jpg.asset.json";
import aV55MasterAi from "@/assets/london-pack-2281/v55-master.ai.asset.json";
import aV55PrintPdf from "@/assets/london-pack-2281/v55-print.pdf.asset.json";
import aV55ProofP1Jpg from "@/assets/london-pack-2281/v55-proof-p1.jpg.asset.json";
import aV56MasterAi from "@/assets/london-pack-2281/v56-master.ai.asset.json";
import aV56PrintPdf from "@/assets/london-pack-2281/v56-print.pdf.asset.json";
import aV56ProofP1Jpg from "@/assets/london-pack-2281/v56-proof-p1.jpg.asset.json";
import aV64MasterAi from "@/assets/london-pack-2281/v64-master.ai.asset.json";
import aV64PrintPdf from "@/assets/london-pack-2281/v64-print.pdf.asset.json";
import aV64ProofP1Jpg from "@/assets/london-pack-2281/v64-proof-p1.jpg.asset.json";
import aV65MasterAi from "@/assets/london-pack-2281/v65-master.ai.asset.json";
import aV65PrintPdf from "@/assets/london-pack-2281/v65-print.pdf.asset.json";
import aV65ProofP1Jpg from "@/assets/london-pack-2281/v65-proof-p1.jpg.asset.json";
import aV65ProofP2Jpg from "@/assets/london-pack-2281/v65-proof-p2.jpg.asset.json";
import aV65ProofP3Jpg from "@/assets/london-pack-2281/v65-proof-p3.jpg.asset.json";
import aV65ProofP4Jpg from "@/assets/london-pack-2281/v65-proof-p4.jpg.asset.json";
import aV65ProofP5Jpg from "@/assets/london-pack-2281/v65-proof-p5.jpg.asset.json";
import aV65ProofP6Jpg from "@/assets/london-pack-2281/v65-proof-p6.jpg.asset.json";
import aV65ProofP7Jpg from "@/assets/london-pack-2281/v65-proof-p7.jpg.asset.json";
import aV65ProofP8Jpg from "@/assets/london-pack-2281/v65-proof-p8.jpg.asset.json";
import aV65ProofP9Jpg from "@/assets/london-pack-2281/v65-proof-p9.jpg.asset.json";
import aV65ProofP10Jpg from "@/assets/london-pack-2281/v65-proof-p10.jpg.asset.json";
import aV65ProofP11Jpg from "@/assets/london-pack-2281/v65-proof-p11.jpg.asset.json";
import aV65ProofP12Jpg from "@/assets/london-pack-2281/v65-proof-p12.jpg.asset.json";
import aV65ProofP13Jpg from "@/assets/london-pack-2281/v65-proof-p13.jpg.asset.json";
import aV13MasterAi from "@/assets/london-pack-2281/v13-master.ai.asset.json";
import aV13PrintPdf from "@/assets/london-pack-2281/v13-print.pdf.asset.json";
import aV13ProofP1Jpg from "@/assets/london-pack-2281/v13-proof-p1.jpg.asset.json";
import aV14MasterAi from "@/assets/london-pack-2281/v14-master.ai.asset.json";
import aV14PrintPdf from "@/assets/london-pack-2281/v14-print.pdf.asset.json";
import aV14ProofP1Jpg from "@/assets/london-pack-2281/v14-proof-p1.jpg.asset.json";
import aV15MasterAi from "@/assets/london-pack-2281/v15-master.ai.asset.json";
import aV15PrintPdf from "@/assets/london-pack-2281/v15-print.pdf.asset.json";
import aV15ProofP1Jpg from "@/assets/london-pack-2281/v15-proof-p1.jpg.asset.json";
import aV15ProofP2Jpg from "@/assets/london-pack-2281/v15-proof-p2.jpg.asset.json";
import aV16MasterAi from "@/assets/london-pack-2281/v16-master.ai.asset.json";
import aV16PrintPdf from "@/assets/london-pack-2281/v16-print.pdf.asset.json";
import aV16ProofP1Jpg from "@/assets/london-pack-2281/v16-proof-p1.jpg.asset.json";
import aV16ProofP2Jpg from "@/assets/london-pack-2281/v16-proof-p2.jpg.asset.json";
import aV17MasterAi from "@/assets/london-pack-2281/v17-master.ai.asset.json";
import aV17PrintPdf from "@/assets/london-pack-2281/v17-print.pdf.asset.json";
import aV17ProofP1Jpg from "@/assets/london-pack-2281/v17-proof-p1.jpg.asset.json";
import aV17ProofP2Jpg from "@/assets/london-pack-2281/v17-proof-p2.jpg.asset.json";
import aV18MasterAi from "@/assets/london-pack-2281/v18-master.ai.asset.json";
import aV18PrintPdf from "@/assets/london-pack-2281/v18-print.pdf.asset.json";
import aV18ProofP1Jpg from "@/assets/london-pack-2281/v18-proof-p1.jpg.asset.json";
import aV18ProofP2Jpg from "@/assets/london-pack-2281/v18-proof-p2.jpg.asset.json";
import aV19MasterAi from "@/assets/london-pack-2281/v19-master.ai.asset.json";
import aV19PrintPdf from "@/assets/london-pack-2281/v19-print.pdf.asset.json";
import aV19ProofP1Jpg from "@/assets/london-pack-2281/v19-proof-p1.jpg.asset.json";
import aV20MasterAi from "@/assets/london-pack-2281/v20-master.ai.asset.json";
import aV20ProofP1Jpg from "@/assets/london-pack-2281/v20-proof-p1.jpg.asset.json";
import aV20ProofP2Jpg from "@/assets/london-pack-2281/v20-proof-p2.jpg.asset.json";
import aV20ProofP3Jpg from "@/assets/london-pack-2281/v20-proof-p3.jpg.asset.json";
import aV20ProofP4Jpg from "@/assets/london-pack-2281/v20-proof-p4.jpg.asset.json";
import aV20ProofP5Jpg from "@/assets/london-pack-2281/v20-proof-p5.jpg.asset.json";
import aV20ProofP6Jpg from "@/assets/london-pack-2281/v20-proof-p6.jpg.asset.json";
import aV21MasterAi from "@/assets/london-pack-2281/v21-master.ai.asset.json";
import aV21PrintPdf from "@/assets/london-pack-2281/v21-print.pdf.asset.json";
import aV21ProofP1Jpg from "@/assets/london-pack-2281/v21-proof-p1.jpg.asset.json";
import aV21ProofP2Jpg from "@/assets/london-pack-2281/v21-proof-p2.jpg.asset.json";
import aV22MasterAi from "@/assets/london-pack-2281/v22-master.ai.asset.json";
import aV22PrintPdf from "@/assets/london-pack-2281/v22-print.pdf.asset.json";
import aV22ProofP2Jpg from "@/assets/london-pack-2281/v22-proof-p2.jpg.asset.json";
import aV22ProofP1Jpg from "@/assets/london-pack-2281/v22-proof-p1.jpg.asset.json";
import aV62MasterAi from "@/assets/london-pack-2281/v62-master.ai.asset.json";
import aV62PrintPdf from "@/assets/london-pack-2281/v62-print.pdf.asset.json";
import aV62ProofP1Jpg from "@/assets/london-pack-2281/v62-proof-p1.jpg.asset.json";
import aV63MasterAi from "@/assets/london-pack-2281/v63-master.ai.asset.json";
import aV63PrintPdf from "@/assets/london-pack-2281/v63-print.pdf.asset.json";
import aV63ProofP1Jpg from "@/assets/london-pack-2281/v63-proof-p1.jpg.asset.json";
import aV25MasterAi from "@/assets/london-pack-2281/v25-master.ai.asset.json";
import aV25ProofP1Jpg from "@/assets/london-pack-2281/v25-proof-p1.jpg.asset.json";
import aV25ProofP2Jpg from "@/assets/london-pack-2281/v25-proof-p2.jpg.asset.json";
import aV26MasterAi from "@/assets/london-pack-2281/v26-master.ai.asset.json";
import aV26PrintPdf from "@/assets/london-pack-2281/v26-print.pdf.asset.json";
import aV26ProofP1Jpg from "@/assets/london-pack-2281/v26-proof-p1.jpg.asset.json";
import aV26ProofP2Jpg from "@/assets/london-pack-2281/v26-proof-p2.jpg.asset.json";
import aV27MasterAi from "@/assets/london-pack-2281/v27-master.ai.asset.json";
import aV27PrintPdf from "@/assets/london-pack-2281/v27-print.pdf.asset.json";
import aV27ProofP1Jpg from "@/assets/london-pack-2281/v27-proof-p1.jpg.asset.json";
import aV27ProofP2Jpg from "@/assets/london-pack-2281/v27-proof-p2.jpg.asset.json";
import aV28MasterAi from "@/assets/london-pack-2281/v28-master.ai.asset.json";
import aV28PrintPdf from "@/assets/london-pack-2281/v28-print.pdf.asset.json";
import aV28ProofP1Jpg from "@/assets/london-pack-2281/v28-proof-p1.jpg.asset.json";
import aV28ProofP2Jpg from "@/assets/london-pack-2281/v28-proof-p2.jpg.asset.json";
import aV28ProofP3Jpg from "@/assets/london-pack-2281/v28-proof-p3.jpg.asset.json";
import aV29MasterAi from "@/assets/london-pack-2281/v29-master.ai.asset.json";
import aV29PrintPdf from "@/assets/london-pack-2281/v29-print.pdf.asset.json";
import aV29ProofP1Jpg from "@/assets/london-pack-2281/v29-proof-p1.jpg.asset.json";
import aV30MasterAi from "@/assets/london-pack-2281/v30-master.ai.asset.json";
import aV30PrintPdf from "@/assets/london-pack-2281/v30-print.pdf.asset.json";
import aV30ProofP1Jpg from "@/assets/london-pack-2281/v30-proof-p1.jpg.asset.json";
import aV31MasterAi from "@/assets/london-pack-2281/v31-master.ai.asset.json";
import aV31PrintPdf from "@/assets/london-pack-2281/v31-print.pdf.asset.json";
import aV31ProofP1Jpg from "@/assets/london-pack-2281/v31-proof-p1.jpg.asset.json";
import aV32MasterAi from "@/assets/london-pack-2281/v32-master.ai.asset.json";
import aV32PrintPdf from "@/assets/london-pack-2281/v32-print.pdf.asset.json";
import aV32ProofP1Jpg from "@/assets/london-pack-2281/v32-proof-p1.jpg.asset.json";
import aV33MasterAi from "@/assets/london-pack-2281/v33-master.ai.asset.json";
import aV33PrintPdf from "@/assets/london-pack-2281/v33-print.pdf.asset.json";
import aV33ProofP1Jpg from "@/assets/london-pack-2281/v33-proof-p1.jpg.asset.json";
import aV34MasterAi from "@/assets/london-pack-2281/v34-master.ai.asset.json";
import aV34PrintPdf from "@/assets/london-pack-2281/v34-print.pdf.asset.json";
import aV34ProofP1Jpg from "@/assets/london-pack-2281/v34-proof-p1.jpg.asset.json";
import aV35MasterAi from "@/assets/london-pack-2281/v35-master.ai.asset.json";
import aV35PrintPdf from "@/assets/london-pack-2281/v35-print.pdf.asset.json";
import aV35ProofP1Jpg from "@/assets/london-pack-2281/v35-proof-p1.jpg.asset.json";
import aV36MasterAi from "@/assets/london-pack-2281/v36-master.ai.asset.json";
import aV36PrintPdf from "@/assets/london-pack-2281/v36-print.pdf.asset.json";
import aV36ProofP1Jpg from "@/assets/london-pack-2281/v36-proof-p1.jpg.asset.json";
import aV37MasterAi from "@/assets/london-pack-2281/v37-master.ai.asset.json";
import aV37PrintPdf from "@/assets/london-pack-2281/v37-print.pdf.asset.json";
import aV37ProofP1Jpg from "@/assets/london-pack-2281/v37-proof-p1.jpg.asset.json";
import aV40MasterAi from "@/assets/london-pack-2281/v40-master.ai.asset.json";
import aV40PrintPdf from "@/assets/london-pack-2281/v40-print.pdf.asset.json";
import aV40ProofP1Jpg from "@/assets/london-pack-2281/v40-proof-p1.jpg.asset.json";
import aV41MasterAi from "@/assets/london-pack-2281/v41-master.ai.asset.json";
import aV41PrintPdf from "@/assets/london-pack-2281/v41-print.pdf.asset.json";
import aV41ProofP1Jpg from "@/assets/london-pack-2281/v41-proof-p1.jpg.asset.json";
import aV41ProofP2Jpg from "@/assets/london-pack-2281/v41-proof-p2.jpg.asset.json";
import aV41ProofP3Jpg from "@/assets/london-pack-2281/v41-proof-p3.jpg.asset.json";
import aLiftStepintoMasterAi from "@/assets/london-pack-2281/lift-stepinto-master.ai.asset.json";
import aLiftStepintoPrintPdf from "@/assets/london-pack-2281/lift-stepinto-print.pdf.asset.json";
import aLiftStepintoProofP1Jpg from "@/assets/london-pack-2281/lift-stepinto-proof-p1.jpg.asset.json";
import aLiftLiftyourMasterAi from "@/assets/london-pack-2281/lift-liftyour-master.ai.asset.json";
import aLiftLiftyourPrintPdf from "@/assets/london-pack-2281/lift-liftyour-print.pdf.asset.json";
import aLiftLiftyourProofP1Jpg from "@/assets/london-pack-2281/lift-liftyour-proof-p1.jpg.asset.json";
import aLiftThinkbiggerMasterAi from "@/assets/london-pack-2281/lift-thinkbigger-master.ai.asset.json";
import aLiftThinkbiggerPrintPdf from "@/assets/london-pack-2281/lift-thinkbigger-print.pdf.asset.json";
import aLiftThinkbiggerProofP1Jpg from "@/assets/london-pack-2281/lift-thinkbigger-proof-p1.jpg.asset.json";
import aLiftWhereideasMasterAi from "@/assets/london-pack-2281/lift-whereideas-master.ai.asset.json";
import aLiftWhereideasPrintPdf from "@/assets/london-pack-2281/lift-whereideas-print.pdf.asset.json";
import aLiftWhereideasProofP1Jpg from "@/assets/london-pack-2281/lift-whereideas-proof-p1.jpg.asset.json";
import aLiftElevateMasterAi from "@/assets/london-pack-2281/lift-elevate-master.ai.asset.json";
import aLiftElevatePrintPdf from "@/assets/london-pack-2281/lift-elevate-print.pdf.asset.json";
import aLiftElevateProofP1Jpg from "@/assets/london-pack-2281/lift-elevate-proof-p1.jpg.asset.json";
import aLiftCantspellMasterAi from "@/assets/london-pack-2281/lift-cantspell-master.ai.asset.json";
import aLiftCantspellPrintPdf from "@/assets/london-pack-2281/lift-cantspell-print.pdf.asset.json";
import aLiftCantspellProofP1Jpg from "@/assets/london-pack-2281/lift-cantspell-proof-p1.jpg.asset.json";
import aGlass1MasterAi from "@/assets/london-pack-2281/glass-1-master.ai.asset.json";
import aGlass1PrintPdf from "@/assets/london-pack-2281/glass-1-print.pdf.asset.json";
import aGlass1ProofP1Jpg from "@/assets/london-pack-2281/glass-1-proof-p1.jpg.asset.json";
import aGlass2MasterAi from "@/assets/london-pack-2281/glass-2-master.ai.asset.json";
import aGlass2PrintPdf from "@/assets/london-pack-2281/glass-2-print.pdf.asset.json";
import aGlass2ProofP1Jpg from "@/assets/london-pack-2281/glass-2-proof-p1.jpg.asset.json";
import aGlass3MasterAi from "@/assets/london-pack-2281/glass-3-master.ai.asset.json";
import aGlass3PrintPdf from "@/assets/london-pack-2281/glass-3-print.pdf.asset.json";
import aGlass3ProofP1Jpg from "@/assets/london-pack-2281/glass-3-proof-p1.jpg.asset.json";
import aGlass4MasterAi from "@/assets/london-pack-2281/glass-4-master.ai.asset.json";
import aGlass4PrintPdf from "@/assets/london-pack-2281/glass-4-print.pdf.asset.json";
import aGlass4ProofP1Jpg from "@/assets/london-pack-2281/glass-4-proof-p1.jpg.asset.json";
import aGlass5MasterAi from "@/assets/london-pack-2281/glass-5-master.ai.asset.json";
import aGlass5PrintPdf from "@/assets/london-pack-2281/glass-5-print.pdf.asset.json";
import aGlass5ProofP1Jpg from "@/assets/london-pack-2281/glass-5-proof-p1.jpg.asset.json";
import aGlass6MasterAi from "@/assets/london-pack-2281/glass-6-master.ai.asset.json";
import aGlass6PrintPdf from "@/assets/london-pack-2281/glass-6-print.pdf.asset.json";
import aGlass6ProofP1Jpg from "@/assets/london-pack-2281/glass-6-proof-p1.jpg.asset.json";
import aGlass7MasterAi from "@/assets/london-pack-2281/glass-7-master.ai.asset.json";
import aGlass7PrintPdf from "@/assets/london-pack-2281/glass-7-print.pdf.asset.json";
import aGlass7ProofP1Jpg from "@/assets/london-pack-2281/glass-7-proof-p1.jpg.asset.json";
import aGlass8MasterAi from "@/assets/london-pack-2281/glass-8-master.ai.asset.json";
import aGlass8PrintAi from "@/assets/london-pack-2281/glass-8-print.ai.asset.json";
import aGlass8ProofP1Jpg from "@/assets/london-pack-2281/glass-8-proof-p1.jpg.asset.json";
import aGlass9MasterAi from "@/assets/london-pack-2281/glass-9-master.ai.asset.json";
import aGlass9PrintPdf from "@/assets/london-pack-2281/glass-9-print.pdf.asset.json";
import aGlass9ProofP1Jpg from "@/assets/london-pack-2281/glass-9-proof-p1.jpg.asset.json";
import aRegSideLeftMasterAi from "@/assets/london-pack-2281/reg-side-left-master.ai.asset.json";
import aRegSideLeftPrintPdf from "@/assets/london-pack-2281/reg-side-left-print.pdf.asset.json";
import aRegSideLeftProofP1Jpg from "@/assets/london-pack-2281/reg-side-left-proof-p1.jpg.asset.json";
import aRegSideRightMasterAi from "@/assets/london-pack-2281/reg-side-right-master.ai.asset.json";
import aRegSideRightPrintPdf from "@/assets/london-pack-2281/reg-side-right-print.pdf.asset.json";
import aRegSideRightProofP1Jpg from "@/assets/london-pack-2281/reg-side-right-proof-p1.jpg.asset.json";
import aReg4155MasterAi from "@/assets/london-pack-2281/reg-4155-master.ai.asset.json";
import aReg4155PrintPdf from "@/assets/london-pack-2281/reg-4155-print.pdf.asset.json";
import aReg4155ProofP1Jpg from "@/assets/london-pack-2281/reg-4155-proof-p1.jpg.asset.json";
import aPaolozziSetwrapMasterAi from "@/assets/london-pack-2281/paolozzi-setwrap-master.ai.asset.json";
import aPaolozziSetwrapPrintPdf from "@/assets/london-pack-2281/paolozzi-setwrap-print.pdf.asset.json";
import aPaolozziSetwrapProofP1Jpg from "@/assets/london-pack-2281/paolozzi-setwrap-proof-p1.jpg.asset.json";
import aPaolozziSetwrapProofP2Jpg from "@/assets/london-pack-2281/paolozzi-setwrap-proof-p2.jpg.asset.json";
import aPaolozziSetwrapProofP3Jpg from "@/assets/london-pack-2281/paolozzi-setwrap-proof-p3.jpg.asset.json";

export type LondonPackPage = {
  page: number;
  /** Measured artboard width in mm. */
  wMm: number;
  /** Measured artboard height in mm. */
  hMm: number;
};

export type LondonPackArea = {
  panelId: string;
  /**
   * What the supplied file actually is. Only "artwork" is finished print art;
   * "survey" is a dimensioned site photograph and "template" is a cut/geometry
   * sheet. Neither may paint a sign ground or stand in as the print file.
   */
  kind: "artwork" | "survey" | "template";
  /** Honest caveat about the supplied file, shown on the card. */
  warning: string | null;
  masterUrl: string;
  masterFilename: string;
  printUrl: string | null;
  printFilename: string | null;
  /** Flat render of each artboard page, ground page first. */
  proofUrls: string[];
  /** Artboard pages in the supplied master, ground page first. */
  pages: LondonPackPage[];
};

export const LONDON_PACK_ISSUE = {
  id: "2281-pack-2026-09-18",
  issued: "2026-09-18",
  label: "London print pack \u2014 18 September 2026",
  source: "Location team delivery (per-area live files plus copy PDFs)",
} as const;

export const LONDON_PACK_AREAS: LondonPackArea[] = [
  {
    panelId: "ldn-v01",
    kind: "artwork",
    warning: null,
    masterUrl: aV01MasterAi.url,
    masterFilename: "QEII Flag 1.ai",
    printUrl: aV01PrintPdf.url,
    printFilename: "QEII Flag 1 copy.pdf",
    proofUrls: [aV01ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1525.0, hMm: 4165.0 }],
  },
  {
    panelId: "ldn-v52",
    kind: "artwork",
    warning: null,
    masterUrl: aV52MasterAi.url,
    masterFilename: "QEII Flag 2.ai",
    printUrl: aV52PrintPdf.url,
    printFilename: "QEII Flag 2 copy.pdf",
    proofUrls: [aV52ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1525.0, hMm: 4165.0 }],
  },
  {
    panelId: "ldn-v74",
    kind: "artwork",
    warning: null,
    masterUrl: aV61MasterAi.url,
    masterFilename: "QEII Flag 3.ai",
    printUrl: aV61PrintPdf.url,
    printFilename: "QEII Flag 3 copy.pdf",
    proofUrls: [aV61ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1525.0, hMm: 4165.0 }],
  },
  {
    panelId: "ldn-v02",
    kind: "artwork",
    warning: null,
    masterUrl: aV02MasterAi.url,
    masterFilename: "CANOPY BANNER A_25percent of 11775x1350mm.ai",
    printUrl: aV02PrintPdf.url,
    printFilename: "CANOPY BANNER A_25percent of 11775x1350mm copy.pdf",
    proofUrls: [aV02ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 2943.8, hMm: 337.5 }],
  },
  {
    panelId: "ldn-v03",
    kind: "artwork",
    warning: "Artboard is supplied portrait (800 \u00d7 4000mm) while the floor vinyl trims landscape 4000 \u00d7 800mm - rotate on output.",
    masterUrl: aV03MasterAi.url,
    masterFilename: "rdraft-FOYER-FLOOR-VINYL-4000x800mm.ai",
    printUrl: aV03PrintPdf.url,
    printFilename: "rdraft-FOYER-FLOOR-VINYL-4000x800mm copy.pdf",
    proofUrls: [aV03ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 800.0, hMm: 4000.0 }],
  },
  {
    panelId: "ldn-v04",
    kind: "artwork",
    warning: null,
    masterUrl: aV04MasterAi.url,
    masterFilename: "Lifts_Template.ai",
    printUrl: null,
    printFilename: null,
    proofUrls: [aV04ProofP1Jpg.url, aV04ProofP2Jpg.url],
    pages: [{ page: 1, wMm: 1100.0, hMm: 2085.0 }, { page: 2, wMm: 1105.0, hMm: 2070.0 }],
  },
  {
    panelId: "ldn-v05",
    kind: "artwork",
    warning: "Artboard is 1105 \u00d7 2070mm against a 1125 \u00d7 2105mm wall - confirm the bleed with the venue before printing.",
    masterUrl: aV05MasterAi.url,
    masterFilename: "Lifts_Template.ai",
    printUrl: aV05PrintPdf.url,
    printFilename: "Lifts_Template copy.pdf",
    proofUrls: [aV05ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1105.0, hMm: 2070.0 }],
  },
  {
    panelId: "ldn-v06",
    kind: "survey",
    warning: null,
    masterUrl: aV06MasterPdf.url,
    masterFilename: "Cloakroom.pdf",
    printUrl: null,
    printFilename: null,
    proofUrls: [aV06ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 338.6, hMm: 190.5 }],
  },
  {
    panelId: "ldn-v07",
    kind: "survey",
    warning: null,
    masterUrl: aV07MasterPdf.url,
    masterFilename: "REG_DESK_SIZES.pdf",
    printUrl: null,
    printFilename: null,
    proofUrls: [aV07ProofP1Jpg.url, aV07ProofP2Jpg.url, aV07ProofP3Jpg.url, aV07ProofP4Jpg.url],
    pages: [{ page: 1, wMm: 338.7, hMm: 190.5 }, { page: 2, wMm: 338.7, hMm: 190.5 }, { page: 3, wMm: 338.7, hMm: 190.5 }, { page: 4, wMm: 338.7, hMm: 190.5 }],
  },
  {
    panelId: "ldn-v66",
    kind: "artwork",
    warning: null,
    masterUrl: aV53MasterAi.url,
    masterFilename: "REGISTRATION-DESK-VINYL-21-25.ai",
    printUrl: aV53PrintPdf.url,
    printFilename: "REGISTRATION-DESK-VINYL-21-25 copy.pdf",
    proofUrls: [aV53ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 3365.5, hMm: 950.0 }],
  },
  {
    panelId: "ldn-v08",
    kind: "survey",
    warning: null,
    masterUrl: aV08MasterPdf.url,
    masterFilename: "Churchill SI Booths.pdf",
    printUrl: null,
    printFilename: null,
    proofUrls: [aV08ProofP1Jpg.url, aV08ProofP2Jpg.url, aV08ProofP3Jpg.url, aV08ProofP4Jpg.url, aV08ProofP5Jpg.url, aV08ProofP6Jpg.url, aV08ProofP7Jpg.url, aV08ProofP8Jpg.url, aV08ProofP9Jpg.url],
    pages: [{ page: 1, wMm: 338.7, hMm: 190.5 }, { page: 2, wMm: 338.7, hMm: 190.5 }, { page: 3, wMm: 338.7, hMm: 190.5 }, { page: 4, wMm: 338.7, hMm: 190.5 }, { page: 5, wMm: 338.7, hMm: 190.5 }, { page: 6, wMm: 338.7, hMm: 190.5 }, { page: 7, wMm: 338.7, hMm: 190.5 }, { page: 8, wMm: 338.7, hMm: 190.5 }, { page: 9, wMm: 338.7, hMm: 190.5 }],
  },
  {
    panelId: "ldn-v09",
    kind: "artwork",
    warning: null,
    masterUrl: aV09MasterAi.url,
    masterFilename: "rdraft-TABLE-TOP-SQUARE-750x750mm.ai",
    printUrl: null,
    printFilename: null,
    proofUrls: [aV09ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 770.0, hMm: 770.0 }],
  },
  {
    panelId: "ldn-v10",
    kind: "artwork",
    warning: null,
    masterUrl: aV10MasterAi.url,
    masterFilename: "rdraft-TABLE-TOP-ROUND-900mm-DIA.ai",
    printUrl: null,
    printFilename: null,
    proofUrls: [aV10ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 900.0, hMm: 900.0 }],
  },
  {
    panelId: "ldn-v11",
    kind: "artwork",
    warning: null,
    masterUrl: aV11MasterAi.url,
    masterFilename: "rdraft-LOW-CIRCLE-TABLE-TOP-700mm-DIA.ai",
    printUrl: null,
    printFilename: null,
    proofUrls: [aV11ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 720.0, hMm: 720.0 }],
  },
  {
    panelId: "ldn-v12",
    kind: "artwork",
    warning: null,
    masterUrl: aV12MasterAi.url,
    masterFilename: "rdraft-TABLE-TOP-SQUARE-600x600mm.ai",
    printUrl: null,
    printFilename: null,
    proofUrls: [aV12ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 620.0, hMm: 620.0 }],
  },
  {
    panelId: "ldn-v46",
    kind: "artwork",
    warning: null,
    masterUrl: aV46MasterAi.url,
    masterFilename: "Churchill_Double_doors.ai",
    printUrl: aV46PrintPdf.url,
    printFilename: "Churchill_Double_doors copy.pdf",
    proofUrls: [aV46ProofP1Jpg.url, aV46ProofP2Jpg.url],
    pages: [{ page: 1, wMm: 1780.0, hMm: 2200.0 }, { page: 2, wMm: 1780.0, hMm: 2200.0 }],
  },
  {
    panelId: "ldn-v68",
    kind: "artwork",
    warning: null,
    masterUrl: aV55MasterAi.url,
    masterFilename: "Cloakroom-DESK-VINYL-4000mmx950mm.ai",
    printUrl: aV55PrintPdf.url,
    printFilename: "Cloakroom-DESK-VINYL-4000mmx950mm copy.pdf",
    proofUrls: [aV55ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 4000.0, hMm: 950.0 }],
  },
  {
    panelId: "ldn-v69",
    kind: "artwork",
    warning: null,
    masterUrl: aV56MasterAi.url,
    masterFilename: "Cloakroom-side-VINYL-250mmx340mm.ai",
    printUrl: aV56PrintPdf.url,
    printFilename: "Cloakroom-side-VINYL-250mmx340mm copy.pdf",
    proofUrls: [aV56ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 250.0, hMm: 340.0 }],
  },
  {
    panelId: "ldn-v77",
    kind: "artwork",
    warning: null,
    masterUrl: aV64MasterAi.url,
    masterFilename: "Circular Banner.ai",
    printUrl: aV64PrintPdf.url,
    printFilename: "Circular Banner.pdf",
    proofUrls: [aV64ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 4600.0, hMm: 1500.0 }],
  },
  {
    panelId: "ldn-v78",
    kind: "artwork",
    warning: null,
    masterUrl: aV65MasterAi.url,
    masterFilename: "Checkerboard Entrance Tiles.ai",
    printUrl: aV65PrintPdf.url,
    printFilename: "Checkerboard Entrance Tiles copy.pdf",
    proofUrls: [aV65ProofP1Jpg.url, aV65ProofP2Jpg.url, aV65ProofP3Jpg.url, aV65ProofP4Jpg.url, aV65ProofP5Jpg.url, aV65ProofP6Jpg.url, aV65ProofP7Jpg.url, aV65ProofP8Jpg.url, aV65ProofP9Jpg.url, aV65ProofP10Jpg.url, aV65ProofP11Jpg.url, aV65ProofP12Jpg.url, aV65ProofP13Jpg.url],
    pages: [{ page: 1, wMm: 800.0, hMm: 800.0 }, { page: 2, wMm: 800.0, hMm: 800.0 }, { page: 3, wMm: 800.0, hMm: 800.0 }, { page: 4, wMm: 800.0, hMm: 800.0 }, { page: 5, wMm: 800.0, hMm: 800.0 }, { page: 6, wMm: 800.0, hMm: 800.0 }, { page: 7, wMm: 800.0, hMm: 800.0 }, { page: 8, wMm: 800.0, hMm: 800.0 }, { page: 9, wMm: 800.0, hMm: 800.0 }, { page: 10, wMm: 800.0, hMm: 800.0 }, { page: 11, wMm: 800.0, hMm: 800.0 }, { page: 12, wMm: 800.0, hMm: 800.0 }, { page: 13, wMm: 800.0, hMm: 800.0 }],
  },
  {
    panelId: "ldn-v13",
    kind: "artwork",
    warning: null,
    masterUrl: aV13MasterAi.url,
    masterFilename: "Bem Vinyl.ai",
    printUrl: aV13PrintPdf.url,
    printFilename: "Bem Vinyl copy.pdf",
    proofUrls: [aV13ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 4750.0, hMm: 850.0 }],
  },
  {
    panelId: "ldn-v14",
    kind: "artwork",
    warning: null,
    masterUrl: aV14MasterAi.url,
    masterFilename: "Redgrave Wall 2A.ai",
    printUrl: aV14PrintPdf.url,
    printFilename: "Redgrave Wall 2A copy.pdf",
    proofUrls: [aV14ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 767.0, hMm: 257.0 }],
  },
  {
    panelId: "ldn-v15",
    kind: "artwork",
    warning: null,
    masterUrl: aV15MasterAi.url,
    masterFilename: "Burton_door.ai",
    printUrl: aV15PrintPdf.url,
    printFilename: "Burton_door.pdf",
    proofUrls: [aV15ProofP1Jpg.url, aV15ProofP2Jpg.url],
    pages: [{ page: 1, wMm: 930.0, hMm: 2001.0 }, { page: 2, wMm: 930.0, hMm: 2001.0 }],
  },
  {
    panelId: "ldn-v16",
    kind: "artwork",
    warning: null,
    masterUrl: aV16MasterAi.url,
    masterFilename: "Albert.ai",
    printUrl: aV16PrintPdf.url,
    printFilename: "Albert copy.pdf",
    proofUrls: [aV16ProofP1Jpg.url, aV16ProofP2Jpg.url],
    pages: [{ page: 1, wMm: 840.0, hMm: 2000.0 }, { page: 2, wMm: 840.0, hMm: 2000.0 }],
  },
  {
    panelId: "ldn-v17",
    kind: "artwork",
    warning: null,
    masterUrl: aV17MasterAi.url,
    masterFilename: "VICTORIA.ai",
    printUrl: aV17PrintPdf.url,
    printFilename: "VICTORIA.pdf",
    proofUrls: [aV17ProofP1Jpg.url, aV17ProofP2Jpg.url],
    pages: [{ page: 1, wMm: 840.0, hMm: 2000.0 }, { page: 2, wMm: 840.0, hMm: 2000.0 }],
  },
  {
    panelId: "ldn-v18",
    kind: "artwork",
    warning: null,
    masterUrl: aV18MasterAi.url,
    masterFilename: "GIELGUD.ai",
    printUrl: aV18PrintPdf.url,
    printFilename: "GIELGUD copy.pdf",
    proofUrls: [aV18ProofP1Jpg.url, aV18ProofP2Jpg.url],
    pages: [{ page: 1, wMm: 840.0, hMm: 2000.0 }, { page: 2, wMm: 840.0, hMm: 2000.0 }],
  },
  {
    panelId: "ldn-v19",
    kind: "artwork",
    warning: null,
    masterUrl: aV19MasterAi.url,
    masterFilename: "@50%_PAOLOZZI-COVER-4500x6500mm.ai",
    printUrl: aV19PrintPdf.url,
    printFilename: "@50%_PAOLOZZI-COVER-4500x6500mm copy.pdf",
    proofUrls: [aV19ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 2250.0, hMm: 3250.0 }],
  },
  {
    panelId: "ldn-v20",
    kind: "template",
    warning: null,
    masterUrl: aV20MasterAi.url,
    masterFilename: "Template_for_Balcony_Full.ai",
    printUrl: null,
    printFilename: null,
    proofUrls: [aV20ProofP1Jpg.url, aV20ProofP2Jpg.url, aV20ProofP3Jpg.url, aV20ProofP4Jpg.url, aV20ProofP5Jpg.url, aV20ProofP6Jpg.url],
    pages: [{ page: 1, wMm: 31.0, hMm: 212.0 }, { page: 2, wMm: 156.2, hMm: 212.0 }, { page: 3, wMm: 380.0, hMm: 212.0 }, { page: 4, wMm: 1336.0, hMm: 155.0 }, { page: 5, wMm: 354.0, hMm: 212.0 }, { page: 6, wMm: 135.0, hMm: 212.0 }],
  },
  {
    panelId: "ldn-v21",
    kind: "artwork",
    warning: null,
    masterUrl: aV21MasterAi.url,
    masterFilename: "Fleming and Whittle doors.ai",
    printUrl: aV21PrintPdf.url,
    printFilename: "Fleming and Whittle doors copy.pdf",
    proofUrls: [aV21ProofP1Jpg.url, aV21ProofP2Jpg.url],
    pages: [{ page: 1, wMm: 1500.0, hMm: 1500.0 }, { page: 2, wMm: 1500.0, hMm: 1500.0 }],
  },
  {
    panelId: "ldn-v22",
    kind: "artwork",
    warning: null,
    masterUrl: aV22MasterAi.url,
    masterFilename: "Fleming and Whittle doors.ai",
    printUrl: aV22PrintPdf.url,
    printFilename: "Fleming and Whittle doors copy.pdf",
    proofUrls: [aV22ProofP2Jpg.url, aV22ProofP1Jpg.url],
    pages: [{ page: 2, wMm: 1500.0, hMm: 1500.0 }, { page: 1, wMm: 1500.0, hMm: 1500.0 }],
  },
  {
    panelId: "ldn-v75",
    kind: "artwork",
    warning: null,
    masterUrl: aV62MasterAi.url,
    masterFilename: "catering_table_front_cover.ai",
    printUrl: aV62PrintPdf.url,
    printFilename: "catering_table_front_cover copy.pdf",
    proofUrls: [aV62ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1570.0, hMm: 920.0 }],
  },
  {
    panelId: "ldn-v76",
    kind: "artwork",
    warning: null,
    masterUrl: aV63MasterAi.url,
    masterFilename: "Metal cover 3F 10th scale.ai",
    printUrl: aV63PrintPdf.url,
    printFilename: "Metal cover 3F 10th scale.pdf",
    proofUrls: [aV63ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 700.0, hMm: 423.0 }],
  },
  {
    panelId: "ldn-v25",
    kind: "artwork",
    warning: null,
    masterUrl: aV25MasterAi.url,
    masterFilename: "Westminster_door_A_copy.ai",
    printUrl: null,
    printFilename: null,
    proofUrls: [aV25ProofP1Jpg.url, aV25ProofP2Jpg.url],
    pages: [{ page: 1, wMm: 900.0, hMm: 2000.0 }, { page: 2, wMm: 440.0, hMm: 2000.0 }],
  },
  {
    panelId: "ldn-v26",
    kind: "artwork",
    warning: null,
    masterUrl: aV26MasterAi.url,
    masterFilename: "Westminster__Corridoor_1.ai",
    printUrl: aV26PrintPdf.url,
    printFilename: "Westminster__Corridoor_1 copy.pdf",
    proofUrls: [aV26ProofP1Jpg.url, aV26ProofP2Jpg.url],
    pages: [{ page: 1, wMm: 900.0, hMm: 2020.0 }, { page: 2, wMm: 900.0, hMm: 2020.0 }],
  },
  {
    panelId: "ldn-v27",
    kind: "artwork",
    warning: null,
    masterUrl: aV27MasterAi.url,
    masterFilename: "St_James_door.ai",
    printUrl: aV27PrintPdf.url,
    printFilename: "St_James_door copy.pdf",
    proofUrls: [aV27ProofP1Jpg.url, aV27ProofP2Jpg.url],
    pages: [{ page: 1, wMm: 900.0, hMm: 2020.0 }, { page: 2, wMm: 420.0, hMm: 2020.0 }],
  },
  {
    panelId: "ldn-v28",
    kind: "artwork",
    warning: null,
    masterUrl: aV28MasterAi.url,
    masterFilename: "Abbey_doors.ai",
    printUrl: aV28PrintPdf.url,
    printFilename: "Abbey_doors copy.pdf",
    proofUrls: [aV28ProofP1Jpg.url, aV28ProofP2Jpg.url, aV28ProofP3Jpg.url],
    pages: [{ page: 1, wMm: 920.0, hMm: 2020.0 }, { page: 2, wMm: 380.0, hMm: 2020.0 }, { page: 3, wMm: 920.0, hMm: 2020.0 }],
  },
  {
    panelId: "ldn-v29",
    kind: "artwork",
    warning: null,
    masterUrl: aV29MasterAi.url,
    masterFilename: "Wordsworth_door.ai",
    printUrl: aV29PrintPdf.url,
    printFilename: "Wordsworth_door.pdf",
    proofUrls: [aV29ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 920.0, hMm: 2020.0 }],
  },
  {
    panelId: "ldn-v30",
    kind: "artwork",
    warning: null,
    masterUrl: aV30MasterAi.url,
    masterFilename: "PILLAR-WRAP-ST-JAMES-620x2500mm.ai",
    printUrl: aV30PrintPdf.url,
    printFilename: "PILLAR-WRAP-ST-JAMES-620x2500mm copy.pdf",
    proofUrls: [aV30ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 630.0, hMm: 2510.0 }],
  },
  {
    panelId: "ldn-v31",
    kind: "artwork",
    warning: null,
    masterUrl: aV31MasterAi.url,
    masterFilename: "PILLAR-WRAP-Westminster-620x2500mm.ai",
    printUrl: aV31PrintPdf.url,
    printFilename: "PILLAR-WRAP-Westminster-620x2500mm copy.pdf",
    proofUrls: [aV31ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 630.0, hMm: 2510.0 }],
  },
  {
    panelId: "ldn-v32",
    kind: "artwork",
    warning: null,
    masterUrl: aV32MasterAi.url,
    masterFilename: "Wall 4E 2590x2110.ai",
    printUrl: aV32PrintPdf.url,
    printFilename: "Wall 4E 2590x2110 copy.pdf",
    proofUrls: [aV32ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 2590.0, hMm: 2110.0 }],
  },
  {
    panelId: "ldn-v33",
    kind: "template",
    warning: null,
    masterUrl: aV33MasterAi.url,
    masterFilename: "QEII-SquarePillarWraps-2500H_floor_5.ai",
    printUrl: aV33PrintPdf.url,
    printFilename: "QEII-SquarePillarWraps-2500H_floor_5.pdf",
    proofUrls: [aV33ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 647.5, hMm: 337.2 }],
  },
  {
    panelId: "ldn-v34",
    kind: "artwork",
    warning: null,
    masterUrl: aV34MasterAi.url,
    masterFilename: "Glass panel 1 (2).ai",
    printUrl: aV34PrintPdf.url,
    printFilename: "Glass panel 1 (2) copy.pdf",
    proofUrls: [aV34ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1244.0, hMm: 1600.0 }],
  },
  {
    panelId: "ldn-v35",
    kind: "artwork",
    warning: null,
    masterUrl: aV35MasterAi.url,
    masterFilename: "Glass panel 2.ai",
    printUrl: aV35PrintPdf.url,
    printFilename: "Glass panel 2 copy.pdf",
    proofUrls: [aV35ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1244.0, hMm: 1600.0 }],
  },
  {
    panelId: "ldn-v36",
    kind: "artwork",
    warning: null,
    masterUrl: aV36MasterAi.url,
    masterFilename: "Glass panel 3.ai",
    printUrl: aV36PrintPdf.url,
    printFilename: "Glass panel 3 copy.pdf",
    proofUrls: [aV36ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1224.0, hMm: 1315.0 }],
  },
  {
    panelId: "ldn-v37",
    kind: "artwork",
    warning: "Artboard is 2590 \u00d7 2110mm, copied from the Wall 4E sheet; the 870 \u00d7 320mm fascia trim is only correct in the supplied print PDF. Print the PDF, not the artboard.",
    masterUrl: aV37MasterAi.url,
    masterFilename: "V2_rdraft-WINDSOR-FASCIA-870x320mm.ai",
    printUrl: aV37PrintPdf.url,
    printFilename: "rdraft-WINDSOR-FASCIA-870x320mm-print.pdf",
    proofUrls: [aV37ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 2590.0, hMm: 2110.0 }],
  },
  {
    panelId: "ldn-v40",
    kind: "artwork",
    warning: null,
    masterUrl: aV40MasterAi.url,
    masterFilename: "Mountbatten 6a.ai",
    printUrl: aV40PrintPdf.url,
    printFilename: "Mountbatten 6a copy.pdf",
    proofUrls: [aV40ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 4940.0, hMm: 2030.0 }],
  },
  {
    panelId: "ldn-v41",
    kind: "template",
    warning: null,
    masterUrl: aV41MasterAi.url,
    masterFilename: "Mountbatten_Set_Wrap_Template.ai",
    printUrl: aV41PrintPdf.url,
    printFilename: "Mountbatten_Set_Wrap_Template copy.pdf",
    proofUrls: [aV41ProofP1Jpg.url, aV41ProofP2Jpg.url, aV41ProofP3Jpg.url],
    pages: [{ page: 1, wMm: 350.0, hMm: 431.4 }, { page: 2, wMm: 350.0, hMm: 431.4 }, { page: 3, wMm: 990.0, hMm: 431.4 }],
  },
  {
    panelId: "ldn-v81",
    kind: "artwork",
    warning: null,
    masterUrl: aLiftStepintoMasterAi.url,
    masterFilename: "Lifts_Template_StepInto.ai",
    printUrl: aLiftStepintoPrintPdf.url,
    printFilename: "Lifts_Template_StepInto.pdf",
    proofUrls: [aLiftStepintoProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1100.0, hMm: 2085.0 }],
  },
  {
    panelId: "ldn-v82",
    kind: "artwork",
    warning: null,
    masterUrl: aLiftLiftyourMasterAi.url,
    masterFilename: "Lifts_Template_LiftYour.ai",
    printUrl: aLiftLiftyourPrintPdf.url,
    printFilename: "Lifts_Template_LiftYour.pdf",
    proofUrls: [aLiftLiftyourProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1100.0, hMm: 2085.0 }],
  },
  {
    panelId: "ldn-v83",
    kind: "artwork",
    warning: null,
    masterUrl: aLiftThinkbiggerMasterAi.url,
    masterFilename: "Lifts_Template_ThinkBigger.ai",
    printUrl: aLiftThinkbiggerPrintPdf.url,
    printFilename: "Lifts_Template_ThinkBigger.pdf",
    proofUrls: [aLiftThinkbiggerProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1100.0, hMm: 2085.0 }],
  },
  {
    panelId: "ldn-v84",
    kind: "artwork",
    warning: null,
    masterUrl: aLiftWhereideasMasterAi.url,
    masterFilename: "Lifts_Template_WhereIdeas.ai",
    printUrl: aLiftWhereideasPrintPdf.url,
    printFilename: "Lifts_Template_WhereIdeas.pdf",
    proofUrls: [aLiftWhereideasProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1100.0, hMm: 2085.0 }],
  },
  {
    panelId: "ldn-v85",
    kind: "artwork",
    warning: null,
    masterUrl: aLiftElevateMasterAi.url,
    masterFilename: "Lifts_Template_YElevateYour.ai",
    printUrl: aLiftElevatePrintPdf.url,
    printFilename: "Lifts_Template_YElevateYour.pdf",
    proofUrls: [aLiftElevateProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1100.0, hMm: 2085.0 }],
  },
  {
    panelId: "ldn-v86",
    kind: "artwork",
    warning: null,
    masterUrl: aLiftCantspellMasterAi.url,
    masterFilename: "Lifts_Template_YouCantSpell.ai",
    printUrl: aLiftCantspellPrintPdf.url,
    printFilename: "Lifts_Template_YouCantSpell.pdf",
    proofUrls: [aLiftCantspellProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1100.0, hMm: 2085.0 }],
  },
  {
    panelId: "ldn-v53",
    kind: "artwork",
    warning: null,
    masterUrl: aGlass1MasterAi.url,
    masterFilename: "Churchill_Glass Vinyl 1.ai",
    printUrl: aGlass1PrintPdf.url,
    printFilename: "Churchill_Glass Vinyl 1 copy.pdf",
    proofUrls: [aGlass1ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1300.0, hMm: 1230.0 }],
  },
  {
    panelId: "ldn-v54",
    kind: "artwork",
    warning: null,
    masterUrl: aGlass2MasterAi.url,
    masterFilename: "Churchill_Glass Vinyl 2 @50%.ai",
    printUrl: aGlass2PrintPdf.url,
    printFilename: "Churchill_Glass Vinyl 2 @50%.pdf",
    proofUrls: [aGlass2ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 3500.0, hMm: 615.0 }],
  },
  {
    panelId: "ldn-v55",
    kind: "artwork",
    warning: null,
    masterUrl: aGlass3MasterAi.url,
    masterFilename: "Churchill_Glass Vinyl 3.ai",
    printUrl: aGlass3PrintPdf.url,
    printFilename: "Churchill_Glass Vinyl 3 copy.pdf",
    proofUrls: [aGlass3ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1300.0, hMm: 1230.0 }],
  },
  {
    panelId: "ldn-v56",
    kind: "artwork",
    warning: null,
    masterUrl: aGlass4MasterAi.url,
    masterFilename: "Churchill_Glass Vinyl 4.ai",
    printUrl: aGlass4PrintPdf.url,
    printFilename: "Churchill_Glass Vinyl 4 copy.pdf",
    proofUrls: [aGlass4ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1300.0, hMm: 1230.0 }],
  },
  {
    panelId: "ldn-v57",
    kind: "artwork",
    warning: null,
    masterUrl: aGlass5MasterAi.url,
    masterFilename: "Churchill_Glass Vinyl 5 @50%.ai",
    printUrl: aGlass5PrintPdf.url,
    printFilename: "Churchill_Glass Vinyl 5 @50% copy.pdf",
    proofUrls: [aGlass5ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 3500.0, hMm: 615.0 }],
  },
  {
    panelId: "ldn-v58",
    kind: "artwork",
    warning: null,
    masterUrl: aGlass6MasterAi.url,
    masterFilename: "Churchill_Glass Vinyl 6.ai",
    printUrl: aGlass6PrintPdf.url,
    printFilename: "Churchill_Glass Vinyl 6 copy.pdf",
    proofUrls: [aGlass6ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1300.0, hMm: 1230.0 }],
  },
  {
    panelId: "ldn-v59",
    kind: "artwork",
    warning: null,
    masterUrl: aGlass7MasterAi.url,
    masterFilename: "Churchill_Glass Vinyl 7.ai",
    printUrl: aGlass7PrintPdf.url,
    printFilename: "Churchill_Glass Vinyl 7 copy.pdf",
    proofUrls: [aGlass7ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1300.0, hMm: 1230.0 }],
  },
  {
    panelId: "ldn-v60",
    kind: "artwork",
    warning: null,
    masterUrl: aGlass8MasterAi.url,
    masterFilename: "Churchill_Glass Vinyl 8 @50%.ai",
    printUrl: aGlass8PrintAi.url,
    printFilename: "Churchill_Glass Vinyl 8 @50%.ai",
    proofUrls: [aGlass8ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 3500.0, hMm: 615.0 }],
  },
  {
    panelId: "ldn-v61",
    kind: "artwork",
    warning: null,
    masterUrl: aGlass9MasterAi.url,
    masterFilename: "Churchill_Glass Vinyl 9.ai",
    printUrl: aGlass9PrintPdf.url,
    printFilename: "Churchill_Glass Vinyl 9 copy.pdf",
    proofUrls: [aGlass9ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 1300.0, hMm: 1230.0 }],
  },
  {
    panelId: "ldn-v79",
    kind: "artwork",
    warning: null,
    masterUrl: aRegSideLeftMasterAi.url,
    masterFilename: "REGISTRATION-DESK-SIDE_Left-VINYL-900mmx950mm.ai",
    printUrl: aRegSideLeftPrintPdf.url,
    printFilename: "REGISTRATION-DESK-SIDE_Left-VINYL-900mmx950mm copy.pdf",
    proofUrls: [aRegSideLeftProofP1Jpg.url],
    pages: [{ page: 1, wMm: 900.0, hMm: 950.0 }],
  },
  {
    panelId: "ldn-v80",
    kind: "artwork",
    warning: null,
    masterUrl: aRegSideRightMasterAi.url,
    masterFilename: "REGISTRATION-DESK-SIDE_Right-VINYL-900mmx950mm.ai",
    printUrl: aRegSideRightPrintPdf.url,
    printFilename: "REGISTRATION-DESK-SIDE_Right-VINYL-900mmx950mm copy.pdf",
    proofUrls: [aRegSideRightProofP1Jpg.url],
    pages: [{ page: 1, wMm: 900.0, hMm: 950.0 }],
  },
  {
    panelId: "ldn-v62",
    kind: "artwork",
    warning: null,
    masterUrl: aReg4155MasterAi.url,
    masterFilename: "REGISTRATION-DESK-VINYL-4155mmx950mm.ai",
    printUrl: aReg4155PrintPdf.url,
    printFilename: "REGISTRATION-DESK-VINYL-4155mmx950mm copy.pdf",
    proofUrls: [aReg4155ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 4155.0, hMm: 950.0 }],
  },
  {
    panelId: "ldn-v63",
    kind: "artwork",
    warning: null,
    masterUrl: aReg4155MasterAi.url,
    masterFilename: "REGISTRATION-DESK-VINYL-4155mmx950mm.ai",
    printUrl: aReg4155PrintPdf.url,
    printFilename: "REGISTRATION-DESK-VINYL-4155mmx950mm copy.pdf",
    proofUrls: [aReg4155ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 4155.0, hMm: 950.0 }],
  },
  {
    panelId: "ldn-v64",
    kind: "artwork",
    warning: null,
    masterUrl: aReg4155MasterAi.url,
    masterFilename: "REGISTRATION-DESK-VINYL-4155mmx950mm.ai",
    printUrl: aReg4155PrintPdf.url,
    printFilename: "REGISTRATION-DESK-VINYL-4155mmx950mm copy.pdf",
    proofUrls: [aReg4155ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 4155.0, hMm: 950.0 }],
  },
  {
    panelId: "ldn-v65",
    kind: "artwork",
    warning: null,
    masterUrl: aReg4155MasterAi.url,
    masterFilename: "REGISTRATION-DESK-VINYL-4155mmx950mm.ai",
    printUrl: aReg4155PrintPdf.url,
    printFilename: "REGISTRATION-DESK-VINYL-4155mmx950mm copy.pdf",
    proofUrls: [aReg4155ProofP1Jpg.url],
    pages: [{ page: 1, wMm: 4155.0, hMm: 950.0 }],
  },
  {
    panelId: "ldn-v87",
    kind: "template",
    warning: null,
    masterUrl: aPaolozziSetwrapMasterAi.url,
    masterFilename: "Paolozzi Set Wrap Template (1).ai",
    printUrl: aPaolozziSetwrapPrintPdf.url,
    printFilename: "Paolozzi Set Wrap Template (1) copy.pdf",
    proofUrls: [aPaolozziSetwrapProofP1Jpg.url, aPaolozziSetwrapProofP2Jpg.url, aPaolozziSetwrapProofP3Jpg.url],
    pages: [{ page: 1, wMm: 120.0, hMm: 470.0 }, { page: 2, wMm: 670.0, hMm: 470.0 }, { page: 3, wMm: 120.0, hMm: 470.0 }],
  },
];

const BY_PANEL = new Map(LONDON_PACK_AREAS.map((a) => [a.panelId, a] as const));

/** The supplied live file for a print area, from the pack in force. */
export function londonPackArea(panelId: string): LondonPackArea | null {
  return BY_PANEL.get(panelId) ?? null;
}

/** True when this area is covered by finished artwork in the supplied pack. */
export function isLondonPackArea(panelId: string): boolean {
  return BY_PANEL.get(panelId)?.kind === "artwork";
}

/** Finished artwork for an area - null for a survey or template sheet. */
export function londonPackArtwork(panelId: string): LondonPackArea | null {
  const area = BY_PANEL.get(panelId);
  return area && area.kind === "artwork" ? area : null;
}

/** Reference sheet (site survey or cut template) supplied for an area. */
export function londonPackReference(panelId: string): LondonPackArea | null {
  const area = BY_PANEL.get(panelId);
  return area && area.kind !== "artwork" ? area : null;
}

/**
 * How the supplied artboard relates to the area trim. A master supplied at 50%
 * or 1:10 is correct for print - the vendor scales it - but it must never be
 * reported as a full-size sheet.
 */
export function londonPackScale(
  panelId: string,
  trimW: number,
  trimH: number,
): { ratio: number; label: string } | null {
  const area = BY_PANEL.get(panelId);
  const first = area?.pages[0];
  if (!area || !first || !trimW || !trimH) return null;
  const long = Math.max(first.wMm, first.hMm) / Math.max(trimW, trimH);
  const ratio = Math.round(long * 1000) / 1000;
  if (ratio > 0.92) return { ratio, label: "Supplied full size" };
  const denom = Math.max(2, Math.round(1 / ratio));
  return { ratio, label: `Supplied at 1:${denom} (${Math.round(ratio * 100)}% of trim)` };
}

/** Artboard pages in the supplied master - leaves, tile variants, template parts. */
export function londonPackPageCount(panelId: string): number {
  return BY_PANEL.get(panelId)?.pages.length ?? 0;
}
