// Client side of the export validation gate: build the expected manifest from
// the deck we just exported, then hand the generated bytes to the server for
// verification. The download is only enabled once the server says the package
// really contains the deck.
import type { Deck } from "./deck-store";
import { collectStrings } from "./reinterpret-design";
import type { ExpectedManifest, ExpectedSlide, PptxValidationReport } from "./pptx-validate";
import { readExportFidelity } from "./export-quality";

/** Longest, most distinctive copy fragments on a slide — good identity probes. */
function slideProbes(content: unknown): string[] {
  const strings = collectStrings(content)
    .map((s) => s.replace(/\s+/g, " ").trim())
    .filter((s) => s.length >= 8 && s.length <= 160);
  const unique = Array.from(new Set(strings));
  unique.sort((a, b) => b.length - a.length);
  return unique.slice(0, 3);
}

/** Media references we can already see in the deck content (images, plates). */
function countMediaHints(deck: Deck): number {
  let n = 0;
  const walk = (value: unknown) => {
    if (typeof value === "string") {
      if (
        /^(https?:|data:image\/|\/)/.test(value) &&
        /\.(png|jpe?g|webp|svg)|data:image\//i.test(value)
      ) {
        n += 1;
      }
      return;
    }
    if (Array.isArray(value)) {
      for (const v of value) walk(v);
      return;
    }
    if (value && typeof value === "object") {
      for (const v of Object.values(value as Record<string, unknown>)) walk(v);
    }
  };
  walk(deck.slides.map((s) => s.content));
  return n;
}

export function buildExportManifest(deck: Deck): ExpectedManifest {
  const fidelity = readExportFidelity();
  const slides: ExpectedSlide[] = deck.slides.map((s) => ({
    slideId: s.id,
    variantId: s.variantId,
    probes: slideProbes(s.content),
  }));
  return {
    slideCount: deck.slides.length,
    slides,
    // Conservative floor: a brand lockup/plate always lands, plus anything the
    // deck content itself points at.
    minMedia: deck.slides.length > 0 ? Math.min(countMediaHints(deck), 1) : 0,
    expectTextRuns: fidelity !== "exact",
  };
}

export async function validateExportedPptx(
  blob: Blob,
  manifest: ExpectedManifest,
): Promise<PptxValidationReport> {
  const form = new FormData();
  form.append("file", blob, "deck.pptx");
  form.append("manifest", JSON.stringify(manifest));
  const res = await fetch("/api/deck-export-validate", { method: "POST", body: form });
  if (!res.ok) {
    let detail = `HTTP ${res.status}`;
    try {
      const body = (await res.json()) as { error?: string };
      if (body?.error) detail = body.error;
    } catch {
      /* non-JSON error body */
    }
    throw new Error(detail);
  }
  return (await res.json()) as PptxValidationReport;
}
