// TransPerfect Modular System — taxonomy seed
// Derived from: Master Template Framework v0.2 + Master Wireframe Atlas v0.1.
// This is the source of truth until Lovable Cloud is enabled and these move to
// database tables. Shape mirrors the planned schema so migration is a copy.

export type BrandMode = {
  id: string;
  name: string;
  description: string;
  tokens: { primary: string; accent: string; surface: string; ink: string };
};

export type SectionFramework = {
  id: string; // SF-XX
  name: string;
  purpose: string;
  permittedFamilyIds: string[]; // MF-XX
};

export type ModuleFamily = {
  id: string; // MF-XX
  name: string;
  reviewLevel: "light" | "standard" | "strict";
  description: string;
};

export type LayoutFramework = {
  id: string; // LF-XX
  name: string;
  description: string;
  // Zones are declarative — the renderer maps zone names to grid regions.
  zones: string[];
};

export type ModuleVariant = {
  id: string; // MV-XX
  familyId: string;
  name: string;
  description: string;
  permittedLayoutIds: string[];
  capacity: {
    items?: { min: number; max: number };
    titleChars?: number;
    bodyChars?: number;
  };
  fallbackVariantId?: string;
  editableFields: string[];
  lockedFields: string[];
};

export type NarrativeArchetype = {
  id: string;
  name: string;
  description: string;
  sectionRecipe: string[]; // ordered SF ids
};

// ────────────────────────────────────────────────────────────────────────────
// Brand modes
// ────────────────────────────────────────────────────────────────────────────
export const BRAND_MODES: BrandMode[] = [
  {
    id: "bm-enterprise",
    name: "Enterprise",
    description: "TransPerfect master brand",
    tokens: { primary: "#0B2A4A", accent: "#E85A2C", surface: "#F5F1EA", ink: "#0A0F1C" },
  },
  {
    id: "bm-subcompany",
    name: "Subcompany",
    description: "Named subcompany within TransPerfect",
    tokens: { primary: "#1F3A6B", accent: "#E85A2C", surface: "#F5F1EA", ink: "#0A0F1C" },
  },
  {
    id: "bm-division",
    name: "Division",
    description: "Business division brand mode",
    tokens: { primary: "#284B63", accent: "#F2A65A", surface: "#F5F1EA", ink: "#0A0F1C" },
  },
  {
    id: "bm-product",
    name: "Product",
    description: "Named product brand mode",
    tokens: { primary: "#111827", accent: "#22C1C3", surface: "#F5F1EA", ink: "#0A0F1C" },
  },
  {
    id: "bm-cobrand",
    name: "Co-brand",
    description: "Co-branded with client or partner",
    tokens: { primary: "#0B2A4A", accent: "#8E44AD", surface: "#F5F1EA", ink: "#0A0F1C" },
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Section Frameworks (SF-01..SF-16, Atlas Part 02)
// ────────────────────────────────────────────────────────────────────────────
export const SECTION_FRAMEWORKS: SectionFramework[] = [
  { id: "SF-01", name: "Opening & Orientation", purpose: "Set up who, what, why now", permittedFamilyIds: ["MF-01"] },
  { id: "SF-02", name: "Audience Framing", purpose: "Anchor the audience POV", permittedFamilyIds: ["MF-01", "MF-02"] },
  { id: "SF-03", name: "Client / Market Context", purpose: "Situate the client in the market", permittedFamilyIds: ["MF-02"] },
  { id: "SF-04", name: "Challenge & Cost of Inaction", purpose: "Frame the problem and its cost", permittedFamilyIds: ["MF-02"] },
  { id: "SF-05", name: "Insight & Opportunity", purpose: "Reveal the leverage point", permittedFamilyIds: ["MF-03"] },
  { id: "SF-06", name: "Solution Overview", purpose: "Introduce the recommended solution", permittedFamilyIds: ["MF-04"] },
  { id: "SF-07", name: "Solution Detail", purpose: "Explain how the solution works", permittedFamilyIds: ["MF-04", "MF-05"] },
  { id: "SF-08", name: "Proof & Evidence", purpose: "Substantiate with data + logos", permittedFamilyIds: ["MF-05"] },
  { id: "SF-09", name: "Case Study", purpose: "Show a comparable win", permittedFamilyIds: ["MF-06"] },
  { id: "SF-10", name: "Process & Journey", purpose: "Sequence the engagement", permittedFamilyIds: ["MF-04"] },
  { id: "SF-11", name: "Comparison & Decision", purpose: "Support the decision", permittedFamilyIds: ["MF-05"] },
  { id: "SF-12", name: "Team & Governance", purpose: "Introduce team + oversight", permittedFamilyIds: ["MF-07"] },
  { id: "SF-13", name: "Commercials", purpose: "Pricing + commercial model", permittedFamilyIds: ["MF-05"] },
  { id: "SF-14", name: "Risk & Mitigation", purpose: "Name and address risk", permittedFamilyIds: ["MF-05"] },
  { id: "SF-15", name: "Recommendation & Next Steps", purpose: "Ask for the decision", permittedFamilyIds: ["MF-07"] },
  { id: "SF-16", name: "Close & CTA", purpose: "Wrap and hand off", permittedFamilyIds: ["MF-07"] },
];

// ────────────────────────────────────────────────────────────────────────────
// Module Families (Framework Sections 11–19, expanded 33–39)
// ────────────────────────────────────────────────────────────────────────────
export const MODULE_FAMILIES: ModuleFamily[] = [
  { id: "MF-01", name: "Opening & Orientation", reviewLevel: "light", description: "Covers, agenda, section dividers" },
  { id: "MF-02", name: "Context & Challenge", reviewLevel: "standard", description: "Market context, challenge cards, cost of inaction" },
  { id: "MF-03", name: "Insight & Opportunity", reviewLevel: "standard", description: "Insight callouts, opportunity sizing" },
  { id: "MF-04", name: "Solution & Process", reviewLevel: "standard", description: "Solution pillars, process, journey" },
  { id: "MF-05", name: "Proof, Data & Decision", reviewLevel: "strict", description: "Proof points, data, comparison, commercials, risk" },
  { id: "MF-06", name: "Case Study", reviewLevel: "strict", description: "Case study modules" },
  { id: "MF-07", name: "Team, Governance & Close", reviewLevel: "standard", description: "Team, governance, recommendation, close" },
];

// ────────────────────────────────────────────────────────────────────────────
// Layout Frameworks (Atlas Section 35, LF-01..LF-24). MVP subset with full metadata.
// ────────────────────────────────────────────────────────────────────────────
export const LAYOUT_FRAMEWORKS: LayoutFramework[] = [
  { id: "LF-01", name: "Single focus", description: "One dominant zone, centered", zones: ["focus"] },
  { id: "LF-02", name: "Title + support", description: "Prominent title with supporting body", zones: ["title", "support"] },
  { id: "LF-03", name: "Left copy / right media", description: "Copy left, image or chart right", zones: ["copy", "media"] },
  { id: "LF-04", name: "Two-column parallel", description: "Two equal columns", zones: ["colA", "colB"] },
  { id: "LF-05", name: "Full-bleed media", description: "Edge-to-edge visual with overlay text", zones: ["media", "overlay"] },
  { id: "LF-06", name: "Header + body", description: "Standard headline over body copy", zones: ["header", "body"] },
  { id: "LF-07", name: "Stat + narrative", description: "Large stat callout with narrative", zones: ["stat", "narrative"] },
  { id: "LF-08", name: "Three-column parallel", description: "Three equal columns, comparable density", zones: ["col1", "col2", "col3"] },
  { id: "LF-09", name: "Asymmetric mosaic", description: "Anchor tile plus supporting tiles", zones: ["anchor", "tileA", "tileB", "tileC"] },
  { id: "LF-10", name: "Four-tile grid", description: "2×2 grid of equal tiles", zones: ["a", "b", "c", "d"] },
  { id: "LF-11", name: "Six-tile grid", description: "3×2 grid of equal tiles", zones: ["a", "b", "c", "d", "e", "f"] },
  { id: "LF-12", name: "Five-tile grid", description: "One hero tile with four supporting", zones: ["hero", "a", "b", "c", "d"] },
  { id: "LF-13", name: "Vertical numbered list", description: "Numbered rows down the page", zones: ["title", "rows"] },
  { id: "LF-14", name: "Timeline", description: "Horizontal sequence of steps", zones: ["title", "steps"] },
  { id: "LF-15", name: "Before / after split", description: "Two states side by side", zones: ["before", "after"] },
  { id: "LF-16", name: "Matrix / quadrant", description: "2×2 matrix with axis labels", zones: ["axisX", "axisY", "q1", "q2", "q3", "q4"] },
  { id: "LF-17", name: "Comparison table", description: "Rows of criteria across columns of options", zones: ["title", "columns", "rows"] },
  { id: "LF-18", name: "Case study spread", description: "Client / challenge / solution / result", zones: ["client", "challenge", "solution", "result"] },
  { id: "LF-19", name: "Logo wall", description: "Grid of client / partner logos", zones: ["title", "logos"] },
  { id: "LF-20", name: "Quote focus", description: "Large quote with attribution", zones: ["quote", "attribution"] },
  { id: "LF-21", name: "Team grid", description: "People cards with headshot / name / role", zones: ["title", "people"] },
  { id: "LF-22", name: "Layered architecture", description: "Stacked layers with labels", zones: ["title", "layers"] },
  { id: "LF-23", name: "Pricing tiers", description: "Parallel plan / package columns", zones: ["title", "tiers"] },
  { id: "LF-24", name: "Closing / CTA", description: "Sign-off with next steps", zones: ["message", "cta"] },
  { id: "LF-25", name: "Editorial spread", description: "Magazine-style asymmetric type + media", zones: ["type", "media", "kicker"] },
  { id: "LF-26", name: "Media gallery", description: "Grid of captioned media tiles", zones: ["title", "tiles"] },
  { id: "LF-27", name: "Portrait feature", description: "Full-height portrait with narrative panel", zones: ["portrait", "narrative"] },
  { id: "LF-28", name: "Poster type", description: "Poster-scale type block on solid field", zones: ["kicker", "type", "meta"] },
  { id: "LF-29", name: "Framed media", description: "Centered framed media with caption", zones: ["media", "caption"] },
  { id: "LF-30", name: "Media strip", description: "Horizontal filmstrip of media", zones: ["title", "strip"] },
  { id: "LF-31", name: "Donut infographic", description: "Donut / pie chart with center callout and legend", zones: ["chart", "legend", "callout"] },
  { id: "LF-32", name: "Funnel infographic", description: "Vertical funnel of stages with conversion", zones: ["title", "stages"] },
  { id: "LF-33", name: "Bar comparison", description: "Horizontal bar comparison across items", zones: ["title", "bars"] },
  { id: "LF-34", name: "Circular flow", description: "Circular / cyclical process of 3–6 steps", zones: ["title", "steps", "hub"] },
  { id: "LF-35", name: "Pyramid", description: "Stacked pyramid tiers from base to peak", zones: ["title", "tiers"] },
  { id: "LF-36", name: "Venn", description: "Overlapping sets showing intersection", zones: ["title", "sets", "intersection"] },
  { id: "LF-37", name: "Media matrix", description: "Grid of media tiles paired with copy", zones: ["title", "cells"] },
  { id: "LF-38", name: "Quote wall", description: "Multiple stacked quotes as a chorus", zones: ["title", "quotes"] },
  { id: "LF-39", name: "Client matrix", description: "Grid of client outcomes with logo, metric, note", zones: ["title", "cells"] },
];

// ────────────────────────────────────────────────────────────────────────────
// Module Variants — expanded seed set spanning every family
// ────────────────────────────────────────────────────────────────────────────
export const MODULE_VARIANTS: ModuleVariant[] = [
  // ── MF-01 Opening & Orientation ─────────────────────────────────────────
  {
    id: "MV-OP-COVER",
    familyId: "MF-01",
    name: "Cover — classic",
    description: "Deck cover with client, title, date, presenter",
    permittedLayoutIds: ["LF-01"],
    capacity: { titleChars: 80, bodyChars: 120 },
    editableFields: ["title", "subtitle", "clientName", "presenter", "date"],
    lockedFields: ["logo", "brandBar"],
  },
  {
    id: "MV-OP-COVER-MEDIA",
    familyId: "MF-01",
    name: "Cover — full-bleed media",
    description: "Cover with a hero image behind the title",
    permittedLayoutIds: ["LF-05"],
    capacity: { titleChars: 60, bodyChars: 100 },
    editableFields: ["title", "subtitle", "clientName", "date"],
    lockedFields: ["logo", "brandBar", "overlayGradient"],
  },
  {
    id: "MV-OP-COVER-MINIMAL",
    familyId: "MF-01",
    name: "Cover — minimal",
    description: "Restrained cover: brand mark, title, date",
    permittedLayoutIds: ["LF-01"],
    capacity: { titleChars: 60 },
    editableFields: ["title", "subtitle", "date"],
    lockedFields: ["logo", "brandBar"],
  },
  {
    id: "MV-OP-AGENDA",
    familyId: "MF-01",
    name: "Agenda — two column",
    description: "Numbered agenda list, 2-column layout",
    permittedLayoutIds: ["LF-04"],
    capacity: { items: { min: 3, max: 6 }, titleChars: 60, bodyChars: 80 },
    editableFields: ["title", "items[].label"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-OP-AGENDA-VERTICAL",
    familyId: "MF-01",
    name: "Agenda — vertical",
    description: "Single-column numbered agenda with descriptions",
    permittedLayoutIds: ["LF-13"],
    capacity: { items: { min: 3, max: 7 }, titleChars: 60, bodyChars: 140 },
    editableFields: ["title", "items[].label", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-OP-DIVIDER",
    familyId: "MF-01",
    name: "Section divider",
    description: "Chapter break between deck sections",
    permittedLayoutIds: ["LF-01"],
    capacity: { titleChars: 60 },
    editableFields: ["title", "kicker"],
    lockedFields: ["logo", "brandBar"],
  },
  {
    id: "MV-OP-DIVIDER-NUMBERED",
    familyId: "MF-01",
    name: "Section divider — numbered",
    description: "Chapter break with large chapter number",
    permittedLayoutIds: ["LF-01"],
    capacity: { titleChars: 60 },
    editableFields: ["chapterNumber", "title", "kicker"],
    lockedFields: ["logo", "brandBar"],
  },
  {
    id: "MV-OP-INTRO-TEAM",
    familyId: "MF-01",
    name: "Who's presenting",
    description: "Introduce the presenting team",
    permittedLayoutIds: ["LF-08"],
    capacity: { items: { min: 2, max: 4 }, titleChars: 40, bodyChars: 100 },
    editableFields: ["title", "items[].name", "items[].role", "items[].note"],
    lockedFields: ["footer", "logo"],
  },

  // ── MF-02 Context & Challenge ───────────────────────────────────────────
  {
    id: "MV-CTX-CARDS-2",
    familyId: "MF-02",
    name: "Two challenge cards",
    description: "Two parallel challenges, more room per card",
    permittedLayoutIds: ["LF-04"],
    capacity: { items: { min: 2, max: 2 }, titleChars: 40, bodyChars: 200 },
    editableFields: ["title", "items[].title", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CTX-CARDS-3",
    familyId: "MF-02",
    name: "Three challenge cards",
    description: "Three parallel challenges with title + body",
    permittedLayoutIds: ["LF-08"],
    capacity: { items: { min: 3, max: 3 }, titleChars: 40, bodyChars: 140 },
    fallbackVariantId: "MV-CTX-CARDS-2",
    editableFields: ["title", "items[].title", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CTX-CARDS-4",
    familyId: "MF-02",
    name: "Four challenge tiles",
    description: "2×2 grid of challenges",
    permittedLayoutIds: ["LF-10"],
    capacity: { items: { min: 4, max: 4 }, titleChars: 32, bodyChars: 100 },
    editableFields: ["title", "items[].title", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CTX-COST",
    familyId: "MF-02",
    name: "Cost of inaction",
    description: "Headline stat + narrative on cost of doing nothing",
    permittedLayoutIds: ["LF-07"],
    capacity: { titleChars: 40, bodyChars: 220 },
    editableFields: ["stat", "unit", "label", "narrative"],
    lockedFields: ["source_style", "footer"],
  },
  {
    id: "MV-CTX-STAT-GRID",
    familyId: "MF-02",
    name: "Market stat grid",
    description: "Four supporting market stats",
    permittedLayoutIds: ["LF-10"],
    capacity: { items: { min: 4, max: 4 } },
    editableFields: ["title", "items[].value", "items[].unit", "items[].label"],
    lockedFields: ["items[].source", "footer", "logo"],
  },
  {
    id: "MV-CTX-TREND",
    familyId: "MF-02",
    name: "Trend narrative",
    description: "Directional trend headline + supporting narrative",
    permittedLayoutIds: ["LF-02"],
    capacity: { titleChars: 100, bodyChars: 260 },
    editableFields: ["direction", "headline", "narrative"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CTX-CHALLENGE-STACK",
    familyId: "MF-02",
    name: "Challenge stack",
    description: "Numbered vertical list of challenges we heard",
    permittedLayoutIds: ["LF-13"],
    capacity: { items: { min: 3, max: 6 }, titleChars: 60, bodyChars: 160 },
    editableFields: ["title", "items[].title", "items[].body"],
    lockedFields: ["footer", "logo"],
  },

  // ── MF-03 Insight & Opportunity ─────────────────────────────────────────
  {
    id: "MV-INS-CALLOUT",
    familyId: "MF-03",
    name: "Insight callout",
    description: "Single insight with supporting narrative",
    permittedLayoutIds: ["LF-02", "LF-06"],
    capacity: { titleChars: 100, bodyChars: 260 },
    editableFields: ["insight", "narrative"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-INS-BIG-IDEA",
    familyId: "MF-03",
    name: "Big idea",
    description: "One-line big idea, maximum focus",
    permittedLayoutIds: ["LF-01"],
    capacity: { titleChars: 120 },
    editableFields: ["idea", "kicker"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-INS-SO-WHAT",
    familyId: "MF-03",
    name: "Insight → So what → Now what",
    description: "Insight paired with implication and action",
    permittedLayoutIds: ["LF-08"],
    capacity: { titleChars: 60, bodyChars: 180 },
    editableFields: ["insight", "soWhat", "nowWhat"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-INS-OPPORTUNITY-SIZE",
    familyId: "MF-03",
    name: "Opportunity size",
    description: "TAM / SAM / SOM stack",
    permittedLayoutIds: ["LF-08"],
    capacity: { items: { min: 3, max: 3 } },
    editableFields: ["title", "items[].value", "items[].unit", "items[].label"],
    lockedFields: ["items[].source", "footer", "logo"],
  },
  {
    id: "MV-INS-QUOTE",
    familyId: "MF-03",
    name: "Client quote",
    description: "Pull-quote with attribution",
    permittedLayoutIds: ["LF-20"],
    capacity: { bodyChars: 260 },
    editableFields: ["quote", "attribution", "role"],
    lockedFields: ["footer", "logo", "quoteMark"],
  },

  // ── MF-04 Solution & Process ────────────────────────────────────────────
  {
    id: "MV-SOL-PILLARS-2",
    familyId: "MF-04",
    name: "Two solution pillars",
    description: "Two focused pillars, longer body",
    permittedLayoutIds: ["LF-04"],
    capacity: { items: { min: 2, max: 2 }, titleChars: 40, bodyChars: 200 },
    editableFields: ["title", "items[].title", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-SOL-PILLARS-3",
    familyId: "MF-04",
    name: "Three solution pillars",
    description: "Three pillars of the solution",
    permittedLayoutIds: ["LF-08"],
    capacity: { items: { min: 3, max: 3 }, titleChars: 40, bodyChars: 140 },
    editableFields: ["title", "items[].title", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-SOL-PILLARS-4",
    familyId: "MF-04",
    name: "Four solution tiles",
    description: "2×2 tiles of solution capabilities",
    permittedLayoutIds: ["LF-10"],
    capacity: { items: { min: 4, max: 4 }, titleChars: 32, bodyChars: 100 },
    editableFields: ["title", "items[].title", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-SOL-PILLARS-5",
    familyId: "MF-04",
    name: "Hero + four tiles",
    description: "One hero capability with four supporting",
    permittedLayoutIds: ["LF-12"],
    capacity: { items: { min: 4, max: 4 }, titleChars: 40, bodyChars: 120 },
    editableFields: ["title", "hero.title", "hero.body", "items[].title", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-SOL-ARCHITECTURE",
    familyId: "MF-04",
    name: "Layered architecture",
    description: "Stacked layers of a solution architecture",
    permittedLayoutIds: ["LF-22"],
    capacity: { items: { min: 3, max: 5 }, titleChars: 40, bodyChars: 120 },
    editableFields: ["title", "items[].label", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-SOL-FEATURE-LIST",
    familyId: "MF-04",
    name: "Feature list",
    description: "Bulleted feature list with short descriptions",
    permittedLayoutIds: ["LF-04"],
    capacity: { items: { min: 4, max: 8 }, titleChars: 40, bodyChars: 120 },
    editableFields: ["title", "items[].label", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-PROC-TIMELINE",
    familyId: "MF-04",
    name: "Process timeline",
    description: "Sequential steps across the engagement",
    permittedLayoutIds: ["LF-14"],
    capacity: { items: { min: 3, max: 5 }, titleChars: 30, bodyChars: 90 },
    editableFields: ["title", "items[].label", "items[].body"],
    lockedFields: ["footer", "logo", "connector"],
  },
  {
    id: "MV-PROC-PHASES",
    familyId: "MF-04",
    name: "Numbered phases",
    description: "Discovery / build / scale style vertical phases",
    permittedLayoutIds: ["LF-13"],
    capacity: { items: { min: 3, max: 5 }, titleChars: 40, bodyChars: 160 },
    editableFields: ["title", "items[].label", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-PROC-BEFORE-AFTER",
    familyId: "MF-04",
    name: "Before → After",
    description: "Two-state view of the workflow change",
    permittedLayoutIds: ["LF-15"],
    capacity: { titleChars: 40, bodyChars: 200 },
    editableFields: ["title", "before.title", "before.body", "after.title", "after.body"],
    lockedFields: ["footer", "logo"],
  },

  // ── MF-05 Proof, Data & Decision ────────────────────────────────────────
  {
    id: "MV-PROOF-STATS-2",
    familyId: "MF-05",
    name: "Two proof stats",
    description: "Two large stats with narrative",
    permittedLayoutIds: ["LF-04"],
    capacity: { items: { min: 2, max: 2 } },
    editableFields: ["title", "items[].value", "items[].unit", "items[].label"],
    lockedFields: ["items[].source", "footer", "logo"],
  },
  {
    id: "MV-PROOF-STATS-3",
    familyId: "MF-05",
    name: "Three proof stats",
    description: "Three big-number stats with labels + sources",
    permittedLayoutIds: ["LF-08"],
    capacity: { items: { min: 3, max: 3 } },
    editableFields: ["title", "items[].value", "items[].unit", "items[].label"],
    lockedFields: ["items[].source", "footer", "logo"],
  },
  {
    id: "MV-PROOF-STATS-4",
    familyId: "MF-05",
    name: "Four proof stats",
    description: "Four big-number stats in a 2×2 grid",
    permittedLayoutIds: ["LF-10"],
    capacity: { items: { min: 4, max: 4 } },
    editableFields: ["title", "items[].value", "items[].unit", "items[].label"],
    lockedFields: ["items[].source", "footer", "logo"],
  },
  {
    id: "MV-PROOF-LOGOS",
    familyId: "MF-05",
    name: "Client logo wall",
    description: "Grid of representative client / partner logos",
    permittedLayoutIds: ["LF-19"],
    capacity: { items: { min: 6, max: 12 }, titleChars: 60 },
    editableFields: ["title", "items[].name"],
    lockedFields: ["items[].logoUrl", "footer", "logo"],
  },
  {
    id: "MV-PROOF-TESTIMONIAL",
    familyId: "MF-05",
    name: "Testimonial card",
    description: "Client testimonial with headshot + metric",
    permittedLayoutIds: ["LF-03"],
    capacity: { bodyChars: 300 },
    editableFields: ["quote", "attribution", "role", "metric"],
    lockedFields: ["footer", "logo", "clientLogo"],
  },
  {
    id: "MV-DEC-MATRIX",
    familyId: "MF-05",
    name: "Decision matrix",
    description: "2×2 comparison / positioning matrix",
    permittedLayoutIds: ["LF-16"],
    capacity: { titleChars: 60, bodyChars: 140 },
    editableFields: ["title", "axisX", "axisY", "q1", "q2", "q3", "q4"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-DEC-COMPARE-TABLE",
    familyId: "MF-05",
    name: "Comparison table",
    description: "Criteria × options table",
    permittedLayoutIds: ["LF-17"],
    capacity: { items: { min: 3, max: 6 }, titleChars: 60 },
    editableFields: ["title", "columns[].label", "items[].criterion", "items[].values[]"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-DEC-CHECKLIST",
    familyId: "MF-05",
    name: "Decision checklist",
    description: "Criteria to meet, framed as a checklist",
    permittedLayoutIds: ["LF-13"],
    capacity: { items: { min: 4, max: 8 }, titleChars: 60, bodyChars: 100 },
    editableFields: ["title", "items[].label", "items[].note"],
    lockedFields: ["footer", "logo", "checkStyle"],
  },
  {
    id: "MV-COMM-PRICING",
    familyId: "MF-05",
    name: "Pricing tiers",
    description: "Three parallel pricing / package tiers",
    permittedLayoutIds: ["LF-23"],
    capacity: { items: { min: 3, max: 3 }, titleChars: 60, bodyChars: 200 },
    editableFields: ["title", "items[].name", "items[].price", "items[].unit", "items[].features[]"],
    lockedFields: ["footer", "logo", "currency"],
  },
  {
    id: "MV-COMM-INVESTMENT",
    familyId: "MF-05",
    name: "Investment summary",
    description: "Single price + what's included",
    permittedLayoutIds: ["LF-07"],
    capacity: { titleChars: 40, bodyChars: 260, items: { min: 3, max: 6 } },
    editableFields: ["title", "amount", "unit", "items[].label"],
    lockedFields: ["footer", "logo", "currency"],
  },
  {
    id: "MV-RISK-MITIGATION",
    familyId: "MF-05",
    name: "Risk & mitigation",
    description: "Pairs of risks and how we address them",
    permittedLayoutIds: ["LF-04"],
    capacity: { items: { min: 3, max: 5 }, titleChars: 60, bodyChars: 160 },
    editableFields: ["title", "items[].risk", "items[].mitigation"],
    lockedFields: ["footer", "logo"],
  },

  // ── MF-06 Case Study ────────────────────────────────────────────────────
  {
    id: "MV-CASE-SPREAD",
    familyId: "MF-06",
    name: "Case study spread",
    description: "Client, challenge, solution, result",
    permittedLayoutIds: ["LF-18"],
    capacity: { bodyChars: 160 },
    editableFields: ["client", "challenge", "solution", "result", "metric"],
    lockedFields: ["clientLogo", "source", "footer"],
  },
  {
    id: "MV-CASE-METRICS",
    familyId: "MF-06",
    name: "Case study — metrics forward",
    description: "Case study with three headline metrics",
    permittedLayoutIds: ["LF-06"],
    capacity: { items: { min: 3, max: 3 }, bodyChars: 200 },
    editableFields: ["client", "summary", "items[].value", "items[].unit", "items[].label"],
    lockedFields: ["clientLogo", "source", "footer"],
  },
  {
    id: "MV-CASE-STORY",
    familyId: "MF-06",
    name: "Case study — narrative",
    description: "Long-form narrative case study",
    permittedLayoutIds: ["LF-03"],
    capacity: { bodyChars: 600 },
    editableFields: ["client", "headline", "story", "result"],
    lockedFields: ["clientLogo", "source", "footer"],
  },
  {
    id: "MV-CASE-LOGO-GRID",
    familyId: "MF-06",
    name: "Case study logo grid",
    description: "Grid of case studies with client + one-line result",
    permittedLayoutIds: ["LF-11"],
    capacity: { items: { min: 4, max: 6 }, titleChars: 60, bodyChars: 100 },
    editableFields: ["title", "items[].client", "items[].result"],
    lockedFields: ["items[].logoUrl", "footer", "logo"],
  },

  // ── MF-07 Team, Governance & Close ──────────────────────────────────────
  {
    id: "MV-TEAM-BIOS-3",
    familyId: "MF-07",
    name: "Team — three bios",
    description: "Three team members with role and short bio",
    permittedLayoutIds: ["LF-21"],
    capacity: { items: { min: 3, max: 3 }, titleChars: 60, bodyChars: 120 },
    editableFields: ["title", "items[].name", "items[].role", "items[].bio"],
    lockedFields: ["items[].headshot", "footer", "logo"],
  },
  {
    id: "MV-TEAM-BIOS-4",
    familyId: "MF-07",
    name: "Team — four bios",
    description: "Four team members with role and short bio",
    permittedLayoutIds: ["LF-21"],
    capacity: { items: { min: 4, max: 4 }, titleChars: 60, bodyChars: 100 },
    editableFields: ["title", "items[].name", "items[].role", "items[].bio"],
    lockedFields: ["items[].headshot", "footer", "logo"],
  },
  {
    id: "MV-GOV-RACI",
    familyId: "MF-07",
    name: "Governance model",
    description: "Governance rhythm — who meets when, deciding what",
    permittedLayoutIds: ["LF-13"],
    capacity: { items: { min: 3, max: 5 }, titleChars: 60, bodyChars: 160 },
    editableFields: ["title", "items[].forum", "items[].cadence", "items[].purpose"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-REC-NEXT",
    familyId: "MF-07",
    name: "Recommendation",
    description: "Recommended path and rationale",
    permittedLayoutIds: ["LF-06", "LF-02"],
    capacity: { titleChars: 100, bodyChars: 320 },
    editableFields: ["recommendation", "rationale"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CLOSE-CTA",
    familyId: "MF-07",
    name: "Close & CTA",
    description: "Sign-off with next steps + owner",
    permittedLayoutIds: ["LF-24"],
    capacity: { titleChars: 80, bodyChars: 200 },
    editableFields: ["message", "nextSteps", "owner", "followUp"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CLOSE-THANKS",
    familyId: "MF-07",
    name: "Thank you",
    description: "Simple thank-you close",
    permittedLayoutIds: ["LF-01"],
    capacity: { titleChars: 40, bodyChars: 120 },
    editableFields: ["message", "signoff"],
    lockedFields: ["footer", "logo", "brandBar"],
  },
  {
    id: "MV-CLOSE-QNA",
    familyId: "MF-07",
    name: "Q & A",
    description: "Open discussion / questions prompt",
    permittedLayoutIds: ["LF-01"],
    capacity: { titleChars: 40, bodyChars: 160 },
    editableFields: ["title", "prompt"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CLOSE-CONTACT",
    familyId: "MF-07",
    name: "Contact card",
    description: "Follow-up owner(s) with contact details",
    permittedLayoutIds: ["LF-04"],
    capacity: { items: { min: 1, max: 3 }, titleChars: 40, bodyChars: 120 },
    editableFields: ["title", "items[].name", "items[].role", "items[].email", "items[].phone"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CLOSE-TIMELINE",
    familyId: "MF-07",
    name: "Next-step timeline",
    description: "30 / 60 / 90-day plan for what happens after sign-off",
    permittedLayoutIds: ["LF-14"],
    capacity: { items: { min: 3, max: 4 }, titleChars: 60, bodyChars: 140 },
    editableFields: ["title", "items[].label", "items[].body", "items[].owner"],
    lockedFields: ["footer", "logo", "connector"],
  },
  {
    id: "MV-CLOSE-CHECKLIST",
    familyId: "MF-07",
    name: "What happens next",
    description: "Checklist of concrete next actions with owners",
    permittedLayoutIds: ["LF-13"],
    capacity: { items: { min: 3, max: 6 }, titleChars: 60, bodyChars: 120 },
    editableFields: ["title", "items[].label", "items[].owner", "items[].when"],
    lockedFields: ["footer", "logo", "checkStyle"],
  },
  {
    id: "MV-CLOSE-DECISION",
    familyId: "MF-07",
    name: "Decision ask",
    description: "Single clear ask with the specific decision being requested",
    permittedLayoutIds: ["LF-01"],
    capacity: { titleChars: 100, bodyChars: 260 },
    editableFields: ["kicker", "ask", "rationale", "decisionBy"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CLOSE-CALENDAR",
    familyId: "MF-07",
    name: "Book the kickoff",
    description: "Concrete kickoff date with a calendar-style anchor",
    permittedLayoutIds: ["LF-07"],
    capacity: { titleChars: 60, bodyChars: 200 },
    editableFields: ["title", "date", "day", "monthYear", "body", "owner"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CLOSE-STATEMENT",
    familyId: "MF-07",
    name: "Statement close",
    description: "Poster-scale sign-off statement on a solid brand field",
    permittedLayoutIds: ["LF-28"],
    capacity: { titleChars: 100, bodyChars: 120 },
    editableFields: ["kicker", "statement", "signoff"],
    lockedFields: ["footer", "logo", "brandBar"],
  },
  {
    id: "MV-CLOSE-SPLIT",
    familyId: "MF-07",
    name: "Split — image + CTA",
    description: "Half-bleed image paired with a CTA panel and owner",
    permittedLayoutIds: ["LF-03"],
    capacity: { titleChars: 60, bodyChars: 220 },
    editableFields: ["title", "body", "ctaLabel", "ctaDetail", "owner", "mediaSeed"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CLOSE-DUAL-CTA",
    familyId: "MF-07",
    name: "Two-path CTA",
    description: "Two commit paths side-by-side — e.g. pilot vs. full program",
    permittedLayoutIds: ["LF-04"],
    capacity: { items: { min: 2, max: 2 }, titleChars: 60, bodyChars: 180 },
    editableFields: ["title", "items[].label", "items[].body", "items[].ctaLabel", "items[].note"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CLOSE-METRIC-PROMISE",
    familyId: "MF-07",
    name: "Metric promise",
    description: "The number we're going after, framed as the commitment",
    permittedLayoutIds: ["LF-07"],
    capacity: { titleChars: 80, bodyChars: 200 },
    editableFields: ["kicker", "metric", "unit", "promise", "timeframe", "owner"],
    lockedFields: ["footer", "logo"],
  },

  // ── MF-01 Extended cover / title variants ───────────────────────────────
  {
    id: "MV-OP-COVER-EDITORIAL",
    familyId: "MF-01",
    name: "Cover — editorial",
    description: "Magazine-style cover with oversized type and a small photo tile",
    permittedLayoutIds: ["LF-25"],
    capacity: { titleChars: 80, bodyChars: 120 },
    editableFields: ["kicker", "title", "subtitle", "clientName", "date", "mediaSeed"],
    lockedFields: ["logo", "brandBar"],
  },
  {
    id: "MV-OP-COVER-SPLIT",
    familyId: "MF-01",
    name: "Cover — split image",
    description: "50/50 split with hero image on one side, title on the other",
    permittedLayoutIds: ["LF-03"],
    capacity: { titleChars: 70, bodyChars: 140 },
    editableFields: ["title", "subtitle", "clientName", "date", "mediaSeed"],
    lockedFields: ["logo", "brandBar"],
  },
  {
    id: "MV-OP-COVER-POSTER",
    familyId: "MF-01",
    name: "Cover — poster",
    description: "Poster-scale typography on a solid brand field",
    permittedLayoutIds: ["LF-28"],
    capacity: { titleChars: 40 },
    editableFields: ["kicker", "title", "meta"],
    lockedFields: ["logo", "brandBar"],
  },
  {
    id: "MV-OP-COVER-GRID",
    familyId: "MF-01",
    name: "Cover — media grid",
    description: "Four-tile media grid backdrop behind the title lockup",
    permittedLayoutIds: ["LF-10"],
    capacity: { titleChars: 60, bodyChars: 100, items: { min: 4, max: 4 } },
    editableFields: ["title", "subtitle", "date", "items[].seed"],
    lockedFields: ["logo", "brandBar"],
  },
  {
    id: "MV-OP-COVER-DOSSIER",
    familyId: "MF-01",
    name: "Cover — dossier",
    description: "Confidential-dossier style cover with stamp and metadata",
    permittedLayoutIds: ["LF-01"],
    capacity: { titleChars: 80, bodyChars: 200 },
    editableFields: ["reference", "title", "clientName", "prepared", "date"],
    lockedFields: ["logo", "brandBar", "stamp"],
  },
  {
    id: "MV-OP-COVER-GRADIENT",
    familyId: "MF-01",
    name: "Cover — chromatic",
    description: "Soft chromatic gradient hero with restrained typography",
    permittedLayoutIds: ["LF-05"],
    capacity: { titleChars: 80 },
    editableFields: ["title", "subtitle", "clientName", "date"],
    lockedFields: ["logo", "brandBar", "gradient"],
  },
  {
    id: "MV-OP-COVER-MONOGRAM",
    familyId: "MF-01",
    name: "Cover — monogram",
    description: "Massive monogram / initials treatment as visual anchor",
    permittedLayoutIds: ["LF-01"],
    capacity: { titleChars: 60 },
    editableFields: ["monogram", "title", "subtitle", "date"],
    lockedFields: ["logo", "brandBar"],
  },
  {
    id: "MV-OP-COVER-STACKED",
    familyId: "MF-01",
    name: "Cover — stacked",
    description: "Kicker + headline + framed portrait stacked vertically",
    permittedLayoutIds: ["LF-25"],
    capacity: { titleChars: 80, bodyChars: 140 },
    editableFields: ["kicker", "title", "subtitle", "date", "mediaSeed"],
    lockedFields: ["logo", "brandBar"],
  },

  // ── Image-forward content variants ──────────────────────────────────────
  {
    id: "MV-IMG-FULL-BLEED",
    familyId: "MF-04",
    name: "Full-bleed image",
    description: "Edge-to-edge hero visual with overlay title",
    permittedLayoutIds: ["LF-05"],
    capacity: { titleChars: 80, bodyChars: 180 },
    editableFields: ["kicker", "title", "body", "mediaSeed"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-IMG-SPLIT",
    familyId: "MF-04",
    name: "Split — media + copy",
    description: "50/50 media panel with narrative alongside",
    permittedLayoutIds: ["LF-03"],
    capacity: { titleChars: 60, bodyChars: 320 },
    editableFields: ["title", "body", "caption", "mediaSeed"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-IMG-CAPTION",
    familyId: "MF-04",
    name: "Framed image + caption",
    description: "Centered framed image with a short caption below",
    permittedLayoutIds: ["LF-29"],
    capacity: { titleChars: 60, bodyChars: 200 },
    editableFields: ["title", "caption", "credit", "mediaSeed"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-IMG-GRID-3",
    familyId: "MF-04",
    name: "Media trio",
    description: "Three media tiles side-by-side with captions",
    permittedLayoutIds: ["LF-26"],
    capacity: { items: { min: 3, max: 3 }, titleChars: 60, bodyChars: 100 },
    editableFields: ["title", "items[].caption", "items[].label", "items[].seed"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-IMG-GRID-6",
    familyId: "MF-05",
    name: "Media grid — six",
    description: "3×2 gallery of media tiles for portfolio / product proof",
    permittedLayoutIds: ["LF-26"],
    capacity: { items: { min: 6, max: 6 }, titleChars: 60, bodyChars: 80 },
    editableFields: ["title", "items[].caption", "items[].seed"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-IMG-PORTRAIT",
    familyId: "MF-07",
    name: "Portrait feature",
    description: "Full-height portrait with narrative panel — for spokesperson / leader",
    permittedLayoutIds: ["LF-27"],
    capacity: { titleChars: 60, bodyChars: 320 },
    editableFields: ["name", "role", "quote", "narrative", "mediaSeed"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-IMG-QUOTE-BG",
    familyId: "MF-03",
    name: "Quote over image",
    description: "Photographic backdrop with a pull-quote and attribution",
    permittedLayoutIds: ["LF-05"],
    capacity: { bodyChars: 220 },
    editableFields: ["quote", "attribution", "role", "mediaSeed"],
    lockedFields: ["footer", "logo", "overlay"],
  },
  {
    id: "MV-IMG-BEFORE-AFTER",
    familyId: "MF-04",
    name: "Before / after — visual",
    description: "Two media panels showing the state change",
    permittedLayoutIds: ["LF-15"],
    capacity: { titleChars: 60, bodyChars: 140 },
    editableFields: ["title", "before.label", "before.body", "before.seed", "after.label", "after.body", "after.seed"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-IMG-STAT-CALLOUT",
    familyId: "MF-05",
    name: "Image + stat callout",
    description: "Full-height image beside an oversized proof stat",
    permittedLayoutIds: ["LF-03"],
    capacity: { titleChars: 60, bodyChars: 200 },
    editableFields: ["stat", "unit", "label", "narrative", "mediaSeed"],
    lockedFields: ["footer", "logo", "source"],
  },
  {
    id: "MV-IMG-STRIP",
    familyId: "MF-05",
    name: "Filmstrip",
    description: "Horizontal filmstrip of five media frames",
    permittedLayoutIds: ["LF-30"],
    capacity: { items: { min: 5, max: 5 }, titleChars: 60 },
    editableFields: ["title", "items[].caption", "items[].seed"],
    lockedFields: ["footer", "logo"],
  },

  // ── Expanded quote layouts (MF-03 / MF-05) ─────────────────────────────
  {
    id: "MV-QUOTE-MULTI",
    familyId: "MF-05",
    name: "Quote wall — three voices",
    description: "Three short pull-quotes stacked as a chorus of client voices",
    permittedLayoutIds: ["LF-38"],
    capacity: { items: { min: 3, max: 3 }, titleChars: 60, bodyChars: 180 },
    editableFields: ["title", "items[].quote", "items[].attribution", "items[].role"],
    lockedFields: ["footer", "logo", "quoteMark"],
  },
  {
    id: "MV-QUOTE-PORTRAIT",
    familyId: "MF-05",
    name: "Quote — portrait",
    description: "Full-height portrait beside an oversized pull-quote",
    permittedLayoutIds: ["LF-27"],
    capacity: { bodyChars: 260 },
    editableFields: ["quote", "attribution", "role", "org", "mediaSeed"],
    lockedFields: ["footer", "logo", "quoteMark", "clientLogo"],
  },
  {
    id: "MV-QUOTE-CARD",
    familyId: "MF-05",
    name: "Quote — framed card",
    description: "Centered framed quote card with brand bar and attribution",
    permittedLayoutIds: ["LF-20"],
    capacity: { bodyChars: 240 },
    editableFields: ["quote", "attribution", "role", "org"],
    lockedFields: ["footer", "logo", "quoteMark", "clientLogo"],
  },
  {
    id: "MV-QUOTE-METRIC",
    familyId: "MF-05",
    name: "Quote + proof metric",
    description: "Pull-quote paired with a headline proof metric",
    permittedLayoutIds: ["LF-03"],
    capacity: { bodyChars: 240 },
    editableFields: ["quote", "attribution", "role", "metric", "unit", "metricLabel"],
    lockedFields: ["footer", "logo", "quoteMark", "source"],
  },
  {
    id: "MV-QUOTE-POSTER",
    familyId: "MF-03",
    name: "Quote — poster",
    description: "Poster-scale quote on a solid brand field",
    permittedLayoutIds: ["LF-28"],
    capacity: { bodyChars: 160 },
    editableFields: ["quote", "attribution", "role"],
    lockedFields: ["footer", "logo", "brandBar"],
  },

  // ── Infographic options (MF-04 / MF-05) ────────────────────────────────
  {
    id: "MV-INFO-DONUT",
    familyId: "MF-05",
    name: "Donut infographic",
    description: "Donut chart with center callout and a segmented legend",
    permittedLayoutIds: ["LF-31"],
    capacity: { items: { min: 3, max: 5 }, titleChars: 60, bodyChars: 160 },
    editableFields: ["title", "centerValue", "centerUnit", "centerLabel", "items[].label", "items[].value", "items[].note"],
    lockedFields: ["footer", "logo", "source"],
  },
  {
    id: "MV-INFO-FUNNEL",
    familyId: "MF-05",
    name: "Funnel infographic",
    description: "Vertical funnel showing stage-to-stage conversion",
    permittedLayoutIds: ["LF-32"],
    capacity: { items: { min: 3, max: 5 }, titleChars: 60, bodyChars: 140 },
    editableFields: ["title", "items[].label", "items[].value", "items[].unit", "items[].note"],
    lockedFields: ["footer", "logo", "source"],
  },
  {
    id: "MV-INFO-BAR-COMPARE",
    familyId: "MF-05",
    name: "Bar comparison",
    description: "Horizontal bar comparison across items or options",
    permittedLayoutIds: ["LF-33"],
    capacity: { items: { min: 3, max: 6 }, titleChars: 60, bodyChars: 120 },
    editableFields: ["title", "unit", "items[].label", "items[].value", "items[].note"],
    lockedFields: ["footer", "logo", "source"],
  },
  {
    id: "MV-INFO-CIRCULAR-FLOW",
    familyId: "MF-04",
    name: "Circular flow",
    description: "Cyclical process with 4 steps around a central hub",
    permittedLayoutIds: ["LF-34"],
    capacity: { items: { min: 4, max: 6 }, titleChars: 60, bodyChars: 100 },
    editableFields: ["title", "hub", "items[].label", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-INFO-PYRAMID",
    familyId: "MF-04",
    name: "Pyramid",
    description: "Stacked tiers from foundation to peak",
    permittedLayoutIds: ["LF-35"],
    capacity: { items: { min: 3, max: 5 }, titleChars: 60, bodyChars: 120 },
    editableFields: ["title", "items[].label", "items[].body"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-INFO-VENN",
    familyId: "MF-04",
    name: "Venn — three sets",
    description: "Three overlapping sets with a named intersection",
    permittedLayoutIds: ["LF-36"],
    capacity: { items: { min: 3, max: 3 }, titleChars: 60, bodyChars: 100 },
    editableFields: ["title", "intersection", "items[].label", "items[].body"],
    lockedFields: ["footer", "logo"],
  },

  // ── Client & image content matrix layouts ──────────────────────────────
  {
    id: "MV-CLIENT-MATRIX",
    familyId: "MF-06",
    name: "Client outcome matrix",
    description: "Grid of client cards — logo, one-line result, headline metric",
    permittedLayoutIds: ["LF-39"],
    capacity: { items: { min: 4, max: 6 }, titleChars: 60, bodyChars: 100 },
    editableFields: ["title", "items[].client", "items[].sector", "items[].result", "items[].metric", "items[].unit"],
    lockedFields: ["items[].logoUrl", "footer", "logo"],
  },
  {
    id: "MV-CLIENT-DETAIL-3",
    familyId: "MF-06",
    name: "Client detail cards",
    description: "Three client cards with portrait, logo, and short story",
    permittedLayoutIds: ["LF-08"],
    capacity: { items: { min: 3, max: 3 }, titleChars: 60, bodyChars: 200 },
    editableFields: ["title", "items[].client", "items[].sector", "items[].story", "items[].metric", "items[].seed"],
    lockedFields: ["items[].logoUrl", "footer", "logo"],
  },
  {
    id: "MV-IMG-MATRIX-4",
    familyId: "MF-04",
    name: "Media matrix — four",
    description: "2×2 matrix pairing an image with a short label + body",
    permittedLayoutIds: ["LF-37"],
    capacity: { items: { min: 4, max: 4 }, titleChars: 60, bodyChars: 120 },
    editableFields: ["title", "items[].label", "items[].body", "items[].seed"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-IMG-MATRIX-6",
    familyId: "MF-05",
    name: "Media matrix — six",
    description: "3×2 matrix pairing images with labels + body copy",
    permittedLayoutIds: ["LF-37"],
    capacity: { items: { min: 6, max: 6 }, titleChars: 60, bodyChars: 100 },
    editableFields: ["title", "items[].label", "items[].body", "items[].seed"],
    lockedFields: ["footer", "logo"],
  },
  {
    id: "MV-CLIENT-COMPARE",
    familyId: "MF-06",
    name: "Client comparison strip",
    description: "Vertical strip comparing three client engagements side-by-side",
    permittedLayoutIds: ["LF-08"],
    capacity: { items: { min: 3, max: 3 }, titleChars: 60, bodyChars: 160 },
    editableFields: ["title", "items[].client", "items[].challenge", "items[].outcome", "items[].metric"],
    lockedFields: ["items[].logoUrl", "footer", "logo"],
  },
];
export const NARRATIVE_ARCHETYPES: NarrativeArchetype[] = [
  {
    id: "arch-problem-solution",
    name: "Problem → Solution",
    description: "Classic pitch: frame the problem, insight, solution, proof, close",
    sectionRecipe: ["SF-01", "SF-03", "SF-04", "SF-05", "SF-06", "SF-08", "SF-09", "SF-15", "SF-16"],
  },
  {
    id: "arch-exec-briefing",
    name: "Executive briefing",
    description: "Tight briefing for a decision-making audience",
    sectionRecipe: ["SF-01", "SF-04", "SF-05", "SF-06", "SF-11", "SF-15", "SF-16"],
  },
  {
    id: "arch-product-pitch",
    name: "Product pitch",
    description: "Product-forward pitch with detail and proof",
    sectionRecipe: ["SF-01", "SF-03", "SF-06", "SF-07", "SF-10", "SF-08", "SF-13", "SF-16"],
  },
  {
    id: "arch-cross-sell",
    name: "Cross-sell",
    description: "Existing client — expand into an adjacent solution",
    sectionRecipe: ["SF-01", "SF-02", "SF-05", "SF-06", "SF-09", "SF-15", "SF-16"],
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────────
export const byId = <T extends { id: string }>(list: T[], id: string): T | undefined =>
  list.find((x) => x.id === id);

export const familyForVariant = (variantId: string) => {
  const mv = byId(MODULE_VARIANTS, variantId);
  return mv ? byId(MODULE_FAMILIES, mv.familyId) : undefined;
};

// Given a section framework, return the module variants that can populate it.
export const variantsForSection = (sectionId: string): ModuleVariant[] => {
  const sf = byId(SECTION_FRAMEWORKS, sectionId);
  if (!sf) return [];
  return MODULE_VARIANTS.filter((mv) => sf.permittedFamilyIds.includes(mv.familyId));
};
