import { SignatureTemplate, defaultDivider, defaultBorder, defaultSpacing } from "@/lib/signature/types";

export const signatureTemplates: SignatureTemplate[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // PROFESSIONAL CATEGORY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'professional-classic',
    archetype: 'classic-stacked',
    name: 'Professional Classic',
    description: 'Clean, traditional layout perfect for corporate environments',
    category: 'professional',
    thumbnail: '/templates/professional-classic.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#0f1b3d',
      secondaryColor: '#5b6478',
      fontFamily: 'Arial, sans-serif',
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#0f1b3d', width: 65, thickness: 2, spacing: 10 },
      border: { enabled: true, side: 'left', color: '#0f1b3d', width: 4, style: 'solid', radius: 0 },
      spacing: { padding: 22, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'elegant-serif',
    archetype: 'retro-editorial',
    name: 'Elegant Serif',
    description: 'Sophisticated design with classic typography',
    category: 'professional',
    thumbnail: '/templates/elegant-serif.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
    ],
    defaultStyling: {
      primaryColor: '#1c1917',
      secondaryColor: '#78716c',
      fontFamily: "'Times New Roman', serif",
      fontSize: 'medium',
      layout: 'vertical',
      divider: { type: 'double', color: '#1c1917', width: 35, thickness: 1, spacing: 14 },
      border: { enabled: false, side: 'left', color: '#1c1917', width: 2, style: 'solid', radius: 0 },
      spacing: { padding: 24, lineHeight: 1.7, sectionGap: 5, iconGap: 8 },
    },
  },
  {
    id: 'navy-gold',
    archetype: 'executive-name-first',
    name: 'Navy & Gold',
    description: 'Luxurious navy blue with gold accents',
    category: 'professional',
    thumbnail: '/templates/navy-gold.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#0c1f3f',
      secondaryColor: '#b8860b',
      fontFamily: 'Georgia, serif',
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#c9a227', width: 80, thickness: 2, spacing: 12 },
      border: { enabled: true, side: 'left', color: '#c9a227', width: 5, style: 'double', radius: 0 },
      spacing: { padding: 24, lineHeight: 1.55, sectionGap: 5, iconGap: 8 },
    },
  },
  {
    id: 'attorney-firm',
    archetype: 'business-card-box',
    name: 'Attorney Firm',
    description: 'Traditional legal/law firm style signature',
    category: 'professional',
    thumbnail: '/templates/attorney-firm.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'address', type: 'address', enabled: true, value: '', label: 'Address' },
    ],
    defaultStyling: {
      primaryColor: '#3a1f1c',
      secondaryColor: '#7d6e69',
      fontFamily: "'Times New Roman', serif",
      fontSize: 'medium',
      layout: 'vertical',
      divider: { type: 'double', color: '#3a1f1c', width: 100, thickness: 1, spacing: 12 },
      border: { enabled: true, side: 'all', color: '#3a1f1c', width: 1, style: 'solid', radius: 0 },
      spacing: { padding: 26, lineHeight: 1.65, sectionGap: 4, iconGap: 8 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODERN CATEGORY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'tech-startup',
    archetype: 'accent-bar',
    name: 'Tech Startup',
    description: 'Modern, dynamic design for tech companies',
    category: 'modern',
    thumbnail: '/templates/tech-startup.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#047857',
      secondaryColor: '#34d399',
      fontFamily: 'Tahoma, sans-serif',
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#10b981', width: 70, thickness: 2, spacing: 10 },
      border: { enabled: true, side: 'left', color: '#10b981', width: 4, style: 'solid', radius: 6 },
      spacing: { padding: 20, lineHeight: 1.45, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'consultant-pro',
    archetype: 'two-column-split',
    name: 'Consultant Pro',
    description: 'Versatile design for consultants and freelancers',
    category: 'modern',
    thumbnail: '/templates/consultant-pro.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#3730a3',
      secondaryColor: '#7c3aed',
      fontFamily: 'Verdana, sans-serif',
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#6366f1', width: 75, thickness: 2, spacing: 10 },
      border: { enabled: true, side: 'left', color: '#4f46e5', width: 4, style: 'solid', radius: 4 },
      spacing: { padding: 22, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'neon-glow',
    archetype: 'after-dark',
    name: 'Neon Glow',
    description: 'Electric cyan accents with a futuristic vibe',
    category: 'modern',
    thumbnail: '/templates/neon-glow.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#0891b2',
      secondaryColor: '#22d3ee',
      fontFamily: 'Tahoma, sans-serif',
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#22d3ee', width: 90, thickness: 3, spacing: 10 },
      border: { enabled: true, side: 'left', color: '#06b6d4', width: 4, style: 'solid', radius: 12 },
      spacing: { padding: 20, lineHeight: 1.45, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'matrix-code',
    archetype: 'after-dark',
    name: 'Matrix Code',
    description: 'Developer-friendly with monospace typography',
    category: 'modern',
    thumbnail: '/templates/matrix-code.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#15803d',
      secondaryColor: '#4ade80',
      fontFamily: "'Courier New', monospace",
      fontSize: 'medium',
      layout: 'vertical',
      divider: { type: 'dashed', color: '#22c55e', width: 100, thickness: 1, spacing: 8 },
      border: { enabled: true, side: 'all', color: '#22c55e', width: 1, style: 'dashed', radius: 2 },
      spacing: { padding: 18, lineHeight: 1.5, sectionGap: 3, iconGap: 8 },
    },
  },
  {
    id: 'blockchain-dark',
    archetype: 'after-dark',
    name: 'Blockchain Dark',
    description: 'Crypto and Web3 inspired dark theme',
    category: 'modern',
    thumbnail: '/templates/blockchain-dark.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#7e22ce',
      secondaryColor: '#d8b4fe',
      fontFamily: "'Lucida Console', monospace",
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#a855f7', width: 80, thickness: 3, spacing: 12 },
      border: { enabled: true, side: 'left', color: '#a855f7', width: 4, style: 'solid', radius: 10 },
      spacing: { padding: 22, lineHeight: 1.45, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'saas-product',
    archetype: 'two-column-split',
    name: 'SaaS Product',
    description: 'Clean B2B SaaS company signature',
    category: 'modern',
    thumbnail: '/templates/saas-product.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
    ],
    defaultStyling: {
      primaryColor: '#1d4ed8',
      secondaryColor: '#3b82f6',
      fontFamily: 'Arial, sans-serif',
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#3b82f6', width: 60, thickness: 2, spacing: 10 },
      border: { enabled: true, side: 'left', color: '#1d4ed8', width: 5, style: 'solid', radius: 4 },
      spacing: { padding: 20, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CREATIVE CATEGORY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'creative-gradient',
    archetype: 'centered-personal',
    name: 'Creative Gradient',
    description: 'Vibrant, eye-catching design for creative professionals',
    category: 'creative',
    thumbnail: '/templates/creative-gradient.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#9333ea',
      secondaryColor: '#ec4899',
      fontFamily: "'Trebuchet MS', sans-serif",
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#ec4899', width: 100, thickness: 3, spacing: 12 },
      border: { enabled: true, side: 'left', color: '#9333ea', width: 5, style: 'solid', radius: 8 },
      spacing: { padding: 22, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'social-connected',
    archetype: 'centered-personal',
    name: 'Social Connected',
    description: 'Perfect for influencers and social media managers',
    category: 'creative',
    thumbnail: '/templates/social-connected.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#be123c',
      secondaryColor: '#fb7185',
      fontFamily: "'Trebuchet MS', sans-serif",
      fontSize: 'medium',
      layout: 'vertical',
      divider: { type: 'gradient', color: '#fb7185', width: 80, thickness: 2, spacing: 10 },
      border: { enabled: true, side: 'bottom', color: '#e11d48', width: 3, style: 'solid', radius: 0 },
      spacing: { padding: 22, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'sunset-vibes',
    archetype: 'card-shadow',
    name: 'Sunset Vibes',
    description: 'Warm orange and coral tones for creatives',
    category: 'creative',
    thumbnail: '/templates/sunset-vibes.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#FF6A2B',
      secondaryColor: '#fb923c',
      fontFamily: "'Trebuchet MS', sans-serif",
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#FF6A2B', width: 90, thickness: 3, spacing: 12 },
      border: { enabled: true, side: 'left', color: '#FF6A2B', width: 5, style: 'solid', radius: 12 },
      spacing: { padding: 22, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'pink-pop',
    archetype: 'card-shadow',
    name: 'Pink Pop',
    description: 'Bold pink design for fashion and beauty',
    category: 'creative',
    thumbnail: '/templates/pink-pop.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#db2777',
      secondaryColor: '#f9a8d4',
      fontFamily: 'Georgia, serif',
      fontSize: 'medium',
      layout: 'vertical',
      divider: { type: 'dotted', color: '#db2777', width: 60, thickness: 2, spacing: 12 },
      border: { enabled: true, side: 'left', color: '#db2777', width: 4, style: 'solid', radius: 16 },
      spacing: { padding: 24, lineHeight: 1.55, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'artist-studio',
    archetype: 'retro-editorial',
    name: 'Artist Studio',
    description: 'Expressive design for visual artists',
    category: 'creative',
    thumbnail: '/templates/artist-studio.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#6d28d9',
      secondaryColor: '#c4b5fd',
      fontFamily: "'Trebuchet MS', sans-serif",
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#8b5cf6', width: 100, thickness: 4, spacing: 14 },
      border: { enabled: true, side: 'bottom', color: '#8b5cf6', width: 4, style: 'solid', radius: 0 },
      spacing: { padding: 22, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'photography-pro',
    archetype: 'centered-personal',
    name: 'Photography Pro',
    description: 'Sleek signature for photographers',
    category: 'creative',
    thumbnail: '/templates/photography-pro.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#0a0a0a',
      secondaryColor: '#737373',
      fontFamily: "'Times New Roman', serif",
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'line', color: '#0a0a0a', width: 28, thickness: 2, spacing: 12 },
      border: { enabled: false, side: 'left', color: '#0a0a0a', width: 2, style: 'solid', radius: 0 },
      spacing: { padding: 22, lineHeight: 1.6, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'music-industry',
    archetype: 'banner-bottom',
    name: 'Music Industry',
    description: 'Bold design for music professionals',
    category: 'creative',
    thumbnail: '/templates/music-industry.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
    ],
    defaultStyling: {
      primaryColor: '#b91c1c',
      secondaryColor: '#f59e0b',
      fontFamily: 'Verdana, sans-serif',
      fontSize: 'large',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#dc2626', width: 100, thickness: 4, spacing: 14 },
      border: { enabled: true, side: 'left', color: '#dc2626', width: 6, style: 'solid', radius: 2 },
      spacing: { padding: 24, lineHeight: 1.45, sectionGap: 4, iconGap: 8 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MINIMAL CATEGORY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'modern-minimal',
    archetype: 'accent-bar',
    name: 'Modern Minimal',
    description: 'Sleek, minimalist design with focus on essential information',
    category: 'minimal',
    thumbnail: '/templates/modern-minimal.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
    ],
    defaultStyling: {
      primaryColor: '#0a0a0a',
      secondaryColor: '#a3a3a3',
      fontFamily: 'Georgia, serif',
      fontSize: 'medium',
      layout: 'vertical',
      divider: { type: 'line', color: '#0a0a0a', width: 24, thickness: 1, spacing: 10 },
      border: { enabled: false, side: 'left', color: '#0a0a0a', width: 2, style: 'solid', radius: 0 },
      spacing: { padding: 20, lineHeight: 1.5, sectionGap: 3, iconGap: 6 },
    },
  },
  {
    id: 'compact-simple',
    archetype: 'accent-bar',
    name: 'Compact Simple',
    description: 'Space-efficient design for everyday use',
    category: 'minimal',
    thumbnail: '/templates/compact-simple.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
    ],
    defaultStyling: {
      primaryColor: '#27272a',
      secondaryColor: '#a1a1aa',
      fontFamily: 'Arial, sans-serif',
      fontSize: 'small',
      layout: 'compact',
      divider: { type: 'line', color: '#e4e4e7', width: 100, thickness: 1, spacing: 8 },
      border: { enabled: false, side: 'left', color: '#27272a', width: 2, style: 'solid', radius: 0 },
      spacing: { padding: 14, lineHeight: 1.35, sectionGap: 2, iconGap: 6 },
    },
  },
  {
    id: 'zen-simple',
    archetype: 'classic-stacked',
    name: 'Zen Simple',
    description: 'Ultra-clean design with maximum whitespace',
    category: 'minimal',
    thumbnail: '/templates/zen-simple.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
    ],
    defaultStyling: {
      primaryColor: '#44403c',
      secondaryColor: '#a8a29e',
      fontFamily: 'Georgia, serif',
      fontSize: 'small',
      layout: 'vertical',
      divider: { type: 'none', color: '#44403c', width: 100, thickness: 1, spacing: 8 },
      border: { enabled: false, side: 'left', color: '#44403c', width: 1, style: 'solid', radius: 0 },
      spacing: { padding: 18, lineHeight: 1.7, sectionGap: 3, iconGap: 6 },
    },
  },
  {
    id: 'scandinavian',
    archetype: 'classic-stacked',
    name: 'Scandinavian',
    description: 'Nordic-inspired clean aesthetic',
    category: 'minimal',
    thumbnail: '/templates/scandinavian.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#171717',
      secondaryColor: '#a3a3a3',
      fontFamily: 'Arial, sans-serif',
      fontSize: 'medium',
      layout: 'vertical',
      divider: { type: 'line', color: '#d4d4d4', width: 100, thickness: 1, spacing: 14 },
      border: { enabled: false, side: 'left', color: '#171717', width: 1, style: 'solid', radius: 0 },
      spacing: { padding: 22, lineHeight: 1.6, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'one-liner',
    archetype: 'accent-bar',
    name: 'One Liner',
    description: 'Everything on a single compact line',
    category: 'minimal',
    thumbnail: '/templates/one-liner.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
    ],
    defaultStyling: {
      primaryColor: '#111827',
      secondaryColor: '#6b7280',
      fontFamily: 'Arial, sans-serif',
      fontSize: 'small',
      layout: 'compact',
      divider: { type: 'none', color: '#111827', width: 100, thickness: 1, spacing: 4 },
      border: { enabled: false, side: 'left', color: '#111827', width: 1, style: 'solid', radius: 0 },
      spacing: { padding: 10, lineHeight: 1.25, sectionGap: 0, iconGap: 6 },
    },
  },
  {
    id: 'text-only',
    archetype: 'classic-stacked',
    name: 'Text Only',
    description: 'Pure typography, no decorations',
    category: 'minimal',
    thumbnail: '/templates/text-only.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
    ],
    defaultStyling: {
      primaryColor: '#0a0a0a',
      secondaryColor: '#737373',
      fontFamily: "'Times New Roman', serif",
      fontSize: 'medium',
      layout: 'vertical',
      divider: { type: 'none', color: '#0a0a0a', width: 100, thickness: 1, spacing: 8 },
      border: { enabled: false, side: 'left', color: '#0a0a0a', width: 1, style: 'solid', radius: 0 },
      spacing: { padding: 16, lineHeight: 1.5, sectionGap: 2, iconGap: 4 },
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CORPORATE CATEGORY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'corporate-bold',
    archetype: 'photo-divider',
    name: 'Corporate Bold',
    description: 'Strong, authoritative design for executive professionals',
    category: 'corporate',
    thumbnail: '/templates/corporate-bold.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
      { id: 'address', type: 'address', enabled: true, value: '', label: 'Address' },
    ],
    defaultStyling: {
      primaryColor: '#1e40af',
      secondaryColor: '#475569',
      fontFamily: 'Verdana, sans-serif',
      fontSize: 'large',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#1e40af', width: 75, thickness: 3, spacing: 14 },
      border: { enabled: true, side: 'left', color: '#1e40af', width: 6, style: 'solid', radius: 0 },
      spacing: { padding: 26, lineHeight: 1.55, sectionGap: 5, iconGap: 8 },
    },
  },
  {
    id: 'executive-prestige',
    archetype: 'executive-name-first',
    name: 'Executive Prestige',
    description: 'Premium design for C-suite executives',
    category: 'corporate',
    thumbnail: '/templates/executive-prestige.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
      { id: 'address', type: 'address', enabled: true, value: '', label: 'Address' },
    ],
    defaultStyling: {
      primaryColor: '#0c1733',
      secondaryColor: '#475569',
      fontFamily: 'Georgia, serif',
      fontSize: 'large',
      layout: 'horizontal',
      divider: { type: 'double', color: '#0c1733', width: 100, thickness: 1, spacing: 16 },
      border: { enabled: true, side: 'left', color: '#0c1733', width: 5, style: 'double', radius: 0 },
      spacing: { padding: 28, lineHeight: 1.7, sectionGap: 6, iconGap: 10 },
    },
  },
  {
    id: 'banking-finance',
    archetype: 'business-card-box',
    name: 'Banking & Finance',
    description: 'Trust-inspiring design for financial sector',
    category: 'corporate',
    thumbnail: '/templates/banking-finance.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'address', type: 'address', enabled: true, value: '', label: 'Address' },
    ],
    defaultStyling: {
      primaryColor: '#14532d',
      secondaryColor: '#4d7c0f',
      fontFamily: "'Times New Roman', serif",
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'line', color: '#14532d', width: 100, thickness: 1, spacing: 12 },
      border: { enabled: true, side: 'left', color: '#14532d', width: 4, style: 'solid', radius: 0 },
      spacing: { padding: 24, lineHeight: 1.55, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'healthcare-medical',
    archetype: 'photo-divider',
    name: 'Healthcare Medical',
    description: 'Professional design for medical practitioners',
    category: 'corporate',
    thumbnail: '/templates/healthcare-medical.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'address', type: 'address', enabled: true, value: '', label: 'Address' },
    ],
    defaultStyling: {
      primaryColor: '#0e7490',
      secondaryColor: '#22d3ee',
      fontFamily: 'Arial, sans-serif',
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#0e7490', width: 70, thickness: 2, spacing: 10 },
      border: { enabled: true, side: 'left', color: '#0e7490', width: 4, style: 'solid', radius: 4 },
      spacing: { padding: 22, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'real-estate',
    archetype: 'photo-divider',
    name: 'Real Estate',
    description: 'Polished design for property professionals',
    category: 'corporate',
    thumbnail: '/templates/real-estate.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#7c2d12',
      secondaryColor: '#d97706',
      fontFamily: 'Georgia, serif',
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'double', color: '#d97706', width: 60, thickness: 1, spacing: 12 },
      border: { enabled: true, side: 'left', color: '#7c2d12', width: 5, style: 'solid', radius: 0 },
      spacing: { padding: 24, lineHeight: 1.55, sectionGap: 5, iconGap: 8 },
    },
  },
  {
    id: 'insurance-agency',
    archetype: 'business-card-box',
    name: 'Insurance Agency',
    description: 'Trustworthy design for insurance professionals',
    category: 'corporate',
    thumbnail: '/templates/insurance-agency.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'address', type: 'address', enabled: true, value: '', label: 'Address' },
    ],
    defaultStyling: {
      primaryColor: '#1e3a8a',
      secondaryColor: '#60a5fa',
      fontFamily: 'Verdana, sans-serif',
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'line', color: '#1e3a8a', width: 100, thickness: 2, spacing: 12 },
      border: { enabled: true, side: 'all', color: '#1e3a8a', width: 1, style: 'solid', radius: 6 },
      spacing: { padding: 22, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'nonprofit-charity',
    archetype: 'card-shadow',
    name: 'Nonprofit Charity',
    description: 'Warm and approachable for nonprofits',
    category: 'corporate',
    thumbnail: '/templates/nonprofit-charity.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'website', type: 'website', enabled: true, value: '', label: 'Website' },
    ],
    defaultStyling: {
      primaryColor: '#15803d',
      secondaryColor: '#fbbf24',
      fontFamily: 'Georgia, serif',
      fontSize: 'medium',
      layout: 'horizontal',
      divider: { type: 'gradient', color: '#16a34a', width: 80, thickness: 2, spacing: 10 },
      border: { enabled: true, side: 'left', color: '#16a34a', width: 4, style: 'solid', radius: 8 },
      spacing: { padding: 22, lineHeight: 1.55, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'education-academic',
    archetype: 'classic-stacked',
    name: 'Education Academic',
    description: 'Scholarly design for educators and academics',
    category: 'corporate',
    thumbnail: '/templates/education-academic.png',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
      { id: 'address', type: 'address', enabled: true, value: '', label: 'Address' },
    ],
    defaultStyling: {
      primaryColor: '#7f1d1d',
      secondaryColor: '#a16207',
      fontFamily: "'Times New Roman', serif",
      fontSize: 'medium',
      layout: 'vertical',
      divider: { type: 'double', color: '#7f1d1d', width: 50, thickness: 1, spacing: 12 },
      border: { enabled: true, side: 'left', color: '#7f1d1d', width: 4, style: 'solid', radius: 0 },
      spacing: { padding: 22, lineHeight: 1.6, sectionGap: 4, iconGap: 8 },
    },
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // REPLY CATEGORY — short signatures for email threads
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'reply-essential',
    archetype: 'accent-bar',
    name: 'Reply Essential',
    description: 'Two-line reply signature with accent bar',
    category: 'reply',
    thumbnail: '/templates/reply-essential.png',
    previewVariant: 'reply',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
    ],
    defaultStyling: {
      primaryColor: '#0f172a', secondaryColor: '#64748b', fontFamily: 'Arial, sans-serif',
      fontSize: 'small', layout: 'compact',
      divider: { type: 'none', color: '#e5e7eb', width: 100, thickness: 1, spacing: 4 },
      border: { enabled: true, side: 'left', color: '#0f172a', width: 3, style: 'solid', radius: 2 },
      spacing: { padding: 12, lineHeight: 1.4, sectionGap: 2, iconGap: 6 },
    },
  },
  {
    id: 'reply-warm',
    archetype: 'accent-bar',
    name: 'Reply Warm',
    description: 'Friendly inline reply with brand accent',
    category: 'reply',
    thumbnail: '/templates/reply-warm.png',
    previewVariant: 'reply',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
    ],
    defaultStyling: {
      primaryColor: '#c2410c', secondaryColor: '#78716c', fontFamily: "'Georgia', serif",
      fontSize: 'small', layout: 'compact',
      divider: { type: 'none', color: '#e5e7eb', width: 100, thickness: 1, spacing: 4 },
      border: { enabled: true, side: 'left', color: '#c2410c', width: 3, style: 'solid', radius: 2 },
      spacing: { padding: 12, lineHeight: 1.4, sectionGap: 2, iconGap: 6 },
    },
  },
  {
    id: 'reply-mono',
    archetype: 'accent-bar',
    name: 'Reply Mono',
    description: 'Developer-style mono reply signature',
    category: 'reply',
    thumbnail: '/templates/reply-mono.png',
    previewVariant: 'reply',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
    ],
    defaultStyling: {
      primaryColor: '#10b981', secondaryColor: '#475569', fontFamily: "'Courier New', monospace",
      fontSize: 'small', layout: 'compact',
      divider: { type: 'none', color: '#10b981', width: 100, thickness: 1, spacing: 4 },
      border: { enabled: true, side: 'left', color: '#10b981', width: 3, style: 'solid', radius: 2 },
      spacing: { padding: 12, lineHeight: 1.4, sectionGap: 2, iconGap: 6 },
    },
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // EXTRA LAYOUT VARIANTS — showcase richer card layouts
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'card-stack-modern',
    archetype: 'card-shadow',
    name: 'Stacked Card',
    description: 'Profile-card layout with gradient header',
    category: 'modern',
    thumbnail: '/templates/card-stack-modern.png',
    previewVariant: 'card-stack',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
    ],
    defaultStyling: {
      primaryColor: '#6366f1', secondaryColor: '#475569', fontFamily: 'Inter, sans-serif',
      fontSize: 'medium', layout: 'horizontal',
      divider: { type: 'gradient', color: '#6366f1', width: 80, thickness: 2, spacing: 8 },
      border: { enabled: true, side: 'all', color: '#6366f1', width: 1, style: 'solid', radius: 12 },
      spacing: { padding: 18, lineHeight: 1.45, sectionGap: 5, iconGap: 8 },
    },
  },
  {
    id: 'split-creative',
    archetype: 'photo-divider',
    name: 'Split Profile',
    description: 'Bold color block paired with portrait',
    category: 'creative',
    thumbnail: '/templates/split-creative.png',
    previewVariant: 'split',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
    ],
    defaultStyling: {
      primaryColor: '#db2777', secondaryColor: '#7c3aed', fontFamily: "'Helvetica Neue', sans-serif",
      fontSize: 'medium', layout: 'horizontal',
      divider: { type: 'none', color: '#db2777', width: 100, thickness: 1, spacing: 6 },
      border: { enabled: true, side: 'all', color: '#db2777', width: 1, style: 'solid', radius: 10 },
      spacing: { padding: 16, lineHeight: 1.4, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'centered-minimal',
    archetype: 'centered-personal',
    name: 'Centered Card',
    description: 'Centered portrait with editorial feel',
    category: 'minimal',
    thumbnail: '/templates/centered-minimal.png',
    previewVariant: 'centered',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
    ],
    defaultStyling: {
      primaryColor: '#1c1917', secondaryColor: '#78716c', fontFamily: "'Playfair Display', serif",
      fontSize: 'medium', layout: 'vertical',
      divider: { type: 'line', color: '#1c1917', width: 40, thickness: 1, spacing: 10 },
      border: { enabled: true, side: 'all', color: '#e7e5e4', width: 1, style: 'solid', radius: 8 },
      spacing: { padding: 20, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'badge-pro',
    archetype: 'photo-divider',
    name: 'Badge Pill',
    description: 'Avatar pill with soft tinted backdrop',
    category: 'professional',
    thumbnail: '/templates/badge-pro.png',
    previewVariant: 'badge',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
    ],
    defaultStyling: {
      primaryColor: '#1e40af', secondaryColor: '#475569', fontFamily: 'Inter, sans-serif',
      fontSize: 'medium', layout: 'horizontal',
      divider: { type: 'none', color: '#1e40af', width: 100, thickness: 1, spacing: 6 },
      border: { enabled: false, side: 'left', color: '#1e40af', width: 0, style: 'solid', radius: 12 },
      spacing: { padding: 16, lineHeight: 1.45, sectionGap: 4, iconGap: 8 },
    },
  },
  {
    id: 'split-corporate',
    archetype: 'two-column-split',
    name: 'Executive Split',
    description: 'Corporate split-card with portrait panel',
    category: 'corporate',
    thumbnail: '/templates/split-corporate.png',
    previewVariant: 'split',
    defaultSections: [
      { id: 'name', type: 'name', enabled: true, value: '', label: 'Full Name' },
      { id: 'title', type: 'title', enabled: true, value: '', label: 'Job Title' },
      { id: 'company', type: 'company', enabled: true, value: '', label: 'Company' },
      { id: 'phone', type: 'phone', enabled: true, value: '', label: 'Phone' },
      { id: 'email', type: 'email', enabled: true, value: '', label: 'Email' },
    ],
    defaultStyling: {
      primaryColor: '#0f1b3d', secondaryColor: '#475569', fontFamily: 'Arial, sans-serif',
      fontSize: 'medium', layout: 'horizontal',
      divider: { type: 'line', color: '#0f1b3d', width: 100, thickness: 1, spacing: 8 },
      border: { enabled: true, side: 'all', color: '#0f1b3d', width: 1, style: 'solid', radius: 8 },
      spacing: { padding: 18, lineHeight: 1.5, sectionGap: 4, iconGap: 8 },
    },
  },
];

export const getTemplateById = (id: string): SignatureTemplate | undefined => {
  return signatureTemplates.find(template => template.id === id);
};

export const getTemplatesByCategory = (category: SignatureTemplate['category']): SignatureTemplate[] => {
  return signatureTemplates.filter(template => template.category === category);
};
