import { getPrintDemo, printDemoItem } from "../src/lib/showcase-print";
import { toEditableContent } from "../src/lib/print-library/editable";
import { approvePrintDemoContent } from "../src/lib/print-library/demo-approve";
const def = getPrintDemo("pd-media-genai")!;
const item = printDemoItem(def)!;
const base: any = toEditableContent(item);
console.log("kind", item.kind);
console.log("before", base.modules.map((m: any) => m.kind));
const out: any = approvePrintDemoContent(item.kind, base);
console.log("after", out.modules.map((m: any) => m.kind));
