/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SocialRouteImport } from './routes/social'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LogohubRouteImport } from './routes/logohub'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ImageryRouteImport } from './routes/imagery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialIndexRouteImport } from './routes/social.index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as DecksIndexRouteImport } from './routes/decks.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TestPrintHeroRouteImport } from './routes/test.print-hero'
import { Route as TestPrintDndRouteImport } from './routes/test.print-dnd'
import { Route as SocialPresetsRouteImport } from './routes/social.presets'
import { Route as SocialNewRouteImport } from './routes/social.new'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as LibraryPrintRouteImport } from './routes/library.print'
import { Route as LibraryMyRouteImport } from './routes/library.my'
import { Route as LibraryImportedRouteImport } from './routes/library.imported'
import { Route as KnowledgeOracleRouteImport } from './routes/knowledge.oracle'
import { Route as KnowledgeNewRouteImport } from './routes/knowledge.new'
import { Route as KnowledgeAskRouteImport } from './routes/knowledge.ask'
import { Route as KnowledgeEntryIdRouteImport } from './routes/knowledge.$entryId'
import { Route as EventsPresetsRouteImport } from './routes/events.presets'
import { Route as EventsNextRouteImport } from './routes/events.next'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as DevSlidestageDemoRouteImport } from './routes/dev.slidestage-demo'
import { Route as DecksImportRouteImport } from './routes/decks.import'
import { Route as BriefNewRouteImport } from './routes/brief.new'
import { Route as BriefDeckIdRouteImport } from './routes/brief.$deckId'
import { Route as AssetSpotlightPreviewRouteImport } from './routes/asset.spotlight-preview'
import { Route as AssetNewRouteImport } from './routes/asset.new'
import { Route as AssetAssetIdRouteImport } from './routes/asset.$assetId'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTranslationRouteImport } from './routes/admin.translation'
import { Route as AdminPrintLibraryRouteImport } from './routes/admin.print-library'
import { Route as AdminPdfIngestRouteImport } from './routes/admin.pdf-ingest'
import { Route as AdminOracleRouteImport } from './routes/admin.oracle'
import { Route as AdminLogohubRouteImport } from './routes/admin.logohub'
import { Route as AdminKnowledgeHubRouteImport } from './routes/admin.knowledge-hub'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminImageryAnalyticsRouteImport } from './routes/admin.imagery-analytics'
import { Route as AdminImageryRouteImport } from './routes/admin.imagery'
import { Route as AdminIconStudioRouteImport } from './routes/admin.icon-studio'
import { Route as AdminGloballinkShareRouteImport } from './routes/admin.globallink-share'
import { Route as AdminGloballinkRouteImport } from './routes/admin.globallink'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminBrandAssetsRouteImport } from './routes/admin.brand-assets'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAbRouteImport } from './routes/admin.ab'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as KnowledgeBrandGuidesIndexRouteImport } from './routes/knowledge.brand-guides.index'
import { Route as DecksDeckIdIndexRouteImport } from './routes/decks.$deckId.index'
import { Route as SocialDemoPlaybookIdRouteImport } from './routes/social.demo.$playbookId'
import { Route as LibraryImportedMastersRouteImport } from './routes/library.imported_.masters'
import { Route as KnowledgeBrandGuidesNext2026BuildRouteImport } from './routes/knowledge.brand-guides.next-2026-build'
import { Route as KnowledgeBrandGuidesNext2026RouteImport } from './routes/knowledge.brand-guides.next-2026'
import { Route as KnowledgeBrandGuidesSlugRouteImport } from './routes/knowledge.brand-guides.$slug'
import { Route as EventsNextBadgesRouteImport } from './routes/events.next_.badges'
import { Route as EventsDemoPlaybookIdRouteImport } from './routes/events.demo.$playbookId'
import { Route as DecksDeckIdPrintRouteImport } from './routes/decks.$deckId.print'
import { Route as DecksDeckIdPresentRouteImport } from './routes/decks.$deckId.present'
import { Route as DecksDeckIdExportRouteImport } from './routes/decks.$deckId.export'
import { Route as DecksDeckIdDocumentRouteImport } from './routes/decks.$deckId.document'
import { Route as ApiPublicPdfIndexProxyRouteImport } from './routes/api/public/pdf-index-proxy'
import { Route as ApiPublicBrandhubSeedProxyRouteImport } from './routes/api/public/brandhub-seed-proxy'
import { Route as AdminCampaignsKitRouteImport } from './routes/admin.campaigns.kit'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LogohubRoute = LogohubRouteImport.update({
  id: '/logohub',
  path: '/logohub',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageryRoute = ImageryRouteImport.update({
  id: '/imagery',
  path: '/imagery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SocialRoute,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TestPrintHeroRoute = TestPrintHeroRouteImport.update({
  id: '/test/print-hero',
  path: '/test/print-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const TestPrintDndRoute = TestPrintDndRouteImport.update({
  id: '/test/print-dnd',
  path: '/test/print-dnd',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPresetsRoute = SocialPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => SocialRoute,
} as any)
const SocialNewRoute = SocialNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SocialRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPrintRoute = LibraryPrintRouteImport.update({
  id: '/library/print',
  path: '/library/print',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMyRoute = LibraryMyRouteImport.update({
  id: '/library/my',
  path: '/library/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryImportedRoute = LibraryImportedRouteImport.update({
  id: '/library/imported',
  path: '/library/imported',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeOracleRoute = KnowledgeOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeNewRoute = KnowledgeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeAskRoute = KnowledgeAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeEntryIdRoute = KnowledgeEntryIdRouteImport.update({
  id: '/$entryId',
  path: '/$entryId',
  getParentRoute: () => KnowledgeRoute,
} as any)
const EventsPresetsRoute = EventsPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => EventsRoute,
} as any)
const EventsNextRoute = EventsNextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => EventsRoute,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EventsRoute,
} as any)
const DevSlidestageDemoRoute = DevSlidestageDemoRouteImport.update({
  id: '/dev/slidestage-demo',
  path: '/dev/slidestage-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksImportRoute = DecksImportRouteImport.update({
  id: '/decks/import',
  path: '/decks/import',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefNewRoute = BriefNewRouteImport.update({
  id: '/brief/new',
  path: '/brief/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefDeckIdRoute = BriefDeckIdRouteImport.update({
  id: '/brief/$deckId',
  path: '/brief/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetSpotlightPreviewRoute = AssetSpotlightPreviewRouteImport.update({
  id: '/asset/spotlight-preview',
  path: '/asset/spotlight-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetNewRoute = AssetNewRouteImport.update({
  id: '/asset/new',
  path: '/asset/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetAssetIdRoute = AssetAssetIdRouteImport.update({
  id: '/asset/$assetId',
  path: '/asset/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationRoute = AdminTranslationRouteImport.update({
  id: '/translation',
  path: '/translation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrintLibraryRoute = AdminPrintLibraryRouteImport.update({
  id: '/print-library',
  path: '/print-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPdfIngestRoute = AdminPdfIngestRouteImport.update({
  id: '/pdf-ingest',
  path: '/pdf-ingest',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOracleRoute = AdminOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogohubRoute = AdminLogohubRouteImport.update({
  id: '/logohub',
  path: '/logohub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeHubRoute = AdminKnowledgeHubRouteImport.update({
  id: '/knowledge-hub',
  path: '/knowledge-hub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImageryAnalyticsRoute = AdminImageryAnalyticsRouteImport.update({
  id: '/imagery-analytics',
  path: '/imagery-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImageryRoute = AdminImageryRouteImport.update({
  id: '/imagery',
  path: '/imagery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIconStudioRoute = AdminIconStudioRouteImport.update({
  id: '/icon-studio',
  path: '/icon-studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGloballinkShareRoute = AdminGloballinkShareRouteImport.update({
  id: '/globallink-share',
  path: '/globallink-share',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGloballinkRoute = AdminGloballinkRouteImport.update({
  id: '/globallink',
  path: '/globallink',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandAssetsRoute = AdminBrandAssetsRouteImport.update({
  id: '/brand-assets',
  path: '/brand-assets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbRoute = AdminAbRouteImport.update({
  id: '/ab',
  path: '/ab',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const KnowledgeBrandGuidesIndexRoute =
  KnowledgeBrandGuidesIndexRouteImport.update({
    id: '/brand-guides/',
    path: '/brand-guides/',
    getParentRoute: () => KnowledgeRoute,
  } as any)
const DecksDeckIdIndexRoute = DecksDeckIdIndexRouteImport.update({
  id: '/decks/$deckId/',
  path: '/decks/$deckId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialDemoPlaybookIdRoute = SocialDemoPlaybookIdRouteImport.update({
  id: '/demo/$playbookId',
  path: '/demo/$playbookId',
  getParentRoute: () => SocialRoute,
} as any)
const LibraryImportedMastersRoute = LibraryImportedMastersRouteImport.update({
  id: '/library/imported_/masters',
  path: '/library/imported/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBrandGuidesNext2026BuildRoute =
  KnowledgeBrandGuidesNext2026BuildRouteImport.update({
    id: '/brand-guides/next-2026-build',
    path: '/brand-guides/next-2026-build',
    getParentRoute: () => KnowledgeRoute,
  } as any)
const KnowledgeBrandGuidesNext2026Route =
  KnowledgeBrandGuidesNext2026RouteImport.update({
    id: '/brand-guides/next-2026',
    path: '/brand-guides/next-2026',
    getParentRoute: () => KnowledgeRoute,
  } as any)
const KnowledgeBrandGuidesSlugRoute =
  KnowledgeBrandGuidesSlugRouteImport.update({
    id: '/brand-guides/$slug',
    path: '/brand-guides/$slug',
    getParentRoute: () => KnowledgeRoute,
  } as any)
const EventsNextBadgesRoute = EventsNextBadgesRouteImport.update({
  id: '/next_/badges',
  path: '/next/badges',
  getParentRoute: () => EventsRoute,
} as any)
const EventsDemoPlaybookIdRoute = EventsDemoPlaybookIdRouteImport.update({
  id: '/demo/$playbookId',
  path: '/demo/$playbookId',
  getParentRoute: () => EventsRoute,
} as any)
const DecksDeckIdPrintRoute = DecksDeckIdPrintRouteImport.update({
  id: '/decks/$deckId/print',
  path: '/decks/$deckId/print',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdPresentRoute = DecksDeckIdPresentRouteImport.update({
  id: '/decks/$deckId/present',
  path: '/decks/$deckId/present',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdExportRoute = DecksDeckIdExportRouteImport.update({
  id: '/decks/$deckId/export',
  path: '/decks/$deckId/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdDocumentRoute = DecksDeckIdDocumentRouteImport.update({
  id: '/decks/$deckId/document',
  path: '/decks/$deckId/document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPdfIndexProxyRoute = ApiPublicPdfIndexProxyRouteImport.update({
  id: '/api/public/pdf-index-proxy',
  path: '/api/public/pdf-index-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandhubSeedProxyRoute =
  ApiPublicBrandhubSeedProxyRouteImport.update({
    id: '/api/public/brandhub-seed-proxy',
    path: '/api/public/brandhub-seed-proxy',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCampaignsKitRoute = AdminCampaignsKitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => AdminCampaignsRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/faq': typeof FaqRoute
  '/imagery': typeof ImageryRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/logohub': typeof LogohubRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/social': typeof SocialRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ab': typeof AdminAbRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brand-assets': typeof AdminBrandAssetsRoute
  '/admin/campaigns': typeof AdminCampaignsRouteWithChildren
  '/admin/globallink': typeof AdminGloballinkRoute
  '/admin/globallink-share': typeof AdminGloballinkShareRoute
  '/admin/icon-studio': typeof AdminIconStudioRoute
  '/admin/imagery': typeof AdminImageryRoute
  '/admin/imagery-analytics': typeof AdminImageryAnalyticsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/knowledge-hub': typeof AdminKnowledgeHubRoute
  '/admin/logohub': typeof AdminLogohubRoute
  '/admin/oracle': typeof AdminOracleRoute
  '/admin/pdf-ingest': typeof AdminPdfIngestRoute
  '/admin/print-library': typeof AdminPrintLibraryRoute
  '/admin/translation': typeof AdminTranslationRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/asset/$assetId': typeof AssetAssetIdRoute
  '/asset/new': typeof AssetNewRoute
  '/asset/spotlight-preview': typeof AssetSpotlightPreviewRoute
  '/brief/$deckId': typeof BriefDeckIdRoute
  '/brief/new': typeof BriefNewRoute
  '/decks/import': typeof DecksImportRoute
  '/dev/slidestage-demo': typeof DevSlidestageDemoRoute
  '/events/new': typeof EventsNewRoute
  '/events/next': typeof EventsNextRoute
  '/events/presets': typeof EventsPresetsRoute
  '/knowledge/$entryId': typeof KnowledgeEntryIdRoute
  '/knowledge/ask': typeof KnowledgeAskRoute
  '/knowledge/new': typeof KnowledgeNewRoute
  '/knowledge/oracle': typeof KnowledgeOracleRoute
  '/library/imported': typeof LibraryImportedRoute
  '/library/my': typeof LibraryMyRoute
  '/library/print': typeof LibraryPrintRoute
  '/share/$token': typeof ShareTokenRoute
  '/social/new': typeof SocialNewRoute
  '/social/presets': typeof SocialPresetsRoute
  '/test/print-dnd': typeof TestPrintDndRoute
  '/test/print-hero': typeof TestPrintHeroRoute
  '/admin/': typeof AdminIndexRoute
  '/decks/': typeof DecksIndexRoute
  '/events/': typeof EventsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/social/': typeof SocialIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/campaigns/kit': typeof AdminCampaignsKitRoute
  '/api/public/brandhub-seed-proxy': typeof ApiPublicBrandhubSeedProxyRoute
  '/api/public/pdf-index-proxy': typeof ApiPublicPdfIndexProxyRoute
  '/decks/$deckId/document': typeof DecksDeckIdDocumentRoute
  '/decks/$deckId/export': typeof DecksDeckIdExportRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/decks/$deckId/print': typeof DecksDeckIdPrintRoute
  '/events/demo/$playbookId': typeof EventsDemoPlaybookIdRoute
  '/events/next/badges': typeof EventsNextBadgesRoute
  '/knowledge/brand-guides/$slug': typeof KnowledgeBrandGuidesSlugRoute
  '/knowledge/brand-guides/next-2026': typeof KnowledgeBrandGuidesNext2026Route
  '/knowledge/brand-guides/next-2026-build': typeof KnowledgeBrandGuidesNext2026BuildRoute
  '/library/imported/masters': typeof LibraryImportedMastersRoute
  '/social/demo/$playbookId': typeof SocialDemoPlaybookIdRoute
  '/decks/$deckId/': typeof DecksDeckIdIndexRoute
  '/knowledge/brand-guides/': typeof KnowledgeBrandGuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/imagery': typeof ImageryRoute
  '/logohub': typeof LogohubRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/templates': typeof TemplatesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ab': typeof AdminAbRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brand-assets': typeof AdminBrandAssetsRoute
  '/admin/campaigns': typeof AdminCampaignsRouteWithChildren
  '/admin/globallink': typeof AdminGloballinkRoute
  '/admin/globallink-share': typeof AdminGloballinkShareRoute
  '/admin/icon-studio': typeof AdminIconStudioRoute
  '/admin/imagery': typeof AdminImageryRoute
  '/admin/imagery-analytics': typeof AdminImageryAnalyticsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/knowledge-hub': typeof AdminKnowledgeHubRoute
  '/admin/logohub': typeof AdminLogohubRoute
  '/admin/oracle': typeof AdminOracleRoute
  '/admin/pdf-ingest': typeof AdminPdfIngestRoute
  '/admin/print-library': typeof AdminPrintLibraryRoute
  '/admin/translation': typeof AdminTranslationRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/asset/$assetId': typeof AssetAssetIdRoute
  '/asset/new': typeof AssetNewRoute
  '/asset/spotlight-preview': typeof AssetSpotlightPreviewRoute
  '/brief/$deckId': typeof BriefDeckIdRoute
  '/brief/new': typeof BriefNewRoute
  '/decks/import': typeof DecksImportRoute
  '/dev/slidestage-demo': typeof DevSlidestageDemoRoute
  '/events/new': typeof EventsNewRoute
  '/events/next': typeof EventsNextRoute
  '/events/presets': typeof EventsPresetsRoute
  '/knowledge/$entryId': typeof KnowledgeEntryIdRoute
  '/knowledge/ask': typeof KnowledgeAskRoute
  '/knowledge/new': typeof KnowledgeNewRoute
  '/knowledge/oracle': typeof KnowledgeOracleRoute
  '/library/imported': typeof LibraryImportedRoute
  '/library/my': typeof LibraryMyRoute
  '/library/print': typeof LibraryPrintRoute
  '/share/$token': typeof ShareTokenRoute
  '/social/new': typeof SocialNewRoute
  '/social/presets': typeof SocialPresetsRoute
  '/test/print-dnd': typeof TestPrintDndRoute
  '/test/print-hero': typeof TestPrintHeroRoute
  '/admin': typeof AdminIndexRoute
  '/decks': typeof DecksIndexRoute
  '/events': typeof EventsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/library': typeof LibraryIndexRoute
  '/social': typeof SocialIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/campaigns/kit': typeof AdminCampaignsKitRoute
  '/api/public/brandhub-seed-proxy': typeof ApiPublicBrandhubSeedProxyRoute
  '/api/public/pdf-index-proxy': typeof ApiPublicPdfIndexProxyRoute
  '/decks/$deckId/document': typeof DecksDeckIdDocumentRoute
  '/decks/$deckId/export': typeof DecksDeckIdExportRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/decks/$deckId/print': typeof DecksDeckIdPrintRoute
  '/events/demo/$playbookId': typeof EventsDemoPlaybookIdRoute
  '/events/next/badges': typeof EventsNextBadgesRoute
  '/knowledge/brand-guides/$slug': typeof KnowledgeBrandGuidesSlugRoute
  '/knowledge/brand-guides/next-2026': typeof KnowledgeBrandGuidesNext2026Route
  '/knowledge/brand-guides/next-2026-build': typeof KnowledgeBrandGuidesNext2026BuildRoute
  '/library/imported/masters': typeof LibraryImportedMastersRoute
  '/social/demo/$playbookId': typeof SocialDemoPlaybookIdRoute
  '/decks/$deckId': typeof DecksDeckIdIndexRoute
  '/knowledge/brand-guides': typeof KnowledgeBrandGuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/faq': typeof FaqRoute
  '/imagery': typeof ImageryRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/logohub': typeof LogohubRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/social': typeof SocialRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ab': typeof AdminAbRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brand-assets': typeof AdminBrandAssetsRoute
  '/admin/campaigns': typeof AdminCampaignsRouteWithChildren
  '/admin/globallink': typeof AdminGloballinkRoute
  '/admin/globallink-share': typeof AdminGloballinkShareRoute
  '/admin/icon-studio': typeof AdminIconStudioRoute
  '/admin/imagery': typeof AdminImageryRoute
  '/admin/imagery-analytics': typeof AdminImageryAnalyticsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/knowledge-hub': typeof AdminKnowledgeHubRoute
  '/admin/logohub': typeof AdminLogohubRoute
  '/admin/oracle': typeof AdminOracleRoute
  '/admin/pdf-ingest': typeof AdminPdfIngestRoute
  '/admin/print-library': typeof AdminPrintLibraryRoute
  '/admin/translation': typeof AdminTranslationRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/asset/$assetId': typeof AssetAssetIdRoute
  '/asset/new': typeof AssetNewRoute
  '/asset/spotlight-preview': typeof AssetSpotlightPreviewRoute
  '/brief/$deckId': typeof BriefDeckIdRoute
  '/brief/new': typeof BriefNewRoute
  '/decks/import': typeof DecksImportRoute
  '/dev/slidestage-demo': typeof DevSlidestageDemoRoute
  '/events/new': typeof EventsNewRoute
  '/events/next': typeof EventsNextRoute
  '/events/presets': typeof EventsPresetsRoute
  '/knowledge/$entryId': typeof KnowledgeEntryIdRoute
  '/knowledge/ask': typeof KnowledgeAskRoute
  '/knowledge/new': typeof KnowledgeNewRoute
  '/knowledge/oracle': typeof KnowledgeOracleRoute
  '/library/imported': typeof LibraryImportedRoute
  '/library/my': typeof LibraryMyRoute
  '/library/print': typeof LibraryPrintRoute
  '/share/$token': typeof ShareTokenRoute
  '/social/new': typeof SocialNewRoute
  '/social/presets': typeof SocialPresetsRoute
  '/test/print-dnd': typeof TestPrintDndRoute
  '/test/print-hero': typeof TestPrintHeroRoute
  '/admin/': typeof AdminIndexRoute
  '/decks/': typeof DecksIndexRoute
  '/events/': typeof EventsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/social/': typeof SocialIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/campaigns/kit': typeof AdminCampaignsKitRoute
  '/api/public/brandhub-seed-proxy': typeof ApiPublicBrandhubSeedProxyRoute
  '/api/public/pdf-index-proxy': typeof ApiPublicPdfIndexProxyRoute
  '/decks/$deckId/document': typeof DecksDeckIdDocumentRoute
  '/decks/$deckId/export': typeof DecksDeckIdExportRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/decks/$deckId/print': typeof DecksDeckIdPrintRoute
  '/events/demo/$playbookId': typeof EventsDemoPlaybookIdRoute
  '/events/next_/badges': typeof EventsNextBadgesRoute
  '/knowledge/brand-guides/$slug': typeof KnowledgeBrandGuidesSlugRoute
  '/knowledge/brand-guides/next-2026': typeof KnowledgeBrandGuidesNext2026Route
  '/knowledge/brand-guides/next-2026-build': typeof KnowledgeBrandGuidesNext2026BuildRoute
  '/library/imported_/masters': typeof LibraryImportedMastersRoute
  '/social/demo/$playbookId': typeof SocialDemoPlaybookIdRoute
  '/decks/$deckId/': typeof DecksDeckIdIndexRoute
  '/knowledge/brand-guides/': typeof KnowledgeBrandGuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/analytics'
    | '/atlas'
    | '/auth'
    | '/events'
    | '/faq'
    | '/imagery'
    | '/knowledge'
    | '/logohub'
    | '/mcp'
    | '/reset-password'
    | '/social'
    | '/templates'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ab'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/brand-assets'
    | '/admin/campaigns'
    | '/admin/globallink'
    | '/admin/globallink-share'
    | '/admin/icon-studio'
    | '/admin/imagery'
    | '/admin/imagery-analytics'
    | '/admin/knowledge'
    | '/admin/knowledge-hub'
    | '/admin/logohub'
    | '/admin/oracle'
    | '/admin/pdf-ingest'
    | '/admin/print-library'
    | '/admin/translation'
    | '/admin/users'
    | '/api/chat'
    | '/asset/$assetId'
    | '/asset/new'
    | '/asset/spotlight-preview'
    | '/brief/$deckId'
    | '/brief/new'
    | '/decks/import'
    | '/dev/slidestage-demo'
    | '/events/new'
    | '/events/next'
    | '/events/presets'
    | '/knowledge/$entryId'
    | '/knowledge/ask'
    | '/knowledge/new'
    | '/knowledge/oracle'
    | '/library/imported'
    | '/library/my'
    | '/library/print'
    | '/share/$token'
    | '/social/new'
    | '/social/presets'
    | '/test/print-dnd'
    | '/test/print-hero'
    | '/admin/'
    | '/decks/'
    | '/events/'
    | '/knowledge/'
    | '/library/'
    | '/social/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/campaigns/kit'
    | '/api/public/brandhub-seed-proxy'
    | '/api/public/pdf-index-proxy'
    | '/decks/$deckId/document'
    | '/decks/$deckId/export'
    | '/decks/$deckId/present'
    | '/decks/$deckId/print'
    | '/events/demo/$playbookId'
    | '/events/next/badges'
    | '/knowledge/brand-guides/$slug'
    | '/knowledge/brand-guides/next-2026'
    | '/knowledge/brand-guides/next-2026-build'
    | '/library/imported/masters'
    | '/social/demo/$playbookId'
    | '/decks/$deckId/'
    | '/knowledge/brand-guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/atlas'
    | '/auth'
    | '/faq'
    | '/imagery'
    | '/logohub'
    | '/mcp'
    | '/reset-password'
    | '/templates'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ab'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/brand-assets'
    | '/admin/campaigns'
    | '/admin/globallink'
    | '/admin/globallink-share'
    | '/admin/icon-studio'
    | '/admin/imagery'
    | '/admin/imagery-analytics'
    | '/admin/knowledge'
    | '/admin/knowledge-hub'
    | '/admin/logohub'
    | '/admin/oracle'
    | '/admin/pdf-ingest'
    | '/admin/print-library'
    | '/admin/translation'
    | '/admin/users'
    | '/api/chat'
    | '/asset/$assetId'
    | '/asset/new'
    | '/asset/spotlight-preview'
    | '/brief/$deckId'
    | '/brief/new'
    | '/decks/import'
    | '/dev/slidestage-demo'
    | '/events/new'
    | '/events/next'
    | '/events/presets'
    | '/knowledge/$entryId'
    | '/knowledge/ask'
    | '/knowledge/new'
    | '/knowledge/oracle'
    | '/library/imported'
    | '/library/my'
    | '/library/print'
    | '/share/$token'
    | '/social/new'
    | '/social/presets'
    | '/test/print-dnd'
    | '/test/print-hero'
    | '/admin'
    | '/decks'
    | '/events'
    | '/knowledge'
    | '/library'
    | '/social'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/campaigns/kit'
    | '/api/public/brandhub-seed-proxy'
    | '/api/public/pdf-index-proxy'
    | '/decks/$deckId/document'
    | '/decks/$deckId/export'
    | '/decks/$deckId/present'
    | '/decks/$deckId/print'
    | '/events/demo/$playbookId'
    | '/events/next/badges'
    | '/knowledge/brand-guides/$slug'
    | '/knowledge/brand-guides/next-2026'
    | '/knowledge/brand-guides/next-2026-build'
    | '/library/imported/masters'
    | '/social/demo/$playbookId'
    | '/decks/$deckId'
    | '/knowledge/brand-guides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/analytics'
    | '/atlas'
    | '/auth'
    | '/events'
    | '/faq'
    | '/imagery'
    | '/knowledge'
    | '/logohub'
    | '/mcp'
    | '/reset-password'
    | '/social'
    | '/templates'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ab'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/brand-assets'
    | '/admin/campaigns'
    | '/admin/globallink'
    | '/admin/globallink-share'
    | '/admin/icon-studio'
    | '/admin/imagery'
    | '/admin/imagery-analytics'
    | '/admin/knowledge'
    | '/admin/knowledge-hub'
    | '/admin/logohub'
    | '/admin/oracle'
    | '/admin/pdf-ingest'
    | '/admin/print-library'
    | '/admin/translation'
    | '/admin/users'
    | '/api/chat'
    | '/asset/$assetId'
    | '/asset/new'
    | '/asset/spotlight-preview'
    | '/brief/$deckId'
    | '/brief/new'
    | '/decks/import'
    | '/dev/slidestage-demo'
    | '/events/new'
    | '/events/next'
    | '/events/presets'
    | '/knowledge/$entryId'
    | '/knowledge/ask'
    | '/knowledge/new'
    | '/knowledge/oracle'
    | '/library/imported'
    | '/library/my'
    | '/library/print'
    | '/share/$token'
    | '/social/new'
    | '/social/presets'
    | '/test/print-dnd'
    | '/test/print-hero'
    | '/admin/'
    | '/decks/'
    | '/events/'
    | '/knowledge/'
    | '/library/'
    | '/social/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/campaigns/kit'
    | '/api/public/brandhub-seed-proxy'
    | '/api/public/pdf-index-proxy'
    | '/decks/$deckId/document'
    | '/decks/$deckId/export'
    | '/decks/$deckId/present'
    | '/decks/$deckId/print'
    | '/events/demo/$playbookId'
    | '/events/next_/badges'
    | '/knowledge/brand-guides/$slug'
    | '/knowledge/brand-guides/next-2026'
    | '/knowledge/brand-guides/next-2026-build'
    | '/library/imported_/masters'
    | '/social/demo/$playbookId'
    | '/decks/$deckId/'
    | '/knowledge/brand-guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AtlasRoute: typeof AtlasRoute
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRouteWithChildren
  FaqRoute: typeof FaqRoute
  ImageryRoute: typeof ImageryRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LogohubRoute: typeof LogohubRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SocialRoute: typeof SocialRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  AssetAssetIdRoute: typeof AssetAssetIdRoute
  AssetNewRoute: typeof AssetNewRoute
  AssetSpotlightPreviewRoute: typeof AssetSpotlightPreviewRoute
  BriefDeckIdRoute: typeof BriefDeckIdRoute
  BriefNewRoute: typeof BriefNewRoute
  DecksImportRoute: typeof DecksImportRoute
  DevSlidestageDemoRoute: typeof DevSlidestageDemoRoute
  LibraryImportedRoute: typeof LibraryImportedRoute
  LibraryMyRoute: typeof LibraryMyRoute
  LibraryPrintRoute: typeof LibraryPrintRoute
  ShareTokenRoute: typeof ShareTokenRoute
  TestPrintDndRoute: typeof TestPrintDndRoute
  TestPrintHeroRoute: typeof TestPrintHeroRoute
  DecksIndexRoute: typeof DecksIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBrandhubSeedProxyRoute: typeof ApiPublicBrandhubSeedProxyRoute
  ApiPublicPdfIndexProxyRoute: typeof ApiPublicPdfIndexProxyRoute
  DecksDeckIdDocumentRoute: typeof DecksDeckIdDocumentRoute
  DecksDeckIdExportRoute: typeof DecksDeckIdExportRoute
  DecksDeckIdPresentRoute: typeof DecksDeckIdPresentRoute
  DecksDeckIdPrintRoute: typeof DecksDeckIdPrintRoute
  LibraryImportedMastersRoute: typeof LibraryImportedMastersRoute
  DecksDeckIdIndexRoute: typeof DecksDeckIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logohub': {
      id: '/logohub'
      path: '/logohub'
      fullPath: '/logohub'
      preLoaderRoute: typeof LogohubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagery': {
      id: '/imagery'
      path: '/imagery'
      fullPath: '/imagery'
      preLoaderRoute: typeof ImageryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof SocialRoute
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/decks/': {
      id: '/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/test/print-hero': {
      id: '/test/print-hero'
      path: '/test/print-hero'
      fullPath: '/test/print-hero'
      preLoaderRoute: typeof TestPrintHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/print-dnd': {
      id: '/test/print-dnd'
      path: '/test/print-dnd'
      fullPath: '/test/print-dnd'
      preLoaderRoute: typeof TestPrintDndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/presets': {
      id: '/social/presets'
      path: '/presets'
      fullPath: '/social/presets'
      preLoaderRoute: typeof SocialPresetsRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/new': {
      id: '/social/new'
      path: '/new'
      fullPath: '/social/new'
      preLoaderRoute: typeof SocialNewRouteImport
      parentRoute: typeof SocialRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/print': {
      id: '/library/print'
      path: '/library/print'
      fullPath: '/library/print'
      preLoaderRoute: typeof LibraryPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/my': {
      id: '/library/my'
      path: '/library/my'
      fullPath: '/library/my'
      preLoaderRoute: typeof LibraryMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/imported': {
      id: '/library/imported'
      path: '/library/imported'
      fullPath: '/library/imported'
      preLoaderRoute: typeof LibraryImportedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/oracle': {
      id: '/knowledge/oracle'
      path: '/oracle'
      fullPath: '/knowledge/oracle'
      preLoaderRoute: typeof KnowledgeOracleRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/new': {
      id: '/knowledge/new'
      path: '/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof KnowledgeNewRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/ask': {
      id: '/knowledge/ask'
      path: '/ask'
      fullPath: '/knowledge/ask'
      preLoaderRoute: typeof KnowledgeAskRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$entryId': {
      id: '/knowledge/$entryId'
      path: '/$entryId'
      fullPath: '/knowledge/$entryId'
      preLoaderRoute: typeof KnowledgeEntryIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/events/presets': {
      id: '/events/presets'
      path: '/presets'
      fullPath: '/events/presets'
      preLoaderRoute: typeof EventsPresetsRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/next': {
      id: '/events/next'
      path: '/next'
      fullPath: '/events/next'
      preLoaderRoute: typeof EventsNextRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/new': {
      id: '/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof EventsRoute
    }
    '/dev/slidestage-demo': {
      id: '/dev/slidestage-demo'
      path: '/dev/slidestage-demo'
      fullPath: '/dev/slidestage-demo'
      preLoaderRoute: typeof DevSlidestageDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/import': {
      id: '/decks/import'
      path: '/decks/import'
      fullPath: '/decks/import'
      preLoaderRoute: typeof DecksImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/new': {
      id: '/brief/new'
      path: '/brief/new'
      fullPath: '/brief/new'
      preLoaderRoute: typeof BriefNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$deckId': {
      id: '/brief/$deckId'
      path: '/brief/$deckId'
      fullPath: '/brief/$deckId'
      preLoaderRoute: typeof BriefDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/spotlight-preview': {
      id: '/asset/spotlight-preview'
      path: '/asset/spotlight-preview'
      fullPath: '/asset/spotlight-preview'
      preLoaderRoute: typeof AssetSpotlightPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/new': {
      id: '/asset/new'
      path: '/asset/new'
      fullPath: '/asset/new'
      preLoaderRoute: typeof AssetNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$assetId': {
      id: '/asset/$assetId'
      path: '/asset/$assetId'
      fullPath: '/asset/$assetId'
      preLoaderRoute: typeof AssetAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translation': {
      id: '/admin/translation'
      path: '/translation'
      fullPath: '/admin/translation'
      preLoaderRoute: typeof AdminTranslationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/print-library': {
      id: '/admin/print-library'
      path: '/print-library'
      fullPath: '/admin/print-library'
      preLoaderRoute: typeof AdminPrintLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pdf-ingest': {
      id: '/admin/pdf-ingest'
      path: '/pdf-ingest'
      fullPath: '/admin/pdf-ingest'
      preLoaderRoute: typeof AdminPdfIngestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/oracle': {
      id: '/admin/oracle'
      path: '/oracle'
      fullPath: '/admin/oracle'
      preLoaderRoute: typeof AdminOracleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logohub': {
      id: '/admin/logohub'
      path: '/logohub'
      fullPath: '/admin/logohub'
      preLoaderRoute: typeof AdminLogohubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge-hub': {
      id: '/admin/knowledge-hub'
      path: '/knowledge-hub'
      fullPath: '/admin/knowledge-hub'
      preLoaderRoute: typeof AdminKnowledgeHubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/imagery-analytics': {
      id: '/admin/imagery-analytics'
      path: '/imagery-analytics'
      fullPath: '/admin/imagery-analytics'
      preLoaderRoute: typeof AdminImageryAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/imagery': {
      id: '/admin/imagery'
      path: '/imagery'
      fullPath: '/admin/imagery'
      preLoaderRoute: typeof AdminImageryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/icon-studio': {
      id: '/admin/icon-studio'
      path: '/icon-studio'
      fullPath: '/admin/icon-studio'
      preLoaderRoute: typeof AdminIconStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/globallink-share': {
      id: '/admin/globallink-share'
      path: '/globallink-share'
      fullPath: '/admin/globallink-share'
      preLoaderRoute: typeof AdminGloballinkShareRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/globallink': {
      id: '/admin/globallink'
      path: '/globallink'
      fullPath: '/admin/globallink'
      preLoaderRoute: typeof AdminGloballinkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brand-assets': {
      id: '/admin/brand-assets'
      path: '/brand-assets'
      fullPath: '/admin/brand-assets'
      preLoaderRoute: typeof AdminBrandAssetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ab': {
      id: '/admin/ab'
      path: '/ab'
      fullPath: '/admin/ab'
      preLoaderRoute: typeof AdminAbRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/brand-guides/': {
      id: '/knowledge/brand-guides/'
      path: '/brand-guides'
      fullPath: '/knowledge/brand-guides/'
      preLoaderRoute: typeof KnowledgeBrandGuidesIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/decks/$deckId/': {
      id: '/decks/$deckId/'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId/'
      preLoaderRoute: typeof DecksDeckIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/demo/$playbookId': {
      id: '/social/demo/$playbookId'
      path: '/demo/$playbookId'
      fullPath: '/social/demo/$playbookId'
      preLoaderRoute: typeof SocialDemoPlaybookIdRouteImport
      parentRoute: typeof SocialRoute
    }
    '/library/imported_/masters': {
      id: '/library/imported_/masters'
      path: '/library/imported/masters'
      fullPath: '/library/imported/masters'
      preLoaderRoute: typeof LibraryImportedMastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/brand-guides/next-2026-build': {
      id: '/knowledge/brand-guides/next-2026-build'
      path: '/brand-guides/next-2026-build'
      fullPath: '/knowledge/brand-guides/next-2026-build'
      preLoaderRoute: typeof KnowledgeBrandGuidesNext2026BuildRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/brand-guides/next-2026': {
      id: '/knowledge/brand-guides/next-2026'
      path: '/brand-guides/next-2026'
      fullPath: '/knowledge/brand-guides/next-2026'
      preLoaderRoute: typeof KnowledgeBrandGuidesNext2026RouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/brand-guides/$slug': {
      id: '/knowledge/brand-guides/$slug'
      path: '/brand-guides/$slug'
      fullPath: '/knowledge/brand-guides/$slug'
      preLoaderRoute: typeof KnowledgeBrandGuidesSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/events/next_/badges': {
      id: '/events/next_/badges'
      path: '/next/badges'
      fullPath: '/events/next/badges'
      preLoaderRoute: typeof EventsNextBadgesRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/demo/$playbookId': {
      id: '/events/demo/$playbookId'
      path: '/demo/$playbookId'
      fullPath: '/events/demo/$playbookId'
      preLoaderRoute: typeof EventsDemoPlaybookIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/decks/$deckId/print': {
      id: '/decks/$deckId/print'
      path: '/decks/$deckId/print'
      fullPath: '/decks/$deckId/print'
      preLoaderRoute: typeof DecksDeckIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/present': {
      id: '/decks/$deckId/present'
      path: '/decks/$deckId/present'
      fullPath: '/decks/$deckId/present'
      preLoaderRoute: typeof DecksDeckIdPresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/export': {
      id: '/decks/$deckId/export'
      path: '/decks/$deckId/export'
      fullPath: '/decks/$deckId/export'
      preLoaderRoute: typeof DecksDeckIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/document': {
      id: '/decks/$deckId/document'
      path: '/decks/$deckId/document'
      fullPath: '/decks/$deckId/document'
      preLoaderRoute: typeof DecksDeckIdDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pdf-index-proxy': {
      id: '/api/public/pdf-index-proxy'
      path: '/api/public/pdf-index-proxy'
      fullPath: '/api/public/pdf-index-proxy'
      preLoaderRoute: typeof ApiPublicPdfIndexProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brandhub-seed-proxy': {
      id: '/api/public/brandhub-seed-proxy'
      path: '/api/public/brandhub-seed-proxy'
      fullPath: '/api/public/brandhub-seed-proxy'
      preLoaderRoute: typeof ApiPublicBrandhubSeedProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns/kit': {
      id: '/admin/campaigns/kit'
      path: '/kit'
      fullPath: '/admin/campaigns/kit'
      preLoaderRoute: typeof AdminCampaignsKitRouteImport
      parentRoute: typeof AdminCampaignsRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCampaignsRouteChildren {
  AdminCampaignsKitRoute: typeof AdminCampaignsKitRoute
}

const AdminCampaignsRouteChildren: AdminCampaignsRouteChildren = {
  AdminCampaignsKitRoute: AdminCampaignsKitRoute,
}

const AdminCampaignsRouteWithChildren = AdminCampaignsRoute._addFileChildren(
  AdminCampaignsRouteChildren,
)

interface AdminRouteChildren {
  AdminAbRoute: typeof AdminAbRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBrandAssetsRoute: typeof AdminBrandAssetsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRouteWithChildren
  AdminGloballinkRoute: typeof AdminGloballinkRoute
  AdminGloballinkShareRoute: typeof AdminGloballinkShareRoute
  AdminIconStudioRoute: typeof AdminIconStudioRoute
  AdminImageryRoute: typeof AdminImageryRoute
  AdminImageryAnalyticsRoute: typeof AdminImageryAnalyticsRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminKnowledgeHubRoute: typeof AdminKnowledgeHubRoute
  AdminLogohubRoute: typeof AdminLogohubRoute
  AdminOracleRoute: typeof AdminOracleRoute
  AdminPdfIngestRoute: typeof AdminPdfIngestRoute
  AdminPrintLibraryRoute: typeof AdminPrintLibraryRoute
  AdminTranslationRoute: typeof AdminTranslationRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbRoute: AdminAbRoute,
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBrandAssetsRoute: AdminBrandAssetsRoute,
  AdminCampaignsRoute: AdminCampaignsRouteWithChildren,
  AdminGloballinkRoute: AdminGloballinkRoute,
  AdminGloballinkShareRoute: AdminGloballinkShareRoute,
  AdminIconStudioRoute: AdminIconStudioRoute,
  AdminImageryRoute: AdminImageryRoute,
  AdminImageryAnalyticsRoute: AdminImageryAnalyticsRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminKnowledgeHubRoute: AdminKnowledgeHubRoute,
  AdminLogohubRoute: AdminLogohubRoute,
  AdminOracleRoute: AdminOracleRoute,
  AdminPdfIngestRoute: AdminPdfIngestRoute,
  AdminPrintLibraryRoute: AdminPrintLibraryRoute,
  AdminTranslationRoute: AdminTranslationRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsNewRoute: typeof EventsNewRoute
  EventsNextRoute: typeof EventsNextRoute
  EventsPresetsRoute: typeof EventsPresetsRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsDemoPlaybookIdRoute: typeof EventsDemoPlaybookIdRoute
  EventsNextBadgesRoute: typeof EventsNextBadgesRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsNewRoute: EventsNewRoute,
  EventsNextRoute: EventsNextRoute,
  EventsPresetsRoute: EventsPresetsRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsDemoPlaybookIdRoute: EventsDemoPlaybookIdRoute,
  EventsNextBadgesRoute: EventsNextBadgesRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeEntryIdRoute: typeof KnowledgeEntryIdRoute
  KnowledgeAskRoute: typeof KnowledgeAskRoute
  KnowledgeNewRoute: typeof KnowledgeNewRoute
  KnowledgeOracleRoute: typeof KnowledgeOracleRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  KnowledgeBrandGuidesSlugRoute: typeof KnowledgeBrandGuidesSlugRoute
  KnowledgeBrandGuidesNext2026Route: typeof KnowledgeBrandGuidesNext2026Route
  KnowledgeBrandGuidesNext2026BuildRoute: typeof KnowledgeBrandGuidesNext2026BuildRoute
  KnowledgeBrandGuidesIndexRoute: typeof KnowledgeBrandGuidesIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeEntryIdRoute: KnowledgeEntryIdRoute,
  KnowledgeAskRoute: KnowledgeAskRoute,
  KnowledgeNewRoute: KnowledgeNewRoute,
  KnowledgeOracleRoute: KnowledgeOracleRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  KnowledgeBrandGuidesSlugRoute: KnowledgeBrandGuidesSlugRoute,
  KnowledgeBrandGuidesNext2026Route: KnowledgeBrandGuidesNext2026Route,
  KnowledgeBrandGuidesNext2026BuildRoute:
    KnowledgeBrandGuidesNext2026BuildRoute,
  KnowledgeBrandGuidesIndexRoute: KnowledgeBrandGuidesIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface SocialRouteChildren {
  SocialNewRoute: typeof SocialNewRoute
  SocialPresetsRoute: typeof SocialPresetsRoute
  SocialIndexRoute: typeof SocialIndexRoute
  SocialDemoPlaybookIdRoute: typeof SocialDemoPlaybookIdRoute
}

const SocialRouteChildren: SocialRouteChildren = {
  SocialNewRoute: SocialNewRoute,
  SocialPresetsRoute: SocialPresetsRoute,
  SocialIndexRoute: SocialIndexRoute,
  SocialDemoPlaybookIdRoute: SocialDemoPlaybookIdRoute,
}

const SocialRouteWithChildren =
  SocialRoute._addFileChildren(SocialRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AtlasRoute: AtlasRoute,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRouteWithChildren,
  FaqRoute: FaqRoute,
  ImageryRoute: ImageryRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LogohubRoute: LogohubRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SocialRoute: SocialRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  AssetAssetIdRoute: AssetAssetIdRoute,
  AssetNewRoute: AssetNewRoute,
  AssetSpotlightPreviewRoute: AssetSpotlightPreviewRoute,
  BriefDeckIdRoute: BriefDeckIdRoute,
  BriefNewRoute: BriefNewRoute,
  DecksImportRoute: DecksImportRoute,
  DevSlidestageDemoRoute: DevSlidestageDemoRoute,
  LibraryImportedRoute: LibraryImportedRoute,
  LibraryMyRoute: LibraryMyRoute,
  LibraryPrintRoute: LibraryPrintRoute,
  ShareTokenRoute: ShareTokenRoute,
  TestPrintDndRoute: TestPrintDndRoute,
  TestPrintHeroRoute: TestPrintHeroRoute,
  DecksIndexRoute: DecksIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBrandhubSeedProxyRoute: ApiPublicBrandhubSeedProxyRoute,
  ApiPublicPdfIndexProxyRoute: ApiPublicPdfIndexProxyRoute,
  DecksDeckIdDocumentRoute: DecksDeckIdDocumentRoute,
  DecksDeckIdExportRoute: DecksDeckIdExportRoute,
  DecksDeckIdPresentRoute: DecksDeckIdPresentRoute,
  DecksDeckIdPrintRoute: DecksDeckIdPrintRoute,
  LibraryImportedMastersRoute: LibraryImportedMastersRoute,
  DecksDeckIdIndexRoute: DecksDeckIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
