/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksDeckIdRouteImport } from './routes/decks.$deckId'
import { Route as BriefNewRouteImport } from './routes/brief.new'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated.knowledge.index'
import { Route as DecksDeckIdPresentRouteImport } from './routes/decks.$deckId.present'
import { Route as DecksDeckIdExportRouteImport } from './routes/decks.$deckId.export'
import { Route as DecksDeckIdDocumentRouteImport } from './routes/decks.$deckId.document'
import { Route as AuthenticatedKnowledgeNewRouteImport } from './routes/_authenticated.knowledge.new'
import { Route as AuthenticatedKnowledgeEntryIdRouteImport } from './routes/_authenticated.knowledge.$entryId'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefNewRoute = BriefNewRouteImport.update({
  id: '/brief/new',
  path: '/brief/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/_authenticated/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DecksDeckIdPresentRoute = DecksDeckIdPresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => DecksDeckIdRoute,
} as any)
const DecksDeckIdExportRoute = DecksDeckIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => DecksDeckIdRoute,
} as any)
const DecksDeckIdDocumentRoute = DecksDeckIdDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => DecksDeckIdRoute,
} as any)
const AuthenticatedKnowledgeNewRoute =
  AuthenticatedKnowledgeNewRouteImport.update({
    id: '/_authenticated/knowledge/new',
    path: '/knowledge/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedKnowledgeEntryIdRoute =
  AuthenticatedKnowledgeEntryIdRouteImport.update({
    id: '/_authenticated/knowledge/$entryId',
    path: '/knowledge/$entryId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/library': typeof LibraryRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/api/chat': typeof ApiChatRoute
  '/brief/new': typeof BriefNewRoute
  '/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/knowledge/$entryId': typeof AuthenticatedKnowledgeEntryIdRoute
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/decks/$deckId/document': typeof DecksDeckIdDocumentRoute
  '/decks/$deckId/export': typeof DecksDeckIdExportRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/library': typeof LibraryRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/api/chat': typeof ApiChatRoute
  '/brief/new': typeof BriefNewRoute
  '/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/knowledge/$entryId': typeof AuthenticatedKnowledgeEntryIdRoute
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/decks/$deckId/document': typeof DecksDeckIdDocumentRoute
  '/decks/$deckId/export': typeof DecksDeckIdExportRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/library': typeof LibraryRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/api/chat': typeof ApiChatRoute
  '/brief/new': typeof BriefNewRoute
  '/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/_authenticated/knowledge/$entryId': typeof AuthenticatedKnowledgeEntryIdRoute
  '/_authenticated/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/decks/$deckId/document': typeof DecksDeckIdDocumentRoute
  '/decks/$deckId/export': typeof DecksDeckIdExportRoute
  '/decks/$deckId/present': typeof DecksDeckIdPresentRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/library'
    | '/admin/approvals'
    | '/api/chat'
    | '/brief/new'
    | '/decks/$deckId'
    | '/knowledge/$entryId'
    | '/knowledge/new'
    | '/decks/$deckId/document'
    | '/decks/$deckId/export'
    | '/decks/$deckId/present'
    | '/knowledge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/library'
    | '/admin/approvals'
    | '/api/chat'
    | '/brief/new'
    | '/decks/$deckId'
    | '/knowledge/$entryId'
    | '/knowledge/new'
    | '/decks/$deckId/document'
    | '/decks/$deckId/export'
    | '/decks/$deckId/present'
    | '/knowledge'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/library'
    | '/admin/approvals'
    | '/api/chat'
    | '/brief/new'
    | '/decks/$deckId'
    | '/_authenticated/knowledge/$entryId'
    | '/_authenticated/knowledge/new'
    | '/decks/$deckId/document'
    | '/decks/$deckId/export'
    | '/decks/$deckId/present'
    | '/_authenticated/knowledge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  LibraryRoute: typeof LibraryRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  ApiChatRoute: typeof ApiChatRoute
  BriefNewRoute: typeof BriefNewRoute
  DecksDeckIdRoute: typeof DecksDeckIdRouteWithChildren
  AuthenticatedKnowledgeEntryIdRoute: typeof AuthenticatedKnowledgeEntryIdRoute
  AuthenticatedKnowledgeNewRoute: typeof AuthenticatedKnowledgeNewRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/new': {
      id: '/brief/new'
      path: '/brief/new'
      fullPath: '/brief/new'
      preLoaderRoute: typeof BriefNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/present': {
      id: '/decks/$deckId/present'
      path: '/present'
      fullPath: '/decks/$deckId/present'
      preLoaderRoute: typeof DecksDeckIdPresentRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
    '/decks/$deckId/export': {
      id: '/decks/$deckId/export'
      path: '/export'
      fullPath: '/decks/$deckId/export'
      preLoaderRoute: typeof DecksDeckIdExportRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
    '/decks/$deckId/document': {
      id: '/decks/$deckId/document'
      path: '/document'
      fullPath: '/decks/$deckId/document'
      preLoaderRoute: typeof DecksDeckIdDocumentRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
    '/_authenticated/knowledge/new': {
      id: '/_authenticated/knowledge/new'
      path: '/knowledge/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof AuthenticatedKnowledgeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/knowledge/$entryId': {
      id: '/_authenticated/knowledge/$entryId'
      path: '/knowledge/$entryId'
      fullPath: '/knowledge/$entryId'
      preLoaderRoute: typeof AuthenticatedKnowledgeEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DecksDeckIdRouteChildren {
  DecksDeckIdDocumentRoute: typeof DecksDeckIdDocumentRoute
  DecksDeckIdExportRoute: typeof DecksDeckIdExportRoute
  DecksDeckIdPresentRoute: typeof DecksDeckIdPresentRoute
}

const DecksDeckIdRouteChildren: DecksDeckIdRouteChildren = {
  DecksDeckIdDocumentRoute: DecksDeckIdDocumentRoute,
  DecksDeckIdExportRoute: DecksDeckIdExportRoute,
  DecksDeckIdPresentRoute: DecksDeckIdPresentRoute,
}

const DecksDeckIdRouteWithChildren = DecksDeckIdRoute._addFileChildren(
  DecksDeckIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  LibraryRoute: LibraryRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  ApiChatRoute: ApiChatRoute,
  BriefNewRoute: BriefNewRoute,
  DecksDeckIdRoute: DecksDeckIdRouteWithChildren,
  AuthenticatedKnowledgeEntryIdRoute: AuthenticatedKnowledgeEntryIdRoute,
  AuthenticatedKnowledgeNewRoute: AuthenticatedKnowledgeNewRoute,
  AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
