insert into public.module_variants (id, family_id, name, description, permitted_layout_ids, capacity, fallback_variant_id, editable_fields, locked_fields) values
  ('MV-VIZ-SANKEY', 'MF-05', 'Sankey flow', 'Weighted flow diagram from source to target nodes. Ideal for revenue splits, funnel drop-off, workload allocation.', ARRAY['LF-11','LF-14']::text[], '{"items":{"min":3,"max":40},"titleChars":80}'::jsonb, null, ARRAY['title','subtitle','rows','encoding','source']::text[], ARRAY['footer','logo']::text[]),
  ('MV-VIZ-CHORD', 'MF-05', 'Chord — relationships', 'Circular relationship diagram: bilateral links between entities weighted by volume or affinity.', ARRAY['LF-11']::text[], '{"items":{"min":3,"max":30},"titleChars":80}'::jsonb, null, ARRAY['title','rows','encoding','source']::text[], ARRAY['footer','logo']::text[]),
  ('MV-VIZ-BEESWARM', 'MF-05', 'Beeswarm distribution', 'Non-overlapping dot distribution across one or more categories. Good for benchmarks and score comparisons.', ARRAY['LF-11','LF-14']::text[], '{"items":{"min":5,"max":400},"titleChars":80}'::jsonb, null, ARRAY['title','rows','encoding','source']::text[], ARRAY['footer','logo']::text[]),
  ('MV-VIZ-BUMP', 'MF-05', 'Bump chart — rank shifts', 'Rank-over-time chart: shows position changes across periods for a small set of competing entities.', ARRAY['LF-11','LF-14']::text[], '{"items":{"min":3,"max":60},"titleChars":80}'::jsonb, null, ARRAY['title','rows','encoding','source']::text[], ARRAY['footer','logo']::text[]),
  ('MV-VIZ-MARKET-MAP', 'MF-05', 'Market map (bubble matrix)', 'Two-axis bubble plot with size + optional category. For competitive maps, portfolio review, opportunity vs. effort.', ARRAY['LF-11']::text[], '{"items":{"min":4,"max":80},"titleChars":80}'::jsonb, null, ARRAY['title','rows','encoding','source']::text[], ARRAY['footer','logo']::text[]),
  ('MV-VIZ-TREEMAP', 'MF-05', 'Treemap — proportional', 'Nested rectangles sized by value with optional category grouping. For portfolio share and revenue mix.', ARRAY['LF-11']::text[], '{"items":{"min":3,"max":40},"titleChars":80}'::jsonb, null, ARRAY['title','rows','encoding','source']::text[], ARRAY['footer','logo']::text[]),
  ('MV-VIZ-CALENDAR-HEATMAP', 'MF-05', 'Calendar heatmap', 'Daily-value heatmap over a calendar year. Great for activity, incidents, engagement cadence.', ARRAY['LF-11']::text[], '{"items":{"min":30,"max":366},"titleChars":80}'::jsonb, null, ARRAY['title','rows','encoding','source']::text[], ARRAY['footer','logo']::text[]),
  ('MV-ED-HERO-BLEED', 'MF-01', 'Editorial — full-bleed hero', 'Single message over an edge-to-edge photo. One line. Enormous.', ARRAY['LF-05']::text[], '{"titleChars":90,"bodyChars":120}'::jsonb, null, ARRAY['kicker','title','subtitle','mediaSeed','mediaUrl']::text[], ARRAY['footer','logo']::text[]),
  ('MV-ED-HERO-ORB', 'MF-01', 'Editorial — orb composition', 'Two soft aurora orbs behind a minimalist type stack. High air.', ARRAY['LF-01']::text[], '{"titleChars":80,"bodyChars":140}'::jsonb, null, ARRAY['kicker','title','subtitle']::text[], ARRAY['footer','logo','orbs']::text[]),
  ('MV-ED-DIVIDER-XL', 'MF-01', 'Editorial — numbered divider', 'Chapter break: oversized numeral + kicker + title. Poster energy.', ARRAY['LF-05']::text[], '{"titleChars":60,"bodyChars":90}'::jsonb, null, ARRAY['numeral','kicker','title','subtitle']::text[], ARRAY['footer','logo']::text[]),
  ('MV-ED-KICKER-POSTER', 'MF-01', 'Editorial — kicker poster', 'Massive tracked kicker over a display headline on solid brand.', ARRAY['LF-28']::text[], '{"titleChars":60,"bodyChars":80}'::jsonb, null, ARRAY['kicker','title','meta']::text[], ARRAY['footer','logo']::text[]),
  ('MV-ED-STAT-PHOTO', 'MF-05', 'Editorial — stat over photo', 'One giant proof stat lockup floating over a full-bleed photo.', ARRAY['LF-05']::text[], '{"titleChars":60,"bodyChars":160}'::jsonb, null, ARRAY['stat','unit','label','narrative','mediaSeed','mediaUrl']::text[], ARRAY['footer','logo']::text[]),
  ('MV-ED-QUOTE-BLEED', 'MF-05', 'Editorial — full-bleed quote', 'Hero quote treated editorially over a portrait or environment shot.', ARRAY['LF-05']::text[], '{"titleChars":240,"bodyChars":120}'::jsonb, null, ARRAY['quote','attribution','role','mediaSeed','mediaUrl']::text[], ARRAY['footer','logo']::text[]),
  ('MV-STAT-PHOTO-TRIO', 'MF-05', 'Stat — photo trio with figures', 'Three full-bleed photo cards, each carrying one oversized stat figure and caption locked to the frame', ARRAY['LF-11','LF-13']::text[], '{"items":{"min":2,"max":3},"titleChars":80}'::jsonb, null, ARRAY['title','kicker','items[].value','items[].unit','items[].label','items[].body','items[].mediaSeed','items[].mediaUrl']::text[], ARRAY['footer','logo']::text[]),
  ('MV-STAT-PHOTO-BAND', 'MF-05', 'Stat — photo band KPI rail', 'Editorial headline above a full-width photographic band with four KPIs set on the image in tabular type', ARRAY['LF-08','LF-11']::text[], '{"items":{"min":3,"max":4},"titleChars":80}'::jsonb, null, ARRAY['title','kicker','narrative','items[].value','items[].unit','items[].label','mediaSeed','mediaUrl']::text[], ARRAY['footer','logo']::text[]),
  ('MV-STAT-PORTRAIT-PROOF', 'MF-05', 'Stat — portrait proof panel', 'Headshot portrait beside an attributed claim with two supporting stat figures on a hairline rail', ARRAY['LF-08']::text[], '{"items":{"min":1,"max":3},"titleChars":80}'::jsonb, null, ARRAY['title','kicker','quote','attribution','role','items[].value','items[].unit','items[].label','mediaSeed','mediaUrl']::text[], ARRAY['footer','logo']::text[])
on conflict (id) do nothing;