insert into public.module_variants (id, family_id, name, description, permitted_layout_ids, capacity, editable_fields, locked_fields) values
('MV-STAT-HERO-NUMBER','MF-05','Stat — giant hero number','One monumental hero numeral filling the stage with a supporting dek and three micro facts on a hairline rail', array['LF-08','LF-11'], '{"items":{"min":0,"max":3},"titleChars":80}'::jsonb, array['kicker','stat.value','stat.unit','stat.label','narrative','items[].label','items[].value','source'], array['footer','logo']),
('MV-STAT-TYPE-WALL','MF-05','Stat — numeric typography wall','A wall of 6–9 numerals set at graded sizes with no boxes; the grid itself is the composition', array['LF-11','LF-13'], '{"items":{"min":4,"max":9},"titleChars":80}'::jsonb, array['title','kicker','items[].value','items[].unit','items[].label'], array['footer','logo']),
('MV-STAT-KPI-RAIL','MF-05','Stat — type-led KPI rail','Four to five KPIs on a single horizontal rail divided by hairlines, huge tabular numerals with delta chips', array['LF-11','LF-13'], '{"items":{"min":3,"max":5},"titleChars":80}'::jsonb, array['title','kicker','items[].value','items[].unit','items[].label','items[].delta'], array['footer','logo']),
('MV-STAT-ORBIT','MF-05','Stat — orbiting distribution type','Distribution ring at centre with share labels orbiting radially; type positions carry the data', array['LF-08','LF-11'], '{"items":{"min":3,"max":6},"titleChars":80}'::jsonb, array['title','kicker','stat.value','stat.unit','stat.label','items[].label','items[].value'], array['footer','logo']),
('MV-STAT-ACTUAL-TARGET','MF-05','Stat — actual → target → delta','Oversized three-beat progression: actual, target, and the delta between them, joined by arrow rules', array['LF-11'], '{"titleChars":80}'::jsonb, array['title','kicker','actual.value','actual.unit','actual.label','target.value','target.unit','target.label','delta.value','delta.unit','delta.label','narrative'], array['footer','logo']),
('MV-STAT-EDITORIAL-DASH','MF-05','Stat — editorial dashboard','Newspaper-style dashboard: masthead rule, column rules, numerals set as headlines with sparklines beneath', array['LF-11','LF-13'], '{"items":{"min":3,"max":4},"titleChars":80}'::jsonb, array['title','kicker','standfirst','items[].value','items[].unit','items[].label','items[].body','items[].series'], array['footer','logo']),
('MV-STAT-MOSAIC','MF-05','Stat — asymmetrical mosaic','Deliberately uneven mosaic of stats: one dominant figure with satellites at graded weights and spans', array['LF-11','LF-13'], '{"items":{"min":4,"max":6},"titleChars":80}'::jsonb, array['title','kicker','items[].value','items[].unit','items[].label','items[].percent'], array['footer','logo']),
('MV-STAT-IMAGE-TYPE','MF-05','Stat — image + oversized type','Half-bleed photography with an oversized numeral crossing the image edge and a stacked caption rail', array['LF-08'], '{"items":{"min":0,"max":3},"titleChars":80}'::jsonb, array['kicker','stat.value','stat.unit','stat.label','narrative','items[].label','items[].value','mediaSeed','mediaUrl'], array['footer','logo'])
on conflict (id) do update set family_id = excluded.family_id, name = excluded.name, description = excluded.description, permitted_layout_ids = excluded.permitted_layout_ids, capacity = excluded.capacity, editable_fields = excluded.editable_fields, locked_fields = excluded.locked_fields;